In [1]:
import re
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('house_data.csv')
df

,Unnamed: 0,location,price_per_sqft,total_sqft,builtup_area,bhk,price
0,0,Residential land / Plot in Devanahalli,"₹ 1,100/sq.ft.","1,200-12,000 sq.ft. (111-1115 sq.m.) Plot Area",(111-1115 sq.m.) Plot Area,NaN,"₹ 13.2 L - 1.32 Cr₹ 1,100/sq.ft."
1,1,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
2,2,1 BHK Apartment in Thanisandra,"₹ 10,845/sq.ft.",461 sq.ft. (43 sq.m.) Carpet Area,(43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 50 L₹ 10,845/sq.ft."
3,3,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
4,4,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
...,...,...,...,...,...,...,...
324,324,9 Bedroom House in Electronics City Phase 1,"₹ 3,541/sq.ft.","1,200 sq.ft. (111 sq.m.) Plot Area",(111 sq.m.) Plot Area,9 BHK6 Baths,"₹ 1.7 Cr₹ 3,541/sq.ft."
325,325,3 BHK Apartment in Himagiri Meadows,"₹ 4,898/sq.ft.","1,327 sq.ft. (123 sq.m.) Super built-up Area",(123 sq.m.) Super built-up Area,3 BHK3 Baths,"₹ 60 L₹ 4,898/sq.ft."
326,326,Residential land / Plot in Raj Mahal Vilas Ext...,"₹ 45,238/sq.ft.","4,200 sq.ft. (390 sq.m.) Plot Area",(390 sq.m.) Plot Area,NaN,"₹ 19 Cr₹ 45,238/sq.ft."
327,327,Residential land / Plot in Singasandra,"₹ 11,650/sq.ft.",960 sq.ft. (89 sq.m.) Plot Area,(89 sq.m.) Plot Area,NaN,"₹ 1.12 Cr₹ 11,650/sq.ft."
328,328,3 BHK Apartment in Kadugodi,"₹ 4,428/sq.ft.","1,330 sq.ft. (124 sq.m.) Super built-up Area",(124 sq.m.) Super built-up Area,3 BHK3 Baths,"₹ 58 L₹ 4,428/sq.ft."

In [3]:
df = df.drop("Unnamed: 0",axis=1)

In [4]:
df.shape

(329, 6)

In [5]:
df.describe().T

               count unique                                     top freq
location         329    281  Residential land / Plot in Devanahalli    8
price_per_sqft   329    291                          ₹ 6,000/sq.ft.    6
total_sqft       329    256      1,200 sq.ft. (111 sq.m.) Plot Area   30
builtup_area     329    219                   (111 sq.m.) Plot Area   31
bhk              271     35                            2 BHK2 Baths   96
price            329    323       ₹ 45.11  - 50.25 L₹ 10,925/sq.ft.    3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   location        329 non-null    object
 1   price_per_sqft  329 non-null    object
 2   total_sqft      329 non-null    object
 3   builtup_area    329 non-null    object
 4   bhk             271 non-null    object
 5   price           329 non-null    object
dtypes: object(6)
memory usage: 15.5+ KB

In [7]:
df.isnull().sum()

location           0
price_per_sqft     0
total_sqft         0
builtup_area       0
bhk               58
price              0
dtype: int64

In [8]:
df.dtypes

location          object
price_per_sqft    object
total_sqft        object
builtup_area      object
bhk               object
price             object
dtype: object

In [9]:
df

,location,price_per_sqft,total_sqft,builtup_area,bhk,price
0,Residential land / Plot in Devanahalli,"₹ 1,100/sq.ft.","1,200-12,000 sq.ft. (111-1115 sq.m.) Plot Area",(111-1115 sq.m.) Plot Area,NaN,"₹ 13.2 L - 1.32 Cr₹ 1,100/sq.ft."
1,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
2,1 BHK Apartment in Thanisandra,"₹ 10,845/sq.ft.",461 sq.ft. (43 sq.m.) Carpet Area,(43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 50 L₹ 10,845/sq.ft."
3,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
4,1 BHK Apartment in Thanisandra,"₹ 10,925/sq.ft.",412-461 sq.ft. (38-43 sq.m.) Carpet Area,(38-43 sq.m.) Carpet Area,1 BHK1 Bath,"₹ 45.11 - 50.25 L₹ 10,925/sq.ft."
...,...,...,...,...,...,...
324,9 Bedroom House in Electronics City Phase 1,"₹ 3,541/sq.ft.","1,200 sq.ft. (111 sq.m.) Plot Area",(111 sq.m.) Plot Area,9 BHK6 Baths,"₹ 1.7 Cr₹ 3,541/sq.ft."
325,3 BHK Apartment in Himagiri Meadows,"₹ 4,898/sq.ft.","1,327 sq.ft. (123 sq.m.) Super built-up Area",(123 sq.m.) Super built-up Area,3 BHK3 Baths,"₹ 60 L₹ 4,898/sq.ft."
326,Residential land / Plot in Raj Mahal Vilas Ext...,"₹ 45,238/sq.ft.","4,200 sq.ft. (390 sq.m.) Plot Area",(390 sq.m.) Plot Area,NaN,"₹ 19 Cr₹ 45,238/sq.ft."
327,Residential land / Plot in Singasandra,"₹ 11,650/sq.ft.",960 sq.ft. (89 sq.m.) Plot Area,(89 sq.m.) Plot Area,NaN,"₹ 1.12 Cr₹ 11,650/sq.ft."
328,3 BHK Apartment in Kadugodi,"₹ 4,428/sq.ft.","1,330 sq.ft. (124 sq.m.) Super built-up Area",(124 sq.m.) Super built-up Area,3 BHK3 Baths,"₹ 58 L₹ 4,428/sq.ft."

In [10]:
location = df['location'].tolist()

print(location)

['Residential land / Plot in Devanahalli', '1 BHK Apartment in Thanisandra', '1 BHK Apartment in Thanisandra', '1 BHK Apartment in Thanisandra', '1 BHK Apartment in Thanisandra', '2 BHK Apartment in Thanisandra', '1 BHK Apartment in Thanisandra', '3 BHK Apartment in 3rd Phase JP Nagar', '2 BHK Apartment in 6th Block Jayanagar', '2 BHK Apartment in CV Raman Nagar', '11 Bedroom House in Chikkalasandra', '6 Bedroom House in Jalahalli West', '5 Bedroom House in Tavarekere', '5 Bedroom House in Suragajakkanahalli', '3 BHK Apartment in Sarjapura Attibele Road', '3 BHK Apartment in Kodichikkanahalli', '3 BHK Apartment in Electronic City Phase 2', '2 BHK Apartment in CV Raman Nagar', '5 Bedroom House in Indira Nagar Stage 2', '3 BHK Apartment in Tumkur Road', '2 Bedroom House in Bannerghatta Road', '12 Bedroom House in Subbannaiah Palya', '2 Bedroom House in Sarjapur Road', 'Residential land / Plot in Kengeri', '3 BHK Apartment in Thanisandra', '2 BHK Apartment in Sarjapur Road', '6 Bedroom House in Mico Layout', '9 Bedroom House in OMBR Layout', '3 Bedroom House in Hennur Road', '2 BHK Apartment in Billekahalli', '2 Bedroom House in Bidadi', '3 Bedroom House in 5th Phase JP Nagar', '3 BHK Apartment in KR Puram', '7 Bedroom House in Rajarajeshwari Nagar', 'Residential land / Plot in Devanahalli', 'Residential land / Plot in Devanahalli', '2 BHK Apartment in Horamavu', '2 BHK Apartment in BTM Layout', 'Residential land / Plot in Hennur Road', '3 BHK Apartment in Kanaka Nagar', '3 BHK Apartment in Vijayanagar', '3 BHK Apartment in Kanakapura Road', 'Residential land / Plot in Sarjapur Road', '2 BHK Apartment in Hebbal', '3 BHK Apartment in Budigere Cross', '2 BHK Apartment in Jalahalli East', '3 BHK Apartment in Sarjapur Road', 'Residential land / Plot in ITC Factory', '2 BHK Apartment in Kadugodi', '2 BHK Apartment in Indira Nagar', '3 Bedroom House in RT Nagar', '6 Bedroom House in T Dasarahalli', 'Residential land / Plot in Devanahalli', '1 Bedroom House in Marathahalli', '3 BHK Apartment in Hebbal', '2 BHK Apartment in Kanakapura Road', '2 BHK Apartment in Maruthi Nagar, Malleshpalya', '3 BHK Apartment in Doddanagamangala', 'Residential land / Plot in Kanakapura Road', '2 BHK Apartment in Electronic City', 'Residential land / Plot in Kyalasanahalli', '3 BHK Apartment in Yelahanka', 'Residential land / Plot in Byadarahalli', '3 Bedroom House in Budigere Cross', '5 Bedroom House in Kengeri Satellite Town Stage 2', '2 BHK Apartment in Murugeshpalya', '3 BHK Apartment in RT Nagar', '2 BHK Apartment in Begur', 'Residential land / Plot in IVC Road', '4 BHK Apartment in Basavangudi', '3 Bedroom House in Mathikere', '2 BHK Apartment in Harlur Road', '4 Bedroom House in Basaveshwara Nagar', '4 BHK Apartment in Postal Colony', '2 BHK Apartment in Devanahalli', '9 Bedroom House in A Narayanapura', '11 Bedroom House in 8th Phase JP Nagar', '3 BHK Apartment in Yelahanka', '3 BHK Apartment in Vidyaranyapura', '3 BHK Apartment in Vidyaranyapura', '2 BHK Apartment in Electronic City', '2 BHK Apartment in Bommanahalli', '5 Bedroom House in Kasturi Nagar', '3 BHK Apartment in Electronic City', '2 BHK Apartment in Ramanashree Enclave', '14 Bedroom House in Hongasandra', 'Residential land / Plot in Whitefield', 'Residential land / Plot in Banashankari Stage 6', '2 BHK Apartment in Devi Nagar', '3 BHK Apartment in JP Nagar', 'Residential land / Plot in Abbigere', 'Residential land / Plot in Sadahalli', '2 BHK Apartment in Kudlu Gate', '3 BHK Apartment in 9th Phase JP Nagar', 'Residential land / Plot in 8th Phase JP Nagar', '3 BHK Apartment in Jakkur', '2 BHK Apartment in Mysore Road', '6 Bedroom House in Surabhi Layout', '3 Bedroom House in Sarjapur Road', 'Residential land / Plot in Jakkur', 'Residential land / Plot in Chikkaballapur', '3 Bedroom House in MS Pallya', '2 BHK Apartment in Rajapura', 'Residential land / Plot in 6th Block Sir M Vishweshwaraiah Layout', '2 BHK Apartment in Jakkur', '3 BHK Apartment in Marasandra', '6 BHK Independent Builder Floor in Yelahanka New Town', '2 BHK Apartment in Tata Nagar', '2 BHK Apartment in Varthur Road', 'Residential land / Plot in Gollarapalya Hosahalli', '4 Bedroom House in Tumkur Road', '3 BHK Apartment in JP Nagar', '11 Bedroom House in Kothanur', 'Residential land / Plot in Upadhyaya Layout', '2 BHK Apartment in Jayanagar', '2 BHK Apartment in Electronic City Phase 2', '3 BHK Apartment in Kaikondrahalli', 'Residential land / Plot in Bisuvanahalli', '7 Bedroom House in 3rd Phase JP Nagar', '3 BHK Apartment in Jalahalli', '3 Bedroom Farm house in Bannerghatta', '12 Bedroom House in Sahakara Nagar', '3 Bedroom House in Attibele', '3 Bedroom House in Jnanabharathi Layout', '3 BHK Apartment in Sri Balaji Krupa Layout', '8 Bedroom House in NRI Layout,Ramuthy nagar', '3 BHK Apartment in Whitefield', '2 BHK Apartment in Tumkur Road', '2 BHK Apartment in Nandi Durga Road', '4 BHK Apartment in Cooke Town', '2 BHK Apartment in Cox Town', '2 BHK Apartment in Kengeri Satellite Town', '12 Bedroom House in Electronic City', '3 BHK Apartment in KR Puram', '2 BHK Apartment in Kanakapura Road', 'Residential land / Plot in Kumaraswamy Layout', 'Residential land / Plot in Devanahalli', '3 BHK Apartment in Devarachikkanahalli', '2 BHK Apartment in Yelahanka New Town', '3 BHK Apartment in Sarjapur Road', '2 BHK Independent Builder Floor in Domlur', '4 Bedroom House in Malleshwaram', '3 BHK Apartment in Hennur Road', '3 BHK Apartment in HBR Layout', '2 BHK Apartment in Tejaswini Nagar', '2 BHK Apartment in Atmananda Colony', '2 BHK Apartment in ISRO Layout', '2 BHK Apartment in Yelahanka', '4 BHK Independent Builder Floor in 3rd Phase JP Nagar', '2 BHK Apartment in Koramangala', '3 BHK Apartment in Sampangi Rama Nagar', 'Residential land / Plot in IVC Road', 'Residential land / Plot in Nelamangala', 'Residential land / Plot in Kothnur Narayanapura', '3 BHK Independent Builder Floor in Benson Town', '3 BHK Apartment in Hoodi', '4 Bedroom House in Kaggadasapura', '2 BHK Apartment in Near International Airport', '3 BHK Independent Builder Floor in Frazer Town', '3 BHK Apartment in Kodihalli', '2 BHK Apartment in Mallasandra', '13 Bedroom House in Belatur, KR Puram', '2 Bedroom House in Naganathapura', '2 BHK Apartment in Chokkanahalli', '2 BHK Apartment in Bannerghatta Road', '2 BHK Apartment in Mallasandra', '3 BHK Apartment in Padmanabhanagar', '12 Bedroom House in Munnekollal', '2 BHK Apartment in Bommanahalli', 'Residential land / Plot in Kanakapura Road', '3 BHK Apartment in Kothanur', '3 BHK Apartment in Jakkur', '9 BHK Independent Builder Floor in Teachers Colony', '3 BHK Apartment in Near International Airport', '2 BHK Apartment in Choodasandra', '3 BHK Independent Builder Floor in BEML Layout', '4 Bedroom House in Hessarghatta', '2 BHK Apartment in Uttarahalli', 'Residential land / Plot in Yelahanka', 'Residential land / Plot in Battarahalli', '3 Bedroom House in Bendiganahalli', 'Residential land / Plot in Nagadevanahalli', '3 BHK Apartment in Sarjapur Road', '3 BHK Apartment in Yelahanka New Town', 'Residential land / Plot in Devanahalli', '2 BHK Apartment in Yelahanka', '2 BHK Apartment in Yelahanka', '3 BHK Apartment in Uttarahalli', '2 BHK Apartment in Rachenahalli', '4 Bedroom House in Hoysalanagar', '4 Bedroom House in Hebbal', '7 Bedroom House in KR Puram', '3 BHK Independent Builder Floor in Gubbalala', '4 BHK Independent Builder Floor in Hebbal', '3 Bedroom House in Sudhama Nagar', 'Residential land / Plot in Gattahalli', '2 BHK Apartment in Electronic City', '1 BHK Apartment in Jalahalli East', '1 Bedroom House in Rajarajeshwari Nagar', '2 BHK Apartment in Mysore Road', '3 BHK Apartment in Thirumenahalli', '6 Bedroom House in Indira Nagar Stage 2', '3 BHK Apartment in Yelahanka', '3 BHK Apartment in Rayasandra', '2 BHK Apartment in Banashankari Stage I', '1 BHK Apartment in Thirupalya', '3 BHK Apartment in Choodasandra', 'Residential land / Plot in Banashankari Stage 6', '14 Bedroom House in Horamavu Agara', '3 Bedroom House in Chikka Tirupathi', '2 BHK Apartment in Sector 3 HSR Layout', '3 BHK Apartment in Whitefield', '3 BHK Apartment in Vijayanagar', 'Residential land / Plot in Rajajinagar', '2 BHK Apartment in 8th Phase JP Nagar', 'Residential land / Plot in KR Puram', '3 BHK Apartment in Doddaballapur Road', 'Residential land / Plot in Margondanahalli', '4 Bedroom House in Ashwathnagar', '4 BHK Apartment in Thanisandra Main Road', '3 BHK Apartment in HSR Layout', '4 Bedroom House in Rajarajeshwari Nagar', 'Residential land / Plot in SBI Colony, Devarachiknahalli, Bommanahalli', '2 Bedroom House in Devanahalli', '2 BHK Apartment in Kasturi Nagar', '3 BHK Apartment in Yelahanka, Bangalore', 'Residential land / Plot in Sarjapur Road', 'Residential land / Plot in 8th Phase JP Nagar', '2 Bedroom House in Attibele', 'Residential land / Plot in Hegganahalli', '2 BHK Apartment in Sahakara Nagar', '3 BHK Apartment in Gubbalala', 'Residential land / Plot in Devanahalli', '7 Bedroom House in Hongasandra', '4 Bedroom House in Kadugodi', '10 Bedroom House in Banashankari Stage I', '3 BHK Apartment in Talacauvery Layout', '2 Bedroom House in RT Nagar', '2 BHK Apartment in Yelahanka', '3 Bedroom House in Sector 1 HSR Layout', '2 BHK Apartment in Nelamangala', '2 BHK Apartment in Hallehalli', '3 BHK Apartment in Banashankari', '3 BHK Apartment in Koramangala', '2 BHK Apartment in BTM 1st Stage', 'Residential land / Plot in Srirampura', '3 BHK Apartment in Vidyaranyapura', '3 BHK Apartment in Kadugodi', '3 BHK Apartment in Sahakara Nagar', 'Residential land / Plot in Chikka Tirupathi', '2 BHK Apartment in Sarjapur Road', 'Residential land / Plot in Machohalli', '2 BHK Apartment in 5th Phase JP Nagar', '3 BHK Apartment in Dollars Colony', '4 Bedroom House in Vishveshwarya Layout', '2 BHK Apartment in Kothanur', '2 BHK Apartment in Hoodi', '2 BHK Apartment in BEL Road', '9 BHK Independent Builder Floor in Kadubeesanahalli', '2 BHK Apartment in Anantapuram', '3 Bedroom House in Sunkadakatte', '5 Bedroom House in Kathriguppe', '2 Bedroom House in KR Puram', 'Residential land / Plot in Hoskote', '2 BHK Apartment in Chikkabanavar', '2 BHK Apartment in Marathahalli', 'Residential land / Plot in Kaggalipura', '3 BHK Apartment in Electronic City Phase 2', '2 BHK Apartment in BTM 2nd Stage', '3 BHK Apartment in Chandapura', '2 BHK Apartment in Peenya', '2 BHK Apartment in Channasandra Layout', 'Residential land / Plot in Sir M Vishweshwaraiah layout', 'Residential land / Plot in Bettahalsoor', '3 BHK Apartment in Murugeshpalya', '2 BHK Apartment in Kirloskar Layout', '2 BHK Apartment in Hennur Road', '3 BHK Apartment in Vinayak Nagar', '2 BHK Apartment in Hebbal', '3 BHK Apartment in RWF West Colony', '2 BHK Apartment in Benson Town', '2 BHK Apartment in Chandapura', '3 BHK Apartment in Amruthahalli', '3 BHK Apartment in Kumarapalli', '2 Bedroom House in Horamavu', '2 Bedroom House in Banjara Layout', '2 BHK Apartment in Dodda Nekkundi', '3 Bedroom House in Sidihosakote', '3 BHK Independent Builder Floor in Arekere', '2 BHK Apartment in Ulsoor', 'Residential land / Plot in Devanahalli', '4 Bedroom House in Budigere Cross', '12 Bedroom House in Panduranga Nagar', '3 BHK Apartment in Electronics City Phase 1', '3 BHK Apartment in Budigere', '2 BHK Apartment in Sarjapur', '2 BHK Apartment in Dasarahalli', '3 BHK Apartment in Jalahalli', '2 BHK Apartment in Sun City Layout', 'Residential land / Plot in Vishwanatha Nagenahalli', 'Residential land / Plot in Sannatammanahalli', '2 BHK Apartment in Yelahanka', '3 BHK Apartment in Sompura', '2 BHK Apartment in Sahakara Nagar', 'Residential land / Plot in 6th Block Rajaji Nagar', '5 Bedroom House in Koramangala', '3 BHK Apartment in KR Puram', '3 BHK Apartment in Ramamurthy Nagar', '14 Bedroom House in Electronic City', 'Residential land / Plot in Nandi Hills', '2 BHK Apartment in PNS Layout', 'Residential land / Plot in Abbigere', '3 BHK Apartment in CV Raman Nagar', '4 BHK Apartment in Kasturi Nagar', '3 BHK Apartment in Frazer Town', '11 Bedroom House in Nataraja Layout', '3 BHK Apartment in Whitefield', '3 BHK Apartment in Sarjapur', '2 BHK Apartment in 5th Phase JP Nagar', '3 Bedroom House in TC Palaya', '4 BHK Apartment in Sadashiva Nagar', '2 BHK Apartment in Kengeri', '3 BHK Apartment in Begur Road', '3 Bedroom House in Banashankari Stage 6', '9 Bedroom House in Electronics City Phase 1', '3 BHK Apartment in Himagiri Meadows', 'Residential land / Plot in Raj Mahal Vilas Extension', 'Residential land / Plot in Singasandra', '3 BHK Apartment in Kadugodi']

In [11]:
pattern = r"in\s(.*)"

#list to store matching strings
loc = []

for string in location:
    match = re.search(pattern, string, re.IGNORECASE)
    if match:
        loc.append(match.group(1))

print(loc)

['Devanahalli', 'Thanisandra', 'Thanisandra', 'Thanisandra', 'Thanisandra', 'Thanisandra', 'Thanisandra', '3rd Phase JP Nagar', '6th Block Jayanagar', 'CV Raman Nagar', 'Chikkalasandra', 'Jalahalli West', 'Tavarekere', 'Suragajakkanahalli', 'Sarjapura Attibele Road', 'Kodichikkanahalli', 'Electronic City Phase 2', 'CV Raman Nagar', 'Indira Nagar Stage 2', 'Tumkur Road', 'Bannerghatta Road', 'Subbannaiah Palya', 'Sarjapur Road', 'Kengeri', 'Thanisandra', 'Sarjapur Road', 'Mico Layout', 'OMBR Layout', 'Hennur Road', 'Billekahalli', 'Bidadi', '5th Phase JP Nagar', 'KR Puram', 'Rajarajeshwari Nagar', 'Devanahalli', 'Devanahalli', 'Horamavu', 'BTM Layout', 'Hennur Road', 'Kanaka Nagar', 'Vijayanagar', 'Kanakapura Road', 'Sarjapur Road', 'Hebbal', 'Budigere Cross', 'Jalahalli East', 'Sarjapur Road', 'ITC Factory', 'Kadugodi', 'Indira Nagar', 'RT Nagar', 'T Dasarahalli', 'Devanahalli', 'Marathahalli', 'Hebbal', 'Kanakapura Road', 'Maruthi Nagar, Malleshpalya', 'Doddanagamangala', 'Kanakapura Road', 'Electronic City', 'Kyalasanahalli', 'Yelahanka', 'Byadarahalli', 'Budigere Cross', 'Kengeri Satellite Town Stage 2', 'Murugeshpalya', 'RT Nagar', 'Begur', 'IVC Road', 'Basavangudi', 'Mathikere', 'Harlur Road', 'Basaveshwara Nagar', 'Postal Colony', 'Devanahalli', 'A Narayanapura', '8th Phase JP Nagar', 'Yelahanka', 'Vidyaranyapura', 'Vidyaranyapura', 'Electronic City', 'Bommanahalli', 'Kasturi Nagar', 'Electronic City', 'Ramanashree Enclave', 'Hongasandra', 'Whitefield', 'Banashankari Stage 6', 'Devi Nagar', 'JP Nagar', 'Abbigere', 'Sadahalli', 'Kudlu Gate', '9th Phase JP Nagar', '8th Phase JP Nagar', 'Jakkur', 'Mysore Road', 'Surabhi Layout', 'Sarjapur Road', 'Jakkur', 'Chikkaballapur', 'MS Pallya', 'Rajapura', '6th Block Sir M Vishweshwaraiah Layout', 'Jakkur', 'Marasandra', 'Yelahanka New Town', 'Tata Nagar', 'Varthur Road', 'Gollarapalya Hosahalli', 'Tumkur Road', 'JP Nagar', 'Kothanur', 'Upadhyaya Layout', 'Jayanagar', 'Electronic City Phase 2', 'Kaikondrahalli', 'Bisuvanahalli', '3rd Phase JP Nagar', 'Jalahalli', 'Bannerghatta', 'Sahakara Nagar', 'Attibele', 'Jnanabharathi Layout', 'Sri Balaji Krupa Layout', 'NRI Layout,Ramuthy nagar', 'Whitefield', 'Tumkur Road', 'Nandi Durga Road', 'Cooke Town', 'Cox Town', 'Kengeri Satellite Town', 'Electronic City', 'KR Puram', 'Kanakapura Road', 'Kumaraswamy Layout', 'Devanahalli', 'Devarachikkanahalli', 'Yelahanka New Town', 'Sarjapur Road', 'Domlur', 'Malleshwaram', 'Hennur Road', 'HBR Layout', 'Tejaswini Nagar', 'Atmananda Colony', 'ISRO Layout', 'Yelahanka', '3rd Phase JP Nagar', 'Koramangala', 'Sampangi Rama Nagar', 'IVC Road', 'Nelamangala', 'Kothnur Narayanapura', 'Benson Town', 'Hoodi', 'Kaggadasapura', 'Near International Airport', 'Frazer Town', 'Kodihalli', 'Mallasandra', 'Belatur, KR Puram', 'Naganathapura', 'Chokkanahalli', 'Bannerghatta Road', 'Mallasandra', 'Padmanabhanagar', 'Munnekollal', 'Bommanahalli', 'Kanakapura Road', 'Kothanur', 'Jakkur', 'Teachers Colony', 'Near International Airport', 'Choodasandra', 'BEML Layout', 'Hessarghatta', 'Uttarahalli', 'Yelahanka', 'Battarahalli', 'Bendiganahalli', 'Nagadevanahalli', 'Sarjapur Road', 'Yelahanka New Town', 'Devanahalli', 'Yelahanka', 'Yelahanka', 'Uttarahalli', 'Rachenahalli', 'Hoysalanagar', 'Hebbal', 'KR Puram', 'Gubbalala', 'Hebbal', 'Sudhama Nagar', 'Gattahalli', 'Electronic City', 'Jalahalli East', 'Rajarajeshwari Nagar', 'Mysore Road', 'Thirumenahalli', 'Indira Nagar Stage 2', 'Yelahanka', 'Rayasandra', 'Banashankari Stage I', 'Thirupalya', 'Choodasandra', 'Banashankari Stage 6', 'Horamavu Agara', 'Chikka Tirupathi', 'Sector 3 HSR Layout', 'Whitefield', 'Vijayanagar', 'Rajajinagar', '8th Phase JP Nagar', 'KR Puram', 'Doddaballapur Road', 'Margondanahalli', 'Ashwathnagar', 'Thanisandra Main Road', 'HSR Layout', 'Rajarajeshwari Nagar', 'SBI Colony, Devarachiknahalli, Bommanahalli', 'Devanahalli', 'Kasturi Nagar', 'Yelahanka, Bangalore', 'Sarjapur Road', '8th Phase JP Nagar', 'Attibele', 'Hegganahalli', 'Sahakara Nagar', 'Gubbalala', 'Devanahalli', 'Hongasandra', 'Kadugodi', 'Banashankari Stage I', 'Talacauvery Layout', 'RT Nagar', 'Yelahanka', 'Sector 1 HSR Layout', 'Nelamangala', 'Hallehalli', 'Banashankari', 'Koramangala', 'BTM 1st Stage', 'Srirampura', 'Vidyaranyapura', 'Kadugodi', 'Sahakara Nagar', 'Chikka Tirupathi', 'Sarjapur Road', 'Machohalli', '5th Phase JP Nagar', 'Dollars Colony', 'Vishveshwarya Layout', 'Kothanur', 'Hoodi', 'BEL Road', 'Kadubeesanahalli', 'Anantapuram', 'Sunkadakatte', 'Kathriguppe', 'KR Puram', 'Hoskote', 'Chikkabanavar', 'Marathahalli', 'Kaggalipura', 'Electronic City Phase 2', 'BTM 2nd Stage', 'Chandapura', 'Peenya', 'Channasandra Layout', 'Sir M Vishweshwaraiah layout', 'Bettahalsoor', 'Murugeshpalya', 'Kirloskar Layout', 'Hennur Road', 'Vinayak Nagar', 'Hebbal', 'RWF West Colony', 'Benson Town', 'Chandapura', 'Amruthahalli', 'Kumarapalli', 'Horamavu', 'Banjara Layout', 'Dodda Nekkundi', 'Sidihosakote', 'Arekere', 'Ulsoor', 'Devanahalli', 'Budigere Cross', 'Panduranga Nagar', 'Electronics City Phase 1', 'Budigere', 'Sarjapur', 'Dasarahalli', 'Jalahalli', 'Sun City Layout', 'Vishwanatha Nagenahalli', 'Sannatammanahalli', 'Yelahanka', 'Sompura', 'Sahakara Nagar', '6th Block Rajaji Nagar', 'Koramangala', 'KR Puram', 'Ramamurthy Nagar', 'Electronic City', 'Nandi Hills', 'PNS Layout', 'Abbigere', 'CV Raman Nagar', 'Kasturi Nagar', 'Frazer Town', 'Nataraja Layout', 'Whitefield', 'Sarjapur', '5th Phase JP Nagar', 'TC Palaya', 'Sadashiva Nagar', 'Kengeri', 'Begur Road', 'Banashankari Stage 6', 'Electronics City Phase 1', 'Himagiri Meadows', 'Raj Mahal Vilas Extension', 'Singasandra', 'Kadugodi']

In [12]:
len(loc)

329

In [13]:
pattern = r"(.*?)\sin"

#list to store modified strings
modified_strings = []

for string in location:
    match = re.search(pattern, string, re.IGNORECASE)
    if match:
        modified_strings.append(match.group(1))
    else:
        modified_strings.append(string)

print(modified_strings)

['Residential land / Plot', '1 BHK Apartment', '1 BHK Apartment', '1 BHK Apartment', '1 BHK Apartment', '2 BHK Apartment', '1 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '11 Bedroom House', '6 Bedroom House', '5 Bedroom House', '5 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '5 Bedroom House', '3 BHK Apartment', '2 Bedroom House', '12 Bedroom House', '2 Bedroom House', 'Residential land / Plot', '3 BHK Apartment', '2 BHK Apartment', '6 Bedroom House', '9 Bedroom House', '3 Bedroom House', '2 BHK Apartment', '2 Bedroom House', '3 Bedroom House', '3 BHK Apartment', '7 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '2 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', '2 BHK Apartment', '3 Bedroom House', '6 Bedroom House', 'Residential land / Plot', '1 Bedroom House', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', 'Residential land / Plot', '3 Bedroom House', '5 Bedroom House', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '4 BHK Apartment', '3 Bedroom House', '2 BHK Apartment', '4 Bedroom House', '4 BHK Apartment', '2 BHK Apartment', '9 Bedroom House', '11 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '5 Bedroom House', '3 BHK Apartment', '2 BHK Apartment', '14 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '2 BHK Apartment', '6 Bedroom House', '3 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '3 Bedroom House', '2 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', '6 BHK', '2 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '4 Bedroom House', '3 BHK Apartment', '11 Bedroom House', 'Residential land / Plot', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '7 Bedroom House', '3 BHK Apartment', '3 Bedroom Farm house', '12 Bedroom House', '3 Bedroom House', '3 Bedroom House', '3 BHK Apartment', '8 Bedroom House', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '4 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '12 Bedroom House', '3 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '3 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK', '4 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '4 BHK', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Residential land / Plot', '3 BHK', '3 BHK Apartment', '4 Bedroom House', '2 BHK Apartment', '3 BHK', '3 BHK Apartment', '2 BHK Apartment', '13 Bedroom House', '2 Bedroom House', '2 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '12 Bedroom House', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '3 BHK Apartment', '9 BHK', '3 BHK Apartment', '2 BHK Apartment', '3 BHK', '4 Bedroom House', '2 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '3 Bedroom House', 'Residential land / Plot', '3 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '4 Bedroom House', '4 Bedroom House', '7 Bedroom House', '3 BHK', '4 BHK', '3 Bedroom House', 'Residential land / Plot', '2 BHK Apartment', '1 BHK Apartment', '1 Bedroom House', '2 BHK Apartment', '3 BHK Apartment', '6 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '1 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '14 Bedroom House', '3 Bedroom House', '2 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', 'Residential land / Plot', '4 Bedroom House', '4 BHK Apartment', '3 BHK Apartment', '4 Bedroom House', 'Residential land / Plot', '2 Bedroom House', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '2 Bedroom House', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '7 Bedroom House', '4 Bedroom House', '10 Bedroom House', '3 BHK Apartment', '2 Bedroom House', '2 BHK Apartment', '3 Bedroom House', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', '4 Bedroom House', '2 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '9 BHK', '2 BHK Apartment', '3 Bedroom House', '5 Bedroom House', '2 Bedroom House', 'Residential land / Plot', '2 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '3 BHK Apartment', '2 Bedroom House', '2 Bedroom House', '2 BHK Apartment', '3 Bedroom House', '3 BHK', '2 BHK Apartment', 'Residential land / Plot', '4 Bedroom House', '12 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '2 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', 'Residential land / Plot', '5 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '14 Bedroom House', 'Residential land / Plot', '2 BHK Apartment', 'Residential land / Plot', '3 BHK Apartment', '4 BHK Apartment', '3 BHK Apartment', '11 Bedroom House', '3 BHK Apartment', '3 BHK Apartment', '2 BHK Apartment', '3 Bedroom House', '4 BHK Apartment', '2 BHK Apartment', '3 BHK Apartment', '3 Bedroom House', '9 Bedroom House', '3 BHK Apartment', 'Residential land / Plot', 'Residential land / Plot', '3 BHK Apartment']

In [14]:
words_to_drop = ["BHK"]

#regular expression pattern to match and drop words
pattern = "|".join(words_to_drop)

#list to store modified strings
modified_strings1 = []

for string in modified_strings:
    modified_string = re.sub(pattern, "", string, flags=re.IGNORECASE)
    modified_strings1.append(modified_string)

print(modified_strings1)

['Residential land / Plot', '1  Apartment', '1  Apartment', '1  Apartment', '1  Apartment', '2  Apartment', '1  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', '11 Bedroom House', '6 Bedroom House', '5 Bedroom House', '5 Bedroom House', '3  Apartment', '3  Apartment', '3  Apartment', '2  Apartment', '5 Bedroom House', '3  Apartment', '2 Bedroom House', '12 Bedroom House', '2 Bedroom House', 'Residential land / Plot', '3  Apartment', '2  Apartment', '6 Bedroom House', '9 Bedroom House', '3 Bedroom House', '2  Apartment', '2 Bedroom House', '3 Bedroom House', '3  Apartment', '7 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '2  Apartment', '2  Apartment', 'Residential land / Plot', '3  Apartment', '3  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', '3  Apartment', '2  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', '2  Apartment', '3 Bedroom House', '6 Bedroom House', 'Residential land / Plot', '1 Bedroom House', '3  Apartment', '2  Apartment', '2  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', 'Residential land / Plot', '3  Apartment', 'Residential land / Plot', '3 Bedroom House', '5 Bedroom House', '2  Apartment', '3  Apartment', '2  Apartment', 'Residential land / Plot', '4  Apartment', '3 Bedroom House', '2  Apartment', '4 Bedroom House', '4  Apartment', '2  Apartment', '9 Bedroom House', '11 Bedroom House', '3  Apartment', '3  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', '5 Bedroom House', '3  Apartment', '2  Apartment', '14 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '2  Apartment', '3  Apartment', 'Residential land / Plot', 'Residential land / Plot', '2  Apartment', '3  Apartment', 'Residential land / Plot', '3  Apartment', '2  Apartment', '6 Bedroom House', '3 Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '3 Bedroom House', '2  Apartment', 'Residential land / Plot', '2  Apartment', '3  Apartment', '6 ', '2  Apartment', '2  Apartment', 'Residential land / Plot', '4 Bedroom House', '3  Apartment', '11 Bedroom House', 'Residential land / Plot', '2  Apartment', '2  Apartment', '3  Apartment', 'Residential land / Plot', '7 Bedroom House', '3  Apartment', '3 Bedroom Farm house', '12 Bedroom House', '3 Bedroom House', '3 Bedroom House', '3  Apartment', '8 Bedroom House', '3  Apartment', '2  Apartment', '2  Apartment', '4  Apartment', '2  Apartment', '2  Apartment', '12 Bedroom House', '3  Apartment', '2  Apartment', 'Residential land / Plot', 'Residential land / Plot', '3  Apartment', '2  Apartment', '3  Apartment', '2 ', '4 Bedroom House', '3  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', '2  Apartment', '2  Apartment', '4 ', '2  Apartment', '3  Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Residential land / Plot', '3 ', '3  Apartment', '4 Bedroom House', '2  Apartment', '3 ', '3  Apartment', '2  Apartment', '13 Bedroom House', '2 Bedroom House', '2  Apartment', '2  Apartment', '2  Apartment', '3  Apartment', '12 Bedroom House', '2  Apartment', 'Residential land / Plot', '3  Apartment', '3  Apartment', '9 ', '3  Apartment', '2  Apartment', '3 ', '4 Bedroom House', '2  Apartment', 'Residential land / Plot', 'Residential land / Plot', '3 Bedroom House', 'Residential land / Plot', '3  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', '2  Apartment', '3  Apartment', '2  Apartment', '4 Bedroom House', '4 Bedroom House', '7 Bedroom House', '3 ', '4 ', '3 Bedroom House', 'Residential land / Plot', '2  Apartment', '1  Apartment', '1 Bedroom House', '2  Apartment', '3  Apartment', '6 Bedroom House', '3  Apartment', '3  Apartment', '2  Apartment', '1  Apartment', '3  Apartment', 'Residential land / Plot', '14 Bedroom House', '3 Bedroom House', '2  Apartment', '3  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', 'Residential land / Plot', '3  Apartment', 'Residential land / Plot', '4 Bedroom House', '4  Apartment', '3  Apartment', '4 Bedroom House', 'Residential land / Plot', '2 Bedroom House', '2  Apartment', '3  Apartment', 'Residential land / Plot', 'Residential land / Plot', '2 Bedroom House', 'Residential land / Plot', '2  Apartment', '3  Apartment', 'Residential land / Plot', '7 Bedroom House', '4 Bedroom House', '10 Bedroom House', '3  Apartment', '2 Bedroom House', '2  Apartment', '3 Bedroom House', '2  Apartment', '2  Apartment', '3  Apartment', '3  Apartment', '2  Apartment', 'Residential land / Plot', '3  Apartment', '3  Apartment', '3  Apartment', 'Residential land / Plot', '2  Apartment', 'Residential land / Plot', '2  Apartment', '3  Apartment', '4 Bedroom House', '2  Apartment', '2  Apartment', '2  Apartment', '9 ', '2  Apartment', '3 Bedroom House', '5 Bedroom House', '2 Bedroom House', 'Residential land / Plot', '2  Apartment', '2  Apartment', 'Residential land / Plot', '3  Apartment', '2  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', 'Residential land / Plot', 'Residential land / Plot', '3  Apartment', '2  Apartment', '2  Apartment', '3  Apartment', '2  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', '3  Apartment', '3  Apartment', '2 Bedroom House', '2 Bedroom House', '2  Apartment', '3 Bedroom House', '3 ', '2  Apartment', 'Residential land / Plot', '4 Bedroom House', '12 Bedroom House', '3  Apartment', '3  Apartment', '2  Apartment', '2  Apartment', '3  Apartment', '2  Apartment', 'Residential land / Plot', 'Residential land / Plot', '2  Apartment', '3  Apartment', '2  Apartment', 'Residential land / Plot', '5 Bedroom House', '3  Apartment', '3  Apartment', '14 Bedroom House', 'Residential land / Plot', '2  Apartment', 'Residential land / Plot', '3  Apartment', '4  Apartment', '3  Apartment', '11 Bedroom House', '3  Apartment', '3  Apartment', '2  Apartment', '3 Bedroom House', '4  Apartment', '2  Apartment', '3  Apartment', '3 Bedroom House', '9 Bedroom House', '3  Apartment', 'Residential land / Plot', 'Residential land / Plot', '3  Apartment']

In [15]:
pattern = "[0-9]+"

#list to store modified strings
modified_strings2 = []

for string in modified_strings1:
    modified_string = re.sub(pattern, "", string)
    modified_strings2.append(modified_string)

print(modified_strings2)

['Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', ' Bedroom House', ' Bedroom House', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', ' Bedroom House', '  Apartment', ' Bedroom House', ' Bedroom House', '  Apartment', ' Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', 'Residential land / Plot', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', ' Bedroom House', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', ' Bedroom House', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', 'Residential land / Plot', 'Residential land / Plot', ' Bedroom House', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', ' ', '  Apartment', '  Apartment', 'Residential land / Plot', ' Bedroom House', '  Apartment', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', ' Bedroom House', '  Apartment', ' Bedroom Farm house', ' Bedroom House', ' Bedroom House', ' Bedroom House', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', ' ', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' ', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Residential land / Plot', ' ', '  Apartment', ' Bedroom House', '  Apartment', ' ', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', ' ', '  Apartment', '  Apartment', ' ', ' Bedroom House', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', ' Bedroom House', ' ', ' ', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', ' Bedroom House', '  Apartment', '  Apartment', ' Bedroom House', 'Residential land / Plot', ' Bedroom House', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', ' Bedroom House', ' Bedroom House', ' Bedroom House', '  Apartment', ' Bedroom House', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', ' ', '  Apartment', ' Bedroom House', ' Bedroom House', ' Bedroom House', 'Residential land / Plot', '  Apartment', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', '  Apartment', ' Bedroom House', ' ', '  Apartment', 'Residential land / Plot', ' Bedroom House', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', 'Residential land / Plot', ' Bedroom House', '  Apartment', '  Apartment', ' Bedroom House', 'Residential land / Plot', '  Apartment', 'Residential land / Plot', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', '  Apartment', '  Apartment', '  Apartment', ' Bedroom House', ' Bedroom House', '  Apartment', 'Residential land / Plot', 'Residential land / Plot', '  Apartment']

In [16]:
#regular expression pattern to match and remove space before starting word
pattern = "^\s"

#list to store modified strings
land = []

for string in modified_strings2:
    modified_string = re.sub(pattern, "", string)
    land.append(modified_string)

print(land)

['Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', ' Apartment', 'Bedroom House', 'Bedroom House', ' Apartment', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', 'Bedroom House', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', '', ' Apartment', ' Apartment', 'Residential land / Plot', 'Bedroom House', ' Apartment', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', 'Bedroom House', ' Apartment', 'Bedroom Farm house', 'Bedroom House', 'Bedroom House', 'Bedroom House', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', '', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', '', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Residential land / Plot', '', ' Apartment', 'Bedroom House', ' Apartment', '', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', '', ' Apartment', ' Apartment', '', 'Bedroom House', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', '', '', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', 'Bedroom House', ' Apartment', ' Apartment', 'Bedroom House', 'Residential land / Plot', 'Bedroom House', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', 'Bedroom House', ' Apartment', 'Bedroom House', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', '', ' Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', ' Apartment', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', ' Apartment', 'Bedroom House', '', ' Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', 'Residential land / Plot', 'Bedroom House', ' Apartment', ' Apartment', 'Bedroom House', 'Residential land / Plot', ' Apartment', 'Residential land / Plot', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', ' Apartment', ' Apartment', ' Apartment', 'Bedroom House', 'Bedroom House', ' Apartment', 'Residential land / Plot', 'Residential land / Plot', ' Apartment']

In [17]:
#regular expression pattern to match and remove space before starting word
pattern = "^\s"

#list to store modified strings
type_of_land = []

for string in land:
    modified_string = re.sub(pattern, "", string)
    type_of_land.append(modified_string)

print(type_of_land)

['Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Apartment', 'Bedroom House', 'Bedroom House', 'Apartment', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Bedroom House', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', '', 'Apartment', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Bedroom Farm house', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', '', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', '', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Residential land / Plot', '', 'Apartment', 'Bedroom House', 'Apartment', '', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', '', 'Apartment', 'Apartment', '', 'Bedroom House', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', '', '', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Apartment', 'Bedroom House', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Apartment', 'Bedroom House', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', '', 'Apartment', 'Bedroom House', 'Bedroom House', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Apartment', 'Bedroom House', '', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Residential land / Plot', 'Bedroom House', 'Apartment', 'Apartment', 'Bedroom House', 'Residential land / Plot', 'Apartment', 'Residential land / Plot', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Apartment', 'Apartment', 'Apartment', 'Bedroom House', 'Bedroom House', 'Apartment', 'Residential land / Plot', 'Residential land / Plot', 'Apartment']

In [18]:
from collections import Counter

# Count the occurrences of each string in the list
counts = Counter(type_of_land)

# Get the most common string
most_common = counts.most_common(1)[0][0]

# Replace empty strings with the most common string
type_of_land = [most_common if x=='' else x for x in type_of_land]

In [19]:
type_of_land = list(map(lambda x: 'Bedroom House' if x=='House' else x, type_of_land))

In [20]:
pattern = '\d+'
bhk = list(map(lambda x: re.search(pattern, x).group() if re.search(pattern, x) else None, location))
pattern = re.compile('\d+')
bhk = list(map(lambda x: pattern.search(x).group() if pattern.search(x) else None, location))
bhk

[None,
 '1',
 '1',
 '1',
 '1',
 '2',
 '1',
 '3',
 '2',
 '2',
 '11',
 '6',
 '5',
 '5',
 '3',
 '3',
 '3',
 '2',
 '5',
 '3',
 '2',
 '12',
 '2',
 None,
 '3',
 '2',
 '6',
 '9',
 '3',
 '2',
 '2',
 '3',
 '3',
 '7',
 None,
 None,
 '2',
 '2',
 None,
 '3',
 '3',
 '3',
 None,
 '2',
 '3',
 '2',
 '3',
 None,
 '2',
 '2',
 '3',
 '6',
 None,
 '1',
 '3',
 '2',
 '2',
 '3',
 None,
 '2',
 None,
 '3',
 None,
 '3',
 '5',
 '2',
 '3',
 '2',
 None,
 '4',
 '3',
 '2',
 '4',
 '4',
 '2',
 '9',
 '11',
 '3',
 '3',
 '3',
 '2',
 '2',
 '5',
 '3',
 '2',
 '14',
 None,
 '6',
 '2',
 '3',
 None,
 None,
 '2',
 '3',
 '8',
 '3',
 '2',
 '6',
 '3',
 None,
 None,
 '3',
 '2',
 '6',
 '2',
 '3',
 '6',
 '2',
 '2',
 None,
 '4',
 '3',
 '11',
 None,
 '2',
 '2',
 '3',
 None,
 '7',
 '3',
 '3',
 '12',
 '3',
 '3',
 '3',
 '8',
 '3',
 '2',
 '2',
 '4',
 '2',
 '2',
 '12',
 '3',
 '2',
 None,
 None,
 '3',
 '2',
 '3',
 '2',
 '4',
 '3',
 '3',
 '2',
 '2',
 '2',
 '2',
 '4',
 '2',
 '3',
 None,
 None,
 None,
 '3',
 '3',
 '4',
 '2',
 '3',
 '3',
 '2',
 '13',
 '2',
 '2',
 '2',
 '2',
 '3',
 '12',
 '2',
 None,
 '3',
 '3',
 '9',
 '3',
 '2',
 '3',
 '4',
 '2',
 None,
 None,
 '3',
 None,
 '3',
 '3',
 None,
 '2',
 '2',
 '3',
 '2',
 '4',
 '4',
 '7',
 '3',
 '4',
 '3',
 None,
 '2',
 '1',
 '1',
 '2',
 '3',
 '6',
 '3',
 '3',
 '2',
 '1',
 '3',
 '6',
 '14',
 '3',
 '2',
 '3',
 '3',
 None,
 '2',
 None,
 '3',
 None,
 '4',
 '4',
 '3',
 '4',
 None,
 '2',
 '2',
 '3',
 None,
 '8',
 '2',
 None,
 '2',
 '3',
 None,
 '7',
 '4',
 '10',
 '3',
 '2',
 '2',
 '3',
 '2',
 '2',
 '3',
 '3',
 '2',
 None,
 '3',
 '3',
 '3',
 None,
 '2',
 None,
 '2',
 '3',
 '4',
 '2',
 '2',
 '2',
 '9',
 '2',
 '3',
 '5',
 '2',
 None,
 '2',
 '2',
 None,
 '3',
 '2',
 '3',
 '2',
 '2',
 None,
 None,
 '3',
 '2',
 '2',
 '3',
 '2',
 '3',
 '2',
 '2',
 '3',
 '3',
 '2',
 '2',
 '2',
 '3',
 '3',
 '2',
 None,
 '4',
 '12',
 '3',
 '3',
 '2',
 '2',
 '3',
 '2',
 None,
 None,
 '2',
 '3',
 '2',
 '6',
 '5',
 '3',
 '3',
 '14',
 None,
 '2',
 None,
 '3',
 '4',
 '3',
 '11',
 '3',
 '3',
 '2',
 '3',
 '4',
 '2',
 '3',
 '3',
 '9',
 '3',
 None,
 None,
 '3']

In [21]:
for i in range(len(bhk)):
    try:
        bhk[i] = int(bhk[i])
    except:
        pass
print(bhk)

[None, 1, 1, 1, 1, 2, 1, 3, 2, 2, 11, 6, 5, 5, 3, 3, 3, 2, 5, 3, 2, 12, 2, None, 3, 2, 6, 9, 3, 2, 2, 3, 3, 7, None, None, 2, 2, None, 3, 3, 3, None, 2, 3, 2, 3, None, 2, 2, 3, 6, None, 1, 3, 2, 2, 3, None, 2, None, 3, None, 3, 5, 2, 3, 2, None, 4, 3, 2, 4, 4, 2, 9, 11, 3, 3, 3, 2, 2, 5, 3, 2, 14, None, 6, 2, 3, None, None, 2, 3, 8, 3, 2, 6, 3, None, None, 3, 2, 6, 2, 3, 6, 2, 2, None, 4, 3, 11, None, 2, 2, 3, None, 7, 3, 3, 12, 3, 3, 3, 8, 3, 2, 2, 4, 2, 2, 12, 3, 2, None, None, 3, 2, 3, 2, 4, 3, 3, 2, 2, 2, 2, 4, 2, 3, None, None, None, 3, 3, 4, 2, 3, 3, 2, 13, 2, 2, 2, 2, 3, 12, 2, None, 3, 3, 9, 3, 2, 3, 4, 2, None, None, 3, None, 3, 3, None, 2, 2, 3, 2, 4, 4, 7, 3, 4, 3, None, 2, 1, 1, 2, 3, 6, 3, 3, 2, 1, 3, 6, 14, 3, 2, 3, 3, None, 2, None, 3, None, 4, 4, 3, 4, None, 2, 2, 3, None, 8, 2, None, 2, 3, None, 7, 4, 10, 3, 2, 2, 3, 2, 2, 3, 3, 2, None, 3, 3, 3, None, 2, None, 2, 3, 4, 2, 2, 2, 9, 2, 3, 5, 2, None, 2, 2, None, 3, 2, 3, 2, 2, None, None, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 3, 2, None, 4, 12, 3, 3, 2, 2, 3, 2, None, None, 2, 3, 2, 6, 5, 3, 3, 14, None, 2, None, 3, 4, 3, 11, 3, 3, 2, 3, 4, 2, 3, 3, 9, 3, None, None, 3]

In [22]:
bhk = [0 if i is None else i for i in bhk]
print(bhk)

[0, 1, 1, 1, 1, 2, 1, 3, 2, 2, 11, 6, 5, 5, 3, 3, 3, 2, 5, 3, 2, 12, 2, 0, 3, 2, 6, 9, 3, 2, 2, 3, 3, 7, 0, 0, 2, 2, 0, 3, 3, 3, 0, 2, 3, 2, 3, 0, 2, 2, 3, 6, 0, 1, 3, 2, 2, 3, 0, 2, 0, 3, 0, 3, 5, 2, 3, 2, 0, 4, 3, 2, 4, 4, 2, 9, 11, 3, 3, 3, 2, 2, 5, 3, 2, 14, 0, 6, 2, 3, 0, 0, 2, 3, 8, 3, 2, 6, 3, 0, 0, 3, 2, 6, 2, 3, 6, 2, 2, 0, 4, 3, 11, 0, 2, 2, 3, 0, 7, 3, 3, 12, 3, 3, 3, 8, 3, 2, 2, 4, 2, 2, 12, 3, 2, 0, 0, 3, 2, 3, 2, 4, 3, 3, 2, 2, 2, 2, 4, 2, 3, 0, 0, 0, 3, 3, 4, 2, 3, 3, 2, 13, 2, 2, 2, 2, 3, 12, 2, 0, 3, 3, 9, 3, 2, 3, 4, 2, 0, 0, 3, 0, 3, 3, 0, 2, 2, 3, 2, 4, 4, 7, 3, 4, 3, 0, 2, 1, 1, 2, 3, 6, 3, 3, 2, 1, 3, 6, 14, 3, 2, 3, 3, 0, 2, 0, 3, 0, 4, 4, 3, 4, 0, 2, 2, 3, 0, 8, 2, 0, 2, 3, 0, 7, 4, 10, 3, 2, 2, 3, 2, 2, 3, 3, 2, 0, 3, 3, 3, 0, 2, 0, 2, 3, 4, 2, 2, 2, 9, 2, 3, 5, 2, 0, 2, 2, 0, 3, 2, 3, 2, 2, 0, 0, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 3, 2, 0, 4, 12, 3, 3, 2, 2, 3, 2, 0, 0, 2, 3, 2, 6, 5, 3, 3, 14, 0, 2, 0, 3, 4, 3, 11, 3, 3, 2, 3, 4, 2, 3, 3, 9, 3, 0, 0, 3]

In [23]:
len(bhk)

329

# price per sqft

In [24]:
price = df['price_per_sqft'].tolist()

print(price)

['₹ 1,100/sq.ft.', '₹ 10,925/sq.ft.', '₹ 10,845/sq.ft.', '₹ 10,925/sq.ft.', '₹ 10,925/sq.ft.', '₹ 13,238/sq.ft.', '₹ 13,237/sq.ft.', '₹ 9,868/sq.ft.', '₹ 6,568/sq.ft.', '₹ 5,579/sq.ft.', '₹ 8,750/sq.ft.', '₹ 11,666/sq.ft.', '₹ 4,516/sq.ft.', '₹ 3,429/sq.ft.', '₹ 7,049/sq.ft.', '₹ 5,873/sq.ft.', '₹ 3,600/sq.ft.', '₹ 5,391/sq.ft.', '₹ 29,166/sq.ft.', '₹ 11,167/sq.ft.', '₹ 6,000/sq.ft.', '₹ 20,916/sq.ft.', '₹ 9,440/sq.ft.', '₹ 7,020/sq.ft.', '₹ 7,804/sq.ft.', '₹ 6,732/sq.ft.', '₹ 6,562/sq.ft.', '₹ 5,500/sq.ft.', '₹ 14,634/sq.ft.', '₹ 7,774/sq.ft.', '₹ 6,481/sq.ft.', '₹ 18,919/sq.ft.', '₹ 15,551/sq.ft.', '₹ 6,470/sq.ft.', '₹ 4,500/sq.ft.', '₹ 6,500/sq.ft.', '₹ 6,639/sq.ft.', '₹ 5,846/sq.ft.', '₹ 7,778/sq.ft.', '₹ 7,067/sq.ft.', '₹ 7,200/sq.ft.', '₹ 8,371/sq.ft.', '₹ 4,361/sq.ft.', '₹ 6,000/sq.ft.', '₹ 6,856/sq.ft.', '₹ 6,008/sq.ft.', '₹ 4,718/sq.ft.', '₹ 3,000/sq.ft.', '₹ 4,913/sq.ft.', '₹ 6,363/sq.ft.', '₹ 16,250/sq.ft.', '₹ 15,416/sq.ft.', '₹ 3,000/sq.ft.', '₹ 8,333/sq.ft.', '₹ 5,142/sq.ft.', '₹ 5,223/sq.ft.', '₹ 7,299/sq.ft.', '₹ 5,990/sq.ft.', '₹ 5,500/sq.ft.', '₹ 7,562/sq.ft.', '₹ 2,850/sq.ft.', '₹ 5,278/sq.ft.', '₹ 6,000/sq.ft.', '₹ 11,462/sq.ft.', '₹ 16,666/sq.ft.', '₹ 7,101/sq.ft.', '₹ 8,500/sq.ft.', '₹ 4,887/sq.ft.', '₹ 1,700/sq.ft.', '₹ 22,222/sq.ft.', '₹ 9,281/sq.ft.', '₹ 6,225/sq.ft.', '₹ 18,333/sq.ft.', '₹ 5,220/sq.ft.', '₹ 6,519/sq.ft.', '₹ 4,326/sq.ft.', '₹ 15,000/sq.ft.', '₹ 6,005/sq.ft.', '₹ 5,375/sq.ft.', '₹ 5,544/sq.ft.', '₹ 6,526/sq.ft.', '₹ 4,574/sq.ft.', '₹ 24,750/sq.ft.', '₹ 5,866/sq.ft.', '₹ 8,814/sq.ft.', '₹ 17,786/sq.ft.', '₹ 9,500/sq.ft.', '₹ 8,500/sq.ft.', '₹ 6,308/sq.ft.', '₹ 11,703/sq.ft.', '₹ 4,200/sq.ft.', '₹ 2,989/sq.ft.', '₹ 5,482/sq.ft.', '₹ 7,500/sq.ft.', '₹ 13,333/sq.ft.', '₹ 5,420/sq.ft.', '₹ 7,076/sq.ft.', '₹ 15,833/sq.ft.', '₹ 9,135/sq.ft.', '₹ 6,833/sq.ft.', '₹ 1,500/sq.ft.', '₹ 10,000/sq.ft.', '₹ 4,891/sq.ft.', '₹ 7,250/sq.ft.', '₹ 5,018/sq.ft.', '₹ 3,441/sq.ft.', '₹ 6,400/sq.ft.', '₹ 6,044/sq.ft.', '₹ 11,673/sq.ft.', '₹ 6,000/sq.ft.', '₹ 12,000/sq.ft.', '₹ 4,690/sq.ft.', '₹ 18,518/sq.ft.', '₹ 8,000/sq.ft.', '₹ 9,433/sq.ft.', '₹ 5,344/sq.ft.', '₹ 8,000/sq.ft.', '₹ 2,334/sq.ft.', '₹ 35,185/sq.ft.', '₹ 8,484/sq.ft.', '₹ 1,837/sq.ft.', '₹ 8,720/sq.ft.', '₹ 10,346/sq.ft.', '₹ 6,304/sq.ft.', '₹ 5,640/sq.ft.', '₹ 9,444/sq.ft.', '₹ 4,648/sq.ft.', '₹ 4,914/sq.ft.', '₹ 7,462/sq.ft.', '₹ 10,000/sq.ft.', '₹ 6,781/sq.ft.', '₹ 5,272/sq.ft.', '₹ 10,000/sq.ft.', '₹ 5,500/sq.ft.', '₹ 8,820/sq.ft.', '₹ 12,000/sq.ft.', '₹ 4,000/sq.ft.', '₹ 6,000/sq.ft.', '₹ 6,582/sq.ft.', '₹ 5,972/sq.ft.', '₹ 7,826/sq.ft.', '₹ 27,666/sq.ft.', '₹ 8,176/sq.ft.', '₹ 11,182/sq.ft.', '₹ 5,344/sq.ft.', '₹ 4,824/sq.ft.', '₹ 4,612/sq.ft.', '₹ 5,511/sq.ft.', '₹ 8,555/sq.ft.', '₹ 11,666/sq.ft.', '₹ 7,575/sq.ft.', '₹ 2,500/sq.ft.', '₹ 1,750/sq.ft.', '₹ 7,000/sq.ft.', '₹ 11,063/sq.ft.', '₹ 4,469/sq.ft.', '₹ 8,750/sq.ft.', '₹ 10,900/sq.ft.', '₹ 6,500/sq.ft.', '₹ 6,516/sq.ft.', '₹ 5,914/sq.ft.', '₹ 20,000/sq.ft.', '₹ 12,500/sq.ft.', '₹ 4,661/sq.ft.', '₹ 3,823/sq.ft.', '₹ 5,093/sq.ft.', '₹ 3,661/sq.ft.', '₹ 14,423/sq.ft.', '₹ 2,890/sq.ft.', '₹ 2,500/sq.ft.', '₹ 7,579/sq.ft.', '₹ 6,803/sq.ft.', '₹ 6,888/sq.ft.', '₹ 3,618/sq.ft.', '₹ 4,465/sq.ft.', '₹ 17,187/sq.ft.', '₹ 7,798/sq.ft.', '₹ 6,256/sq.ft.', '₹ 4,500/sq.ft.', '₹ 6,530/sq.ft.', '₹ 7,500/sq.ft.', '₹ 6,875/sq.ft.', '₹ 3,409/sq.ft.', '₹ 6,386/sq.ft.', '₹ 4,554/sq.ft.', '₹ 5,726/sq.ft.', '₹ 5,829/sq.ft.', '₹ 4,850/sq.ft.', '₹ 5,461/sq.ft.', '₹ 20,833/sq.ft.', '₹ 23,809/sq.ft.', '₹ 20,754/sq.ft.', '₹ 5,867/sq.ft.', '₹ 5,111/sq.ft.', '₹ 25,000/sq.ft.', '₹ 6,916/sq.ft.', '₹ 7,107/sq.ft.', '₹ 6,153/sq.ft.', '₹ 4,550/sq.ft.', '₹ 9,255/sq.ft.', '₹ 6,028/sq.ft.', '₹ 27,160/sq.ft.', '₹ 4,950/sq.ft.', '₹ 9,118/sq.ft.', '₹ 9,500/sq.ft.', '₹ 7,200/sq.ft.', '₹ 6,352/sq.ft.', '₹ 6,250/sq.ft.', '₹ 12,406/sq.ft.', '₹ 4,688/sq.ft.', '₹ 7,364/sq.ft.', '₹ 4,333/sq.ft.', '₹ 7,272/sq.ft.', '₹ 19,583/sq.ft.', '₹ 6,720/sq.ft.', '₹ 5,279/sq.ft.', '₹ 3,201/sq.ft.', '₹ 4,750/sq.ft.', '₹ 13,750/sq.ft.', '₹ 9,806/sq.ft.', '₹ 8,059/sq.ft.', '₹ 7,045/sq.ft.', '₹ 10,000/sq.ft.', '₹ 6,500/sq.ft.', '₹ 8,292/sq.ft.', '₹ 4,812/sq.ft.', '₹ 1,098/sq.ft.', '₹ 9,562/sq.ft.', '₹ 4,366/sq.ft.', '₹ 2,500/sq.ft.', '₹ 6,583/sq.ft.', '₹ 5,868/sq.ft.', '₹ 500/sq.ft.', '₹ 14,327/sq.ft.', '₹ 11,300/sq.ft.', '₹ 7,000/sq.ft.', '₹ 8,074/sq.ft.', '₹ 13,181/sq.ft.', '₹ 5,794/sq.ft.', '₹ 39,583/sq.ft.', '₹ 5,897/sq.ft.', '₹ 3,839/sq.ft.', '₹ 5,592/sq.ft.', '₹ 15,500/sq.ft.', '₹ 4,360/sq.ft.', '₹ 7,166/sq.ft.', '₹ 6,029/sq.ft.', '₹ 5,209/sq.ft.', '₹ 5,576/sq.ft.', '₹ 1,875/sq.ft.', '₹ 5,962/sq.ft.', '₹ 3,121/sq.ft.', '₹ 5,416/sq.ft.', '₹ 9,917/sq.ft.', '₹ 5,818/sq.ft.', '₹ 5,293/sq.ft.', '₹ 4,405/sq.ft.', '₹ 6,260/sq.ft.', '₹ 5,434/sq.ft.', '₹ 5,172/sq.ft.', '₹ 5,439/sq.ft.', '₹ 24,000/sq.ft.', '₹ 9,166/sq.ft.', '₹ 3,500/sq.ft.', '₹ 5,000/sq.ft.', '₹ 5,845/sq.ft.', '₹ 4,200/sq.ft.', '₹ 3,956/sq.ft.', '₹ 6,250/sq.ft.', '₹ 4,177/sq.ft.', '₹ 5,528/sq.ft.', '₹ 6,039/sq.ft.', '₹ 8,400/sq.ft.', '₹ 5,151/sq.ft.', '₹ 8,000/sq.ft.', '₹ 3,666/sq.ft.', '₹ 6,715/sq.ft.', '₹ 6,740/sq.ft.', '₹ 4,500/sq.ft.', '₹ 5,033/sq.ft.', '₹ 7,718/sq.ft.', '₹ 3,216/sq.ft.', '₹ 4,546/sq.ft.', '₹ 5,040/sq.ft.', '₹ 7,238/sq.ft.', '₹ 7,086/sq.ft.', '₹ 6,445/sq.ft.', '₹ 4,676/sq.ft.', '₹ 5,652/sq.ft.', '₹ 10,333/sq.ft.', '₹ 3,000/sq.ft.', '₹ 12,915/sq.ft.', '₹ 9,803/sq.ft.', '₹ 6,879/sq.ft.', '₹ 5,077/sq.ft.', '₹ 3,750/sq.ft.', '₹ 5,504/sq.ft.', '₹ 5,639/sq.ft.', '₹ 8,683/sq.ft.', '₹ 8,333/sq.ft.', '₹ 5,757/sq.ft.', '₹ 6,034/sq.ft.', '₹ 5,151/sq.ft.', '₹ 8,120/sq.ft.', '₹ 11,111/sq.ft.', '₹ 28,157/sq.ft.', '₹ 6,591/sq.ft.', '₹ 4,114/sq.ft.', '₹ 14,583/sq.ft.', '₹ 500/sq.ft.', '₹ 7,761/sq.ft.', '₹ 6,000/sq.ft.', '₹ 7,380/sq.ft.', '₹ 8,125/sq.ft.', '₹ 7,053/sq.ft.', '₹ 25,000/sq.ft.', '₹ 6,179/sq.ft.', '₹ 7,938/sq.ft.', '₹ 4,602/sq.ft.', '₹ 8,571/sq.ft.', '₹ 11,787/sq.ft.', '₹ 4,756/sq.ft.', '₹ 9,730/sq.ft.', '₹ 20,000/sq.ft.', '₹ 3,541/sq.ft.', '₹ 4,898/sq.ft.', '₹ 45,238/sq.ft.', '₹ 11,650/sq.ft.', '₹ 4,428/sq.ft.']

In [25]:
characters_to_remove = ["₹ ","/sq.ft.",","]

#regular expression pattern to match and remove special characters and characters
pattern = "[{}]".format("".join(characters_to_remove))

#list to store modified strings
Price_per_sqft = []

for string in price:
    modified_string = re.sub(pattern, "", string)
    Price_per_sqft.append(modified_string)

print(Price_per_sqft)

['1100', '10925', '10845', '10925', '10925', '13238', '13237', '9868', '6568', '5579', '8750', '11666', '4516', '3429', '7049', '5873', '3600', '5391', '29166', '11167', '6000', '20916', '9440', '7020', '7804', '6732', '6562', '5500', '14634', '7774', '6481', '18919', '15551', '6470', '4500', '6500', '6639', '5846', '7778', '7067', '7200', '8371', '4361', '6000', '6856', '6008', '4718', '3000', '4913', '6363', '16250', '15416', '3000', '8333', '5142', '5223', '7299', '5990', '5500', '7562', '2850', '5278', '6000', '11462', '16666', '7101', '8500', '4887', '1700', '22222', '9281', '6225', '18333', '5220', '6519', '4326', '15000', '6005', '5375', '5544', '6526', '4574', '24750', '5866', '8814', '17786', '9500', '8500', '6308', '11703', '4200', '2989', '5482', '7500', '13333', '5420', '7076', '15833', '9135', '6833', '1500', '10000', '4891', '7250', '5018', '3441', '6400', '6044', '11673', '6000', '12000', '4690', '18518', '8000', '9433', '5344', '8000', '2334', '35185', '8484', '1837', '8720', '10346', '6304', '5640', '9444', '4648', '4914', '7462', '10000', '6781', '5272', '10000', '5500', '8820', '12000', '4000', '6000', '6582', '5972', '7826', '27666', '8176', '11182', '5344', '4824', '4612', '5511', '8555', '11666', '7575', '2500', '1750', '7000', '11063', '4469', '8750', '10900', '6500', '6516', '5914', '20000', '12500', '4661', '3823', '5093', '3661', '14423', '2890', '2500', '7579', '6803', '6888', '3618', '4465', '17187', '7798', '6256', '4500', '6530', '7500', '6875', '3409', '6386', '4554', '5726', '5829', '4850', '5461', '20833', '23809', '20754', '5867', '5111', '25000', '6916', '7107', '6153', '4550', '9255', '6028', '27160', '4950', '9118', '9500', '7200', '6352', '6250', '12406', '4688', '7364', '4333', '7272', '19583', '6720', '5279', '3201', '4750', '13750', '9806', '8059', '7045', '10000', '6500', '8292', '4812', '1098', '9562', '4366', '2500', '6583', '5868', '500', '14327', '11300', '7000', '8074', '13181', '5794', '39583', '5897', '3839', '5592', '15500', '4360', '7166', '6029', '5209', '5576', '1875', '5962', '3121', '5416', '9917', '5818', '5293', '4405', '6260', '5434', '5172', '5439', '24000', '9166', '3500', '5000', '5845', '4200', '3956', '6250', '4177', '5528', '6039', '8400', '5151', '8000', '3666', '6715', '6740', '4500', '5033', '7718', '3216', '4546', '5040', '7238', '7086', '6445', '4676', '5652', '10333', '3000', '12915', '9803', '6879', '5077', '3750', '5504', '5639', '8683', '8333', '5757', '6034', '5151', '8120', '11111', '28157', '6591', '4114', '14583', '500', '7761', '6000', '7380', '8125', '7053', '25000', '6179', '7938', '4602', '8571', '11787', '4756', '9730', '20000', '3541', '4898', '45238', '11650', '4428']

In [26]:
Price_per_SqFt = [int(x) for x in Price_per_sqft]

print(Price_per_SqFt)

[1100, 10925, 10845, 10925, 10925, 13238, 13237, 9868, 6568, 5579, 8750, 11666, 4516, 3429, 7049, 5873, 3600, 5391, 29166, 11167, 6000, 20916, 9440, 7020, 7804, 6732, 6562, 5500, 14634, 7774, 6481, 18919, 15551, 6470, 4500, 6500, 6639, 5846, 7778, 7067, 7200, 8371, 4361, 6000, 6856, 6008, 4718, 3000, 4913, 6363, 16250, 15416, 3000, 8333, 5142, 5223, 7299, 5990, 5500, 7562, 2850, 5278, 6000, 11462, 16666, 7101, 8500, 4887, 1700, 22222, 9281, 6225, 18333, 5220, 6519, 4326, 15000, 6005, 5375, 5544, 6526, 4574, 24750, 5866, 8814, 17786, 9500, 8500, 6308, 11703, 4200, 2989, 5482, 7500, 13333, 5420, 7076, 15833, 9135, 6833, 1500, 10000, 4891, 7250, 5018, 3441, 6400, 6044, 11673, 6000, 12000, 4690, 18518, 8000, 9433, 5344, 8000, 2334, 35185, 8484, 1837, 8720, 10346, 6304, 5640, 9444, 4648, 4914, 7462, 10000, 6781, 5272, 10000, 5500, 8820, 12000, 4000, 6000, 6582, 5972, 7826, 27666, 8176, 11182, 5344, 4824, 4612, 5511, 8555, 11666, 7575, 2500, 1750, 7000, 11063, 4469, 8750, 10900, 6500, 6516, 5914, 20000, 12500, 4661, 3823, 5093, 3661, 14423, 2890, 2500, 7579, 6803, 6888, 3618, 4465, 17187, 7798, 6256, 4500, 6530, 7500, 6875, 3409, 6386, 4554, 5726, 5829, 4850, 5461, 20833, 23809, 20754, 5867, 5111, 25000, 6916, 7107, 6153, 4550, 9255, 6028, 27160, 4950, 9118, 9500, 7200, 6352, 6250, 12406, 4688, 7364, 4333, 7272, 19583, 6720, 5279, 3201, 4750, 13750, 9806, 8059, 7045, 10000, 6500, 8292, 4812, 1098, 9562, 4366, 2500, 6583, 5868, 500, 14327, 11300, 7000, 8074, 13181, 5794, 39583, 5897, 3839, 5592, 15500, 4360, 7166, 6029, 5209, 5576, 1875, 5962, 3121, 5416, 9917, 5818, 5293, 4405, 6260, 5434, 5172, 5439, 24000, 9166, 3500, 5000, 5845, 4200, 3956, 6250, 4177, 5528, 6039, 8400, 5151, 8000, 3666, 6715, 6740, 4500, 5033, 7718, 3216, 4546, 5040, 7238, 7086, 6445, 4676, 5652, 10333, 3000, 12915, 9803, 6879, 5077, 3750, 5504, 5639, 8683, 8333, 5757, 6034, 5151, 8120, 11111, 28157, 6591, 4114, 14583, 500, 7761, 6000, 7380, 8125, 7053, 25000, 6179, 7938, 4602, 8571, 11787, 4756, 9730, 20000, 3541, 4898, 45238, 11650, 4428]

# total sqft

In [27]:
sqft = df['total_sqft'].tolist()

print(sqft)

['1,200-12,000 sq.ft. (111-1115 sq.m.) Plot Area', '412-461 sq.ft. (38-43 sq.m.) Carpet Area', '461 sq.ft. (43 sq.m.) Carpet Area', '412-461 sq.ft. (38-43 sq.m.) Carpet Area', '412-461 sq.ft. (38-43 sq.m.) Carpet Area', '627 sq.ft. (58 sq.m.) Carpet Area', '412-461 sq.ft. (38-43 sq.m.) Carpet Area', '2,280 sq.ft. (212 sq.m.) Built-up Area', '1,065 sq.ft. (99 sq.m.) Built-up Area', '1,165 sq.ft. (108 sq.m.) Carpet Area', '1,973 sq.ft. (183 sq.m.) Plot Area', '3,000 sq.ft. (279 sq.m.) Plot Area', '3,100 sq.ft. (288 sq.m.) Plot Area', '3,500 sq.ft. (325 sq.m.) Built-up Area', '922 sq.ft. (86 sq.m.) Super built-up Area', '1,345 sq.ft. (125 sq.m.) Built-up Area', '1,468 sq.ft. (136 sq.m.) Built-up Area', '1,150 sq.ft. (107 sq.m.) Carpet Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,373 sq.ft. (128 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,483 sq.ft. (138 sq.m.) Plot Area', '3,675 sq.ft. (341 sq.m.) Plot Area', '2,050 sq.ft. (190 sq.m.) Super built-up Area', '1,131 sq.ft. (105 sq.m.) Super built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '4,000 sq.ft. (372 sq.m.) Built-up Area', '2,665 sq.ft. (248 sq.m.) Plot Area', '1,222 sq.ft. (114 sq.m.) Built-up Area', '2,700 sq.ft. (251 sq.m.) Plot Area', '2,378 sq.ft. (221 sq.m.) Built-up Area', '1,765 sq.ft. (164 sq.m.) Super built-up Area', '1,250 sq.ft. (116 sq.m.) Plot Area', '7,200 sq.ft. (669 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,205 sq.ft. (112 sq.m.) Super built-up Area', '1,300 sq.ft. (121 sq.m.) Super built-up Area', '1,800 sq.ft. (167 sq.m.) Plot Area', '1,429 sq.ft. (133 sq.m.) Super built-up Area', '1,704 sq.ft. (158 sq.m.) Carpet Area', '1,314 sq.ft. (122 sq.m.) Super built-up Area', '2,293 sq.ft. (213 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Built-up Area', '1,612 sq.ft. (150 sq.m.) Built-up Area', '1,165 sq.ft. (108 sq.m.) Built-up Area', '1,441 sq.ft. (134 sq.m.) Super built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,160 sq.ft. (108 sq.m.) Super built-up Area', '1,100 sq.ft. (102 sq.m.) Super built-up Area', '800 sq.ft. (74 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '3,000 sq.ft. (279 sq.m.) Plot Area', '1,800 sq.ft. (167 sq.m.) Plot Area', '1,750 sq.ft. (163 sq.m.) Super built-up Area', '1,340 sq.ft. (124 sq.m.) Super built-up Area', '1,233 sq.ft. (115 sq.m.) Built-up Area', '1,252 sq.ft. (116 sq.m.) Built-up Area', '3,569 sq.ft. (332 sq.m.) Plot Area', '1,005 sq.ft. (93 sq.m.) Carpet Area', '1,485 sq.ft. (138 sq.m.) Plot Area', '1,705 sq.ft. (158 sq.m.) Built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '2,505 sq.ft. (233 sq.m.) Plot Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,380 sq.ft. (128 sq.m.) Super built-up Area', '2,590 sq.ft. (241 sq.m.) Carpet Area', '1,156 sq.ft. (107 sq.m.) Carpet Area', '4,000 sq.ft. (372 sq.m.) Plot Area', '3,600 sq.ft. (334 sq.m.) Super built-up Area', '1,530 sq.ft. (142 sq.m.) Plot Area', '1,285 sq.ft. (119 sq.m.) Super built-up Area', '600 sq.ft. (56 sq.m.) Plot Area', '1,724 sq.ft. (160 sq.m.) Built-up Area', '997 sq.ft. (93 sq.m.) Super built-up Area', '5,200 sq.ft. (483 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,648 sq.ft. (153 sq.m.) Super built-up Area', '1,600 sq.ft. (149 sq.m.) Super built-up Area', '1,569 sq.ft. (146 sq.m.) Super built-up Area', '950 sq.ft. (88 sq.m.) Super built-up Area', '940 sq.ft. (87 sq.m.) Built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,500 sq.ft. (139 sq.m.) Super built-up Area', '1,021 sq.ft. (95 sq.m.) Carpet Area', '1,265 sq.ft. (118 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,395 sq.ft. (130 sq.m.) Super built-up Area', '2,119 sq.ft. (197 sq.m.) Super built-up Area', '1,800 sq.ft. (167 sq.m.) Plot Area', '7,025 sq.ft. (653 sq.m.) Plot Area', '1,368 sq.ft. (127 sq.m.) Carpet Area', '1,600 sq.ft. (149 sq.m.) Carpet Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,725 sq.ft. (160 sq.m.) Built-up Area', '1,074 sq.ft. (100 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '2,627 sq.ft. (244 sq.m.) Built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '920 sq.ft. (85 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,375 sq.ft. (128 sq.m.) Carpet Area', '1,075 sq.ft. (100 sq.m.) Built-up Area', '5,000 sq.ft. (465 sq.m.) Super built-up Area', '1,307 sq.ft. (121 sq.m.) Built-up Area', '1,285 sq.ft. (119 sq.m.) Super built-up Area', '1,300 sq.ft. (121 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,450 sq.ft. (135 sq.m.) Super built-up Area', '1,350 sq.ft. (125 sq.m.) Plot Area', '2,200 sq.ft. (204 sq.m.) Plot Area', '1,060 sq.ft. (98 sq.m.) Carpet Area', '1,235 sq.ft. (115 sq.m.) Super built-up Area', '2,075 sq.ft. (193 sq.m.) Super built-up Area', '1,199 sq.ft. (111 sq.m.) Plot Area', '5,400 sq.ft. (502 sq.m.) Plot Area', '1,650 sq.ft. (153 sq.m.) Carpet Area', '65,340 sq.ft. (6070 sq.m.) Plot Area', '1,360 sq.ft. (126 sq.m.) Plot Area', '2,600 sq.ft. (242 sq.m.) Built-up Area', '2,300 sq.ft. (214 sq.m.) Plot Area', '1,241 sq.ft. (115 sq.m.) Super built-up Area', '1,800 sq.ft. (167 sq.m.) Plot Area', '1,700 sq.ft. (158 sq.m.) Super built-up Area', '814 sq.ft. (76 sq.m.) Super built-up Area', '1,340 sq.ft. (124 sq.m.) Built-up Area', '2,600 sq.ft. (242 sq.m.) Built-up Area', '1,100 sq.ft. (102 sq.m.) Built-up Area', '1,119 sq.ft. (104 sq.m.) Super built-up Area', '3,000 sq.ft. (279 sq.m.) Plot Area', '1,525 sq.ft. (142 sq.m.) Super built-up Area', '907 sq.ft. (84 sq.m.) Built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '2,000 sq.ft. (186 sq.m.) Plot Area', '1,575 sq.ft. (146 sq.m.) Built-up Area', '1,261 sq.ft. (117 sq.m.) Carpet Area', '1,239 sq.ft. (115 sq.m.) Super built-up Area', '1,150 sq.ft. (107 sq.m.) Built-up Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,590 sq.ft. (148 sq.m.) Super built-up Area', '2,012 sq.ft. (187 sq.m.) Carpet Area', '1,160 sq.ft. (108 sq.m.) Super built-up Area', '995 sq.ft. (92 sq.m.) Carpet Area', '1,084 sq.ft. (101 sq.m.) Super built-up Area', '1,270 sq.ft. (118 sq.m.) Super built-up Area', '4,500 sq.ft. (418 sq.m.) Carpet Area', '1,485 sq.ft. (138 sq.m.) Super built-up Area', '1,650 sq.ft. (153 sq.m.) Built-up Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '3,293 sq.ft. (306 sq.m.) Plot Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '2,350 sq.ft. (218 sq.m.) Super built-up Area', '1,320 sq.ft. (123 sq.m.) Built-up Area', '2,000 sq.ft. (186 sq.m.) Built-up Area', '1,000 sq.ft. (93 sq.m.) Carpet Area', '2,000 sq.ft. (186 sq.m.) Super built-up Area', '1,335 sq.ft. (124 sq.m.) Built-up Area', '1,082 sq.ft. (101 sq.m.) Carpet Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,566 sq.ft. (145 sq.m.) Super built-up Area', '1,125 sq.ft. (105 sq.m.) Super built-up Area', '746 sq.ft. (69 sq.m.) Built-up Area', '1,475 sq.ft. (137 sq.m.) Built-up Area', '2,080 sq.ft. (193 sq.m.) Plot Area', '1,038 sq.ft. (96 sq.m.) Super built-up Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '2,045 sq.ft. (190 sq.m.) Super built-up Area', '1,470 sq.ft. (137 sq.m.) Super built-up Area', '2,250 sq.ft. (209 sq.m.) Built-up Area', '1,520 sq.ft. (141 sq.m.) Super built-up Area', '1,075 sq.ft. (100 sq.m.) Carpet Area', '1,600 sq.ft. (149 sq.m.) Carpet Area', '2,180 sq.ft. (203 sq.m.) Plot Area', '959 sq.ft. (89 sq.m.) Super built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '735 sq.ft. (68 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,525 sq.ft. (142 sq.m.) Super built-up Area', '1,879 sq.ft. (175 sq.m.) Built-up Area', '1,976 sq.ft. (184 sq.m.) Plot Area', '1,135 sq.ft. (105 sq.m.) Built-up Area', '1,115 sq.ft. (104 sq.m.) Super built-up Area', '1,340 sq.ft. (124 sq.m.) Carpet Area', '1,245 sq.ft. (116 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,260 sq.ft. (117 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,619 sq.ft. (150 sq.m.) Carpet Area', '4,500 sq.ft. (418 sq.m.) Built-up Area', '1,600 sq.ft. (149 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,196 sq.ft. (111 sq.m.) Super built-up Area', '780 sq.ft. (72 sq.m.) Carpet Area', '1,876 sq.ft. (174 sq.m.) Plot Area', '940 sq.ft. (87 sq.m.) Super built-up Area', '1,410 sq.ft. (131 sq.m.) Carpet Area', '1,215 sq.ft. (113 sq.m.) Plot Area', '1,515 sq.ft. (141 sq.m.) Super built-up Area', '1,645 sq.ft. (153 sq.m.) Super built-up Area', '1,014 sq.ft. (94 sq.m.) Super built-up Area', '500 sq.ft. (46 sq.m.) Carpet Area', '1,338 sq.ft. (124 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '2,660 sq.ft. (247 sq.m.) Plot Area', '2,325 sq.ft. (216 sq.m.) Plot Area', '1,290 sq.ft. (120 sq.m.) Super built-up Area', '1,500 sq.ft. (139 sq.m.) Carpet Area', '1,630 sq.ft. (151 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,265 sq.ft. (118 sq.m.) Super built-up Area', '1,326 sq.ft. (123 sq.m.) Plot Area', '1,187 sq.ft. (110 sq.m.) Carpet Area', '2,000 sq.ft. (186 sq.m.) Plot Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '2,427 sq.ft. (225 sq.m.) Super built-up Area', '1,675 sq.ft. (156 sq.m.) Super built-up Area', '4,400 sq.ft. (409 sq.m.) Built-up Area', '2,100 sq.ft. (195 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,025 sq.ft. (95 sq.m.) Built-up Area', '1,496 sq.ft. (139 sq.m.) Super built-up Area', '5,500 sq.ft. (511 sq.m.) Plot Area', '1,600 sq.ft. (149 sq.m.) Plot Area', '916 sq.ft. (85 sq.m.) Plot Area', '3,000 sq.ft. (279 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Built-up Area', '1,278 sq.ft. (119 sq.m.) Super built-up Area', '40,000 sq.ft. (3716 sq.m.) Plot Area', '1,382 sq.ft. (128 sq.m.) Plot Area', '2,100 sq.ft. (195 sq.m.) Plot Area', '5,000 sq.ft. (465 sq.m.) Built-up Area', '1,610 sq.ft. (150 sq.m.) Super built-up Area', '1,050 sq.ft. (98 sq.m.) Plot Area', '1,070 sq.ft. (99 sq.m.) Super built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,187 sq.ft. (110 sq.m.) Super built-up Area', '1,172 sq.ft. (109 sq.m.) Carpet Area', '1,520 sq.ft. (141 sq.m.) Carpet Area', '1,435 sq.ft. (133 sq.m.) Super built-up Area', '1,330 sq.ft. (124 sq.m.) Super built-up Area', '4,800 sq.ft. (446 sq.m.) Plot Area', '1,360 sq.ft. (126 sq.m.) Super built-up Area', '1,670 sq.ft. (155 sq.m.) Super built-up Area', '1,345 sq.ft. (125 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,258 sq.ft. (117 sq.m.) Super built-up Area', '2,915 sq.ft. (271 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Carpet Area', '1,815 sq.ft. (169 sq.m.) Carpet Area', '2,200 sq.ft. (204 sq.m.) Plot Area', '1,228 sq.ft. (114 sq.m.) Super built-up Area', '1,135 sq.ft. (105 sq.m.) Carpet Area', '1,150 sq.ft. (107 sq.m.) Carpet Area', '4,600 sq.ft. (427 sq.m.) Super built-up Area', '928 sq.ft. (86 sq.m.) Carpet Area', '1,140 sq.ft. (106 sq.m.) Built-up Area', '1,000 sq.ft. (93 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,000 sq.ft. (93 sq.m.) Carpet Area', '1,283 sq.ft. (119 sq.m.) Super built-up Area', '10,800 sq.ft. (1003 sq.m.) Plot Area', '1,390 sq.ft. (129 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Super built-up Area', '1,197 sq.ft. (111 sq.m.) Carpet Area', '814 sq.ft. (76 sq.m.) Carpet Area', '1,010 sq.ft. (94 sq.m.) Built-up Area', '2,400 sq.ft. (223 sq.m.) Plot Area', '1,747 sq.ft. (162 sq.m.) Plot Area', '1,400 sq.ft. (130 sq.m.) Super built-up Area', '900 sq.ft. (84 sq.m.) Super built-up Area', '1,260 sq.ft. (117 sq.m.) Super built-up Area', '1,558 sq.ft. (145 sq.m.) Super built-up Area', '1,000 sq.ft. (93 sq.m.) Built-up Area', '1,570 sq.ft. (146 sq.m.) Super built-up Area', '1,166 sq.ft. (108 sq.m.) Built-up Area', '1,057 sq.ft. (98 sq.m.) Super built-up Area', '1,540 sq.ft. (143 sq.m.) Built-up Area', '1,488 sq.ft. (138 sq.m.) Super built-up Area', '1,004 sq.ft. (93 sq.m.) Plot Area', '1,270 sq.ft. (118 sq.m.) Plot Area', '1,055 sq.ft. (98 sq.m.) Super built-up Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,600 sq.ft. (149 sq.m.) Super built-up Area', '1,500 sq.ft. (139 sq.m.) Carpet Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '4,607 sq.ft. (428 sq.m.) Plot Area', '5,100 sq.ft. (474 sq.m.) Built-up Area', '2,035 sq.ft. (189 sq.m.) Built-up Area', '1,674 sq.ft. (156 sq.m.) Built-up Area', '1,200 sq.ft. (111 sq.m.) Built-up Area', '872 sq.ft. (81 sq.m.) Super built-up Area', '1,596 sq.ft. (148 sq.m.) Super built-up Area', '1,094 sq.ft. (102 sq.m.) Carpet Area', '1,500 sq.ft. (139 sq.m.) Plot Area', '1,650 sq.ft. (153 sq.m.) Plot Area', '870 sq.ft. (81 sq.m.) Carpet Area', '1,650 sq.ft. (153 sq.m.) Carpet Area', '1,170 sq.ft. (109 sq.m.) Built-up Area', '1,350 sq.ft. (125 sq.m.) Plot Area', '1,243 sq.ft. (115 sq.m.) Plot Area', '1,502 sq.ft. (140 sq.m.) Built-up Area', '1,750 sq.ft. (163 sq.m.) Carpet Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '7,623,000 sq.ft. (708200 sq.m.) Plot Area', '1,005 sq.ft. (93 sq.m.) Super built-up Area', '14,400 sq.ft. (1338 sq.m.) Plot Area', '1,355 sq.ft. (126 sq.m.) Carpet Area', '4,000 sq.ft. (372 sq.m.) Super built-up Area', '1,276 sq.ft. (119 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,780 sq.ft. (165 sq.m.) Super built-up Area', '844 sq.ft. (78 sq.m.) Super built-up Area', '1,195 sq.ft. (111 sq.m.) Carpet Area', '1,750 sq.ft. (163 sq.m.) Plot Area', '5,090 sq.ft. (473 sq.m.) Super built-up Area', '902 sq.ft. (84 sq.m.) Super built-up Area', '1,850 sq.ft. (172 sq.m.) Super built-up Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,200 sq.ft. (111 sq.m.) Plot Area', '1,327 sq.ft. (123 sq.m.) Super built-up Area', '4,200 sq.ft. (390 sq.m.) Plot Area', '960 sq.ft. (89 sq.m.) Plot Area', '1,330 sq.ft. (124 sq.m.) Super built-up Area']

In [28]:
characters_to_remove = ["sq.ft."," sq.m.) Built-up Area",","]

#regular expression pattern to match and remove special characters and characters
pattern = "[{}]".format("".join(characters_to_remove))

#list to store modified strings
total = []

for string in sqft:
    modified_string = re.sub(pattern, "", string)
    total.append(modified_string)

print(total)

['1200-12000(111-1115Po', '412-461(38-43C', '461(43C', '412-461(38-43C', '412-461(38-43C', '627(58C', '412-461(38-43C', '2280(212-', '1065(99-', '1165(108C', '1973(183Po', '3000(279Po', '3100(288Po', '3500(325-', '922(86Sb-', '1345(125-', '1468(136-', '1150(107C', '2400(223Po', '1373(128Sb-', '1200(111Po', '1200(111Po', '1483(138Po', '3675(341Po', '2050(190Sb-', '1131(105Sb-', '2400(223Po', '4000(372-', '2665(248Po', '1222(114-', '2700(251Po', '2378(221-', '1765(164Sb-', '1250(116Po', '7200(669Po', '1200(111Po', '1205(112Sb-', '1300(121Sb-', '1800(167Po', '1429(133Sb-', '1704(158C', '1314(122Sb-', '2293(213Po', '1200(111-', '1612(150-', '1165(108-', '1441(134Sb-', '2400(223Po', '1160(108Sb-', '1100(102Sb-', '800(74Po', '1200(111Po', '3000(279Po', '1800(167Po', '1750(163Sb-', '1340(124Sb-', '1233(115-', '1252(116-', '3569(332Po', '1005(93C', '1485(138Po', '1705(158-', '2400(223Po', '2505(233Po', '1500(139Po', '1380(128Sb-', '2590(241C', '1156(107C', '4000(372Po', '3600(334Sb-', '1530(142Po', '1285(119Sb-', '600(56Po', '1724(160-', '997(93Sb-', '5200(483Po', '1200(111Po', '1648(153Sb-', '1600(149Sb-', '1569(146Sb-', '950(88Sb-', '940(87-', '2400(223Po', '1500(139Sb-', '1021(95C', '1265(118Po', '1200(111Po', '1200(111Po', '1395(130Sb-', '2119(197Sb-', '1800(167Po', '7025(653Po', '1368(127C', '1600(149C', '1500(139Po', '1725(160-', '1074(100Sb-', '1200(111Po', '2627(244-', '1200(111Po', '1500(139Po', '1200(111Po', '920(85Sb-', '1200(111Po', '1375(128C', '1075(100-', '5000(465Sb-', '1307(121-', '1285(119Sb-', '1300(121Po', '1200(111Po', '1450(135Sb-', '1350(125Po', '2200(204Po', '1060(98C', '1235(115Sb-', '2075(193Sb-', '1199(111Po', '5400(502Po', '1650(153C', '65340(6070Po', '1360(126Po', '2600(242-', '2300(214Po', '1241(115Sb-', '1800(167Po', '1700(158Sb-', '814(76Sb-', '1340(124-', '2600(242-', '1100(102-', '1119(104Sb-', '3000(279Po', '1525(142Sb-', '907(84-', '1200(111Po', '2000(186Po', '1575(146-', '1261(117C', '1239(115Sb-', '1150(107-', '1500(139Po', '1590(148Sb-', '2012(187C', '1160(108Sb-', '995(92C', '1084(101Sb-', '1270(118Sb-', '4500(418C', '1485(138Sb-', '1650(153-', '1500(139Po', '3293(306Po', '2400(223Po', '2350(218Sb-', '1320(123-', '2000(186-', '1000(93C', '2000(186Sb-', '1335(124-', '1082(101C', '1200(111Po', '1200(111Po', '1566(145Sb-', '1125(105Sb-', '746(69-', '1475(137-', '2080(193Po', '1038(96Sb-', '1500(139Po', '2045(190Sb-', '1470(137Sb-', '2250(209-', '1520(141Sb-', '1075(100C', '1600(149C', '2180(203Po', '959(89Sb-', '2400(223Po', '735(68Po', '1200(111Po', '2400(223Po', '1525(142Sb-', '1879(175-', '1976(184Po', '1135(105-', '1115(104Sb-', '1340(124C', '1245(116Sb-', '1200(111Po', '1260(117Po', '1200(111Po', '1619(150C', '4500(418-', '1600(149Po', '1200(111Po', '1196(111Sb-', '780(72C', '1876(174Po', '940(87Sb-', '1410(131C', '1215(113Po', '1515(141Sb-', '1645(153Sb-', '1014(94Sb-', '500(46C', '1338(124Sb-', '1200(111Po', '2660(247Po', '2325(216Po', '1290(120Sb-', '1500(139C', '1630(151Sb-', '1200(111Po', '1265(118Sb-', '1326(123Po', '1187(110C', '2000(186Po', '2400(223Po', '2427(225Sb-', '1675(156Sb-', '4400(409-', '2100(195Po', '1200(111Po', '1025(95-', '1496(139Sb-', '5500(511Po', '1600(149Po', '916(85Po', '3000(279Po', '1200(111-', '1278(119Sb-', '40000(3716Po', '1382(128Po', '2100(195Po', '5000(465-', '1610(150Sb-', '1050(98Po', '1070(99Sb-', '2400(223Po', '1187(110Sb-', '1172(109C', '1520(141C', '1435(133Sb-', '1330(124Sb-', '4800(446Po', '1360(126Sb-', '1670(155Sb-', '1345(125Sb-', '1200(111Po', '1258(117Sb-', '2915(271Po', '1200(111C', '1815(169C', '2200(204Po', '1228(114Sb-', '1135(105C', '1150(107C', '4600(427Sb-', '928(86C', '1140(106-', '1000(93Po', '1200(111Po', '1200(111Po', '1000(93C', '1283(119Sb-', '10800(1003Po', '1390(129Sb-', '1200(111Sb-', '1197(111C', '814(76C', '1010(94-', '2400(223Po', '1747(162Po', '1400(130Sb-', '900(84Sb-', '1260(117Sb-', '1558(145Sb-', '1000(93-', '1570(146Sb-', '1166(108-', '1057(98Sb-', '1540(143-', '1488(138Sb-', '1004(93Po', '1270(118Po', '1055(98Sb-', '1500(139Po', '1600(149Sb-', '1500(139C', '1200(111Po', '4607(428Po', '5100(474-', '2035(189-', '1674(156-', '1200(111-', '872(81Sb-', '1596(148Sb-', '1094(102C', '1500(139Po', '1650(153Po', '870(81C', '1650(153C', '1170(109-', '1350(125Po', '1243(115Po', '1502(140-', '1750(163C', '1200(111Po', '7623000(708200Po', '1005(93Sb-', '14400(1338Po', '1355(126C', '4000(372Sb-', '1276(119Sb-', '1200(111Po', '1780(165Sb-', '844(78Sb-', '1195(111C', '1750(163Po', '5090(473Sb-', '902(84Sb-', '1850(172Sb-', '1200(111Po', '1200(111Po', '1327(123Sb-', '4200(390Po', '960(89Po', '1330(124Sb-']

In [29]:
pattern = "\(.*$"

#list to store modified strings
total_sqft = []

for string in total:
    modified_string = re.sub(pattern, "", string)
    total_sqft.append(modified_string)

print(total_sqft)

['1200-12000', '412-461', '461', '412-461', '412-461', '627', '412-461', '2280', '1065', '1165', '1973', '3000', '3100', '3500', '922', '1345', '1468', '1150', '2400', '1373', '1200', '1200', '1483', '3675', '2050', '1131', '2400', '4000', '2665', '1222', '2700', '2378', '1765', '1250', '7200', '1200', '1205', '1300', '1800', '1429', '1704', '1314', '2293', '1200', '1612', '1165', '1441', '2400', '1160', '1100', '800', '1200', '3000', '1800', '1750', '1340', '1233', '1252', '3569', '1005', '1485', '1705', '2400', '2505', '1500', '1380', '2590', '1156', '4000', '3600', '1530', '1285', '600', '1724', '997', '5200', '1200', '1648', '1600', '1569', '950', '940', '2400', '1500', '1021', '1265', '1200', '1200', '1395', '2119', '1800', '7025', '1368', '1600', '1500', '1725', '1074', '1200', '2627', '1200', '1500', '1200', '920', '1200', '1375', '1075', '5000', '1307', '1285', '1300', '1200', '1450', '1350', '2200', '1060', '1235', '2075', '1199', '5400', '1650', '65340', '1360', '2600', '2300', '1241', '1800', '1700', '814', '1340', '2600', '1100', '1119', '3000', '1525', '907', '1200', '2000', '1575', '1261', '1239', '1150', '1500', '1590', '2012', '1160', '995', '1084', '1270', '4500', '1485', '1650', '1500', '3293', '2400', '2350', '1320', '2000', '1000', '2000', '1335', '1082', '1200', '1200', '1566', '1125', '746', '1475', '2080', '1038', '1500', '2045', '1470', '2250', '1520', '1075', '1600', '2180', '959', '2400', '735', '1200', '2400', '1525', '1879', '1976', '1135', '1115', '1340', '1245', '1200', '1260', '1200', '1619', '4500', '1600', '1200', '1196', '780', '1876', '940', '1410', '1215', '1515', '1645', '1014', '500', '1338', '1200', '2660', '2325', '1290', '1500', '1630', '1200', '1265', '1326', '1187', '2000', '2400', '2427', '1675', '4400', '2100', '1200', '1025', '1496', '5500', '1600', '916', '3000', '1200', '1278', '40000', '1382', '2100', '5000', '1610', '1050', '1070', '2400', '1187', '1172', '1520', '1435', '1330', '4800', '1360', '1670', '1345', '1200', '1258', '2915', '1200', '1815', '2200', '1228', '1135', '1150', '4600', '928', '1140', '1000', '1200', '1200', '1000', '1283', '10800', '1390', '1200', '1197', '814', '1010', '2400', '1747', '1400', '900', '1260', '1558', '1000', '1570', '1166', '1057', '1540', '1488', '1004', '1270', '1055', '1500', '1600', '1500', '1200', '4607', '5100', '2035', '1674', '1200', '872', '1596', '1094', '1500', '1650', '870', '1650', '1170', '1350', '1243', '1502', '1750', '1200', '7623000', '1005', '14400', '1355', '4000', '1276', '1200', '1780', '844', '1195', '1750', '5090', '902', '1850', '1200', '1200', '1327', '4200', '960', '1330']

In [30]:
result = []
for item in total_sqft:
    if '-' in item:
        result.append(re.sub(r'.*-', '', item))
    else:
        result.append(item)

print(result)

['12000', '461', '461', '461', '461', '627', '461', '2280', '1065', '1165', '1973', '3000', '3100', '3500', '922', '1345', '1468', '1150', '2400', '1373', '1200', '1200', '1483', '3675', '2050', '1131', '2400', '4000', '2665', '1222', '2700', '2378', '1765', '1250', '7200', '1200', '1205', '1300', '1800', '1429', '1704', '1314', '2293', '1200', '1612', '1165', '1441', '2400', '1160', '1100', '800', '1200', '3000', '1800', '1750', '1340', '1233', '1252', '3569', '1005', '1485', '1705', '2400', '2505', '1500', '1380', '2590', '1156', '4000', '3600', '1530', '1285', '600', '1724', '997', '5200', '1200', '1648', '1600', '1569', '950', '940', '2400', '1500', '1021', '1265', '1200', '1200', '1395', '2119', '1800', '7025', '1368', '1600', '1500', '1725', '1074', '1200', '2627', '1200', '1500', '1200', '920', '1200', '1375', '1075', '5000', '1307', '1285', '1300', '1200', '1450', '1350', '2200', '1060', '1235', '2075', '1199', '5400', '1650', '65340', '1360', '2600', '2300', '1241', '1800', '1700', '814', '1340', '2600', '1100', '1119', '3000', '1525', '907', '1200', '2000', '1575', '1261', '1239', '1150', '1500', '1590', '2012', '1160', '995', '1084', '1270', '4500', '1485', '1650', '1500', '3293', '2400', '2350', '1320', '2000', '1000', '2000', '1335', '1082', '1200', '1200', '1566', '1125', '746', '1475', '2080', '1038', '1500', '2045', '1470', '2250', '1520', '1075', '1600', '2180', '959', '2400', '735', '1200', '2400', '1525', '1879', '1976', '1135', '1115', '1340', '1245', '1200', '1260', '1200', '1619', '4500', '1600', '1200', '1196', '780', '1876', '940', '1410', '1215', '1515', '1645', '1014', '500', '1338', '1200', '2660', '2325', '1290', '1500', '1630', '1200', '1265', '1326', '1187', '2000', '2400', '2427', '1675', '4400', '2100', '1200', '1025', '1496', '5500', '1600', '916', '3000', '1200', '1278', '40000', '1382', '2100', '5000', '1610', '1050', '1070', '2400', '1187', '1172', '1520', '1435', '1330', '4800', '1360', '1670', '1345', '1200', '1258', '2915', '1200', '1815', '2200', '1228', '1135', '1150', '4600', '928', '1140', '1000', '1200', '1200', '1000', '1283', '10800', '1390', '1200', '1197', '814', '1010', '2400', '1747', '1400', '900', '1260', '1558', '1000', '1570', '1166', '1057', '1540', '1488', '1004', '1270', '1055', '1500', '1600', '1500', '1200', '4607', '5100', '2035', '1674', '1200', '872', '1596', '1094', '1500', '1650', '870', '1650', '1170', '1350', '1243', '1502', '1750', '1200', '7623000', '1005', '14400', '1355', '4000', '1276', '1200', '1780', '844', '1195', '1750', '5090', '902', '1850', '1200', '1200', '1327', '4200', '960', '1330']

In [31]:
Total_SqFt = [int(x) for x in result]

print(Total_SqFt)

[12000, 461, 461, 461, 461, 627, 461, 2280, 1065, 1165, 1973, 3000, 3100, 3500, 922, 1345, 1468, 1150, 2400, 1373, 1200, 1200, 1483, 3675, 2050, 1131, 2400, 4000, 2665, 1222, 2700, 2378, 1765, 1250, 7200, 1200, 1205, 1300, 1800, 1429, 1704, 1314, 2293, 1200, 1612, 1165, 1441, 2400, 1160, 1100, 800, 1200, 3000, 1800, 1750, 1340, 1233, 1252, 3569, 1005, 1485, 1705, 2400, 2505, 1500, 1380, 2590, 1156, 4000, 3600, 1530, 1285, 600, 1724, 997, 5200, 1200, 1648, 1600, 1569, 950, 940, 2400, 1500, 1021, 1265, 1200, 1200, 1395, 2119, 1800, 7025, 1368, 1600, 1500, 1725, 1074, 1200, 2627, 1200, 1500, 1200, 920, 1200, 1375, 1075, 5000, 1307, 1285, 1300, 1200, 1450, 1350, 2200, 1060, 1235, 2075, 1199, 5400, 1650, 65340, 1360, 2600, 2300, 1241, 1800, 1700, 814, 1340, 2600, 1100, 1119, 3000, 1525, 907, 1200, 2000, 1575, 1261, 1239, 1150, 1500, 1590, 2012, 1160, 995, 1084, 1270, 4500, 1485, 1650, 1500, 3293, 2400, 2350, 1320, 2000, 1000, 2000, 1335, 1082, 1200, 1200, 1566, 1125, 746, 1475, 2080, 1038, 1500, 2045, 1470, 2250, 1520, 1075, 1600, 2180, 959, 2400, 735, 1200, 2400, 1525, 1879, 1976, 1135, 1115, 1340, 1245, 1200, 1260, 1200, 1619, 4500, 1600, 1200, 1196, 780, 1876, 940, 1410, 1215, 1515, 1645, 1014, 500, 1338, 1200, 2660, 2325, 1290, 1500, 1630, 1200, 1265, 1326, 1187, 2000, 2400, 2427, 1675, 4400, 2100, 1200, 1025, 1496, 5500, 1600, 916, 3000, 1200, 1278, 40000, 1382, 2100, 5000, 1610, 1050, 1070, 2400, 1187, 1172, 1520, 1435, 1330, 4800, 1360, 1670, 1345, 1200, 1258, 2915, 1200, 1815, 2200, 1228, 1135, 1150, 4600, 928, 1140, 1000, 1200, 1200, 1000, 1283, 10800, 1390, 1200, 1197, 814, 1010, 2400, 1747, 1400, 900, 1260, 1558, 1000, 1570, 1166, 1057, 1540, 1488, 1004, 1270, 1055, 1500, 1600, 1500, 1200, 4607, 5100, 2035, 1674, 1200, 872, 1596, 1094, 1500, 1650, 870, 1650, 1170, 1350, 1243, 1502, 1750, 1200, 7623000, 1005, 14400, 1355, 4000, 1276, 1200, 1780, 844, 1195, 1750, 5090, 902, 1850, 1200, 1200, 1327, 4200, 960, 1330]

# Total price

In [32]:
total_price = df['price'].tolist()

print(total_price)

['₹ 13.2 L - 1.32 Cr₹ 1,100/sq.ft.', '₹ 45.11  - 50.25 L₹ 10,925/sq.ft.', '₹ 50 L₹ 10,845/sq.ft.', '₹ 45.11  - 50.25 L₹ 10,925/sq.ft.', '₹ 45.11  - 50.25 L₹ 10,925/sq.ft.', '₹ 83 L₹ 13,238/sq.ft.', '₹ 54.54  - 61.03 L₹ 13,237/sq.ft.', '₹ 2.25 Cr₹ 9,868/sq.ft.', '₹ 69.95 L₹ 6,568/sq.ft.', '₹ 65 L₹ 5,579/sq.ft.', '₹ 3.5 Cr₹ 8,750/sq.ft.', '₹ 3.5 Cr₹ 11,666/sq.ft.', '₹ 1.4 Cr₹ 4,516/sq.ft.', '₹ 1.4 Cr₹ 3,429/sq.ft.', '₹ 65 L₹ 7,049/sq.ft.', '₹ 79 L₹ 5,873/sq.ft.', '₹ 52.85 L₹ 3,600/sq.ft.', '₹ 62 L₹ 5,391/sq.ft.', '₹ 7 Cr₹ 29,166/sq.ft.', '₹ 1.1 Cr₹ 11,167/sq.ft.', '₹ 72 L₹ 6,000/sq.ft.', '₹ 2.51 Cr₹ 20,916/sq.ft.', '₹ 1.4 Cr₹ 9,440/sq.ft.', '₹ 2.58 Cr₹ 7,020/sq.ft.', '₹ 1.6 Cr₹ 7,804/sq.ft.', '₹ 75 L₹ 6,732/sq.ft.', '₹ 4.2 Cr₹ 6,562/sq.ft.', '₹ 2.2 Cr₹ 5,500/sq.ft.', '₹ 3.9 Cr₹ 14,634/sq.ft.', '₹ 95 L₹ 7,774/sq.ft.', '₹ 1.75 Cr₹ 6,481/sq.ft.', '₹ 4.5 Cr₹ 18,919/sq.ft.', '₹ 1.72 Cr₹ 15,551/sq.ft.', '₹ 2.75 Cr₹ 6,470/sq.ft.', '₹ 3.24 Cr₹ 4,500/sq.ft.', '₹ 78 L₹ 6,500/sq.ft.', '₹ 80 L₹ 6,639/sq.ft.', '₹ 76 L₹ 5,846/sq.ft.', '₹ 1.4 Cr₹ 7,778/sq.ft.', '₹ 1.01 Cr₹ 7,067/sq.ft.', '₹ 1.4 Cr₹ 7,200/sq.ft.', '₹ 1.1 Cr₹ 8,371/sq.ft.', '₹ 1 Cr₹ 4,361/sq.ft.', '₹ 72 L₹ 6,000/sq.ft.', '₹ 82 L₹ 6,856/sq.ft.', '₹ 70 L₹ 6,008/sq.ft.', '₹ 68 L₹ 4,718/sq.ft.', '₹ 72 L₹ 3,000/sq.ft.', '₹ 57 L₹ 4,913/sq.ft.', '₹ 70 L₹ 6,363/sq.ft.', '₹ 1.3 Cr₹ 16,250/sq.ft.', '₹ 1.85 Cr₹ 15,416/sq.ft.', '₹ 90 L₹ 3,000/sq.ft.', '₹ 1.6 Cr₹ 8,333/sq.ft.', '₹ 90 L₹ 5,142/sq.ft.', '₹ 70 L₹ 5,223/sq.ft.', '₹ 90 L₹ 7,299/sq.ft.', '₹ 70 L₹ 5,990/sq.ft.', '₹ 1.96 Cr₹ 5,500/sq.ft.', '₹ 76 L₹ 7,562/sq.ft.', '₹ 42 L₹ 2,850/sq.ft.', '₹ 90 L₹ 5,278/sq.ft.', '₹ 1.44 Cr₹ 6,000/sq.ft.', '₹ 3.37 Cr₹ 11,462/sq.ft.', '₹ 2.5 Cr₹ 16,666/sq.ft.', '₹ 1.05 Cr₹ 7,101/sq.ft.', '₹ 2.2 Cr₹ 8,500/sq.ft.', '₹ 56.5 L₹ 4,887/sq.ft.', '₹ 68 L₹ 1,700/sq.ft.', '₹ 8.5 Cr₹ 22,222/sq.ft.', '₹ 1.42 Cr₹ 9,281/sq.ft.', '₹ 80 L₹ 6,225/sq.ft.', '₹ 1.1 Cr₹ 18,333/sq.ft.', '₹ 90 L₹ 5,220/sq.ft.', '₹ 65 L₹ 6,519/sq.ft.', '₹ 2.25 Cr₹ 4,326/sq.ft.', '₹ 1.8 Cr₹ 15,000/sq.ft.', '₹ 99 L₹ 6,005/sq.ft.', '₹ 86 L₹ 5,375/sq.ft.', '₹ 87 L₹ 5,544/sq.ft.', '₹ 62 L₹ 6,526/sq.ft.', '₹ 43 L₹ 4,574/sq.ft.', '₹ 5.94 Cr₹ 24,750/sq.ft.', '₹ 88 L₹ 5,866/sq.ft.', '₹ 90 L₹ 8,814/sq.ft.', '₹ 2.25 Cr₹ 17,786/sq.ft.', '₹ 1.14 Cr₹ 9,500/sq.ft.', '₹ 1.02 Cr₹ 8,500/sq.ft.', '₹ 88 L₹ 6,308/sq.ft.', '₹ 2.48 Cr₹ 11,703/sq.ft.', '₹ 75.6 L₹ 4,200/sq.ft.', '₹ 2.1 Cr₹ 2,989/sq.ft.', '₹ 75 L₹ 5,482/sq.ft.', '₹ 1.2 Cr₹ 7,500/sq.ft.', '₹ 2 Cr₹ 13,333/sq.ft.', '₹ 95 L₹ 5,420/sq.ft.', '₹ 76 L₹ 7,076/sq.ft.', '₹ 1.9 Cr₹ 15,833/sq.ft.', '₹ 2.4 Cr₹ 9,135/sq.ft.', '₹ 82 L₹ 6,833/sq.ft.', '₹ 22.5 L₹ 1,500/sq.ft.', '₹ 1.2 Cr₹ 10,000/sq.ft.', '₹ 45 L₹ 4,891/sq.ft.', '₹ 87 L₹ 7,250/sq.ft.', '₹ 69 L₹ 5,018/sq.ft.', '₹ 37 L₹ 3,441/sq.ft.', '₹ 3.2 Cr₹ 6,400/sq.ft.', '₹ 79 L₹ 6,044/sq.ft.', '₹ 1.4 Cr₹ 11,673/sq.ft.', '₹ 78 L₹ 6,000/sq.ft.', '₹ 1.44 Cr₹ 12,000/sq.ft.', '₹ 68 L₹ 4,690/sq.ft.', '₹ 2.5 Cr₹ 18,518/sq.ft.', '₹ 1.76 Cr₹ 8,000/sq.ft.', '₹ 1 Cr₹ 9,433/sq.ft.', '₹ 66 L₹ 5,344/sq.ft.', '₹ 1.66 Cr₹ 8,000/sq.ft.', '₹ 28 L₹ 2,334/sq.ft.', '₹ 19 Cr₹ 35,185/sq.ft.', '₹ 1.3 Cr₹ 8,484/sq.ft.', '₹ 12 Cr₹ 1,837/sq.ft.', '₹ 4.5 Cr₹ 8,720/sq.ft.', '₹ 2.49 Cr₹ 10,346/sq.ft.', '₹ 1.45 Cr₹ 6,304/sq.ft.', '₹ 70 L₹ 5,640/sq.ft.', '₹ 1.7 Cr₹ 9,444/sq.ft.', '₹ 79 L₹ 4,648/sq.ft.', '₹ 40 L₹ 4,914/sq.ft.', '₹ 1 Cr₹ 7,462/sq.ft.', '₹ 3.25 Cr₹ 10,000/sq.ft.', '₹ 74.6 L₹ 6,781/sq.ft.', '₹ 59 L₹ 5,272/sq.ft.', '₹ 3 Cr₹ 10,000/sq.ft.', '₹ 83 L₹ 5,500/sq.ft.', '₹ 80 L₹ 8,820/sq.ft.', '₹ 1.44 Cr₹ 12,000/sq.ft.', '₹ 80 L₹ 4,000/sq.ft.', '₹ 88 L₹ 6,000/sq.ft.', '₹ 83 L₹ 6,582/sq.ft.', '₹ 74 L₹ 5,972/sq.ft.', '₹ 90 L₹ 7,826/sq.ft.', '₹ 4.15 Cr₹ 27,666/sq.ft.', '₹ 1.3 Cr₹ 8,176/sq.ft.', '₹ 2.25 Cr₹ 11,182/sq.ft.', '₹ 62 L₹ 5,344/sq.ft.', '₹ 48 L₹ 4,824/sq.ft.', '₹ 50 L₹ 4,612/sq.ft.', '₹ 70 L₹ 5,511/sq.ft.', '₹ 3.99 Cr₹ 8,555/sq.ft.', '₹ 1.4 Cr₹ 11,666/sq.ft.', '₹ 1.25 Cr₹ 7,575/sq.ft.', '₹ 39 L₹ 2,500/sq.ft.', '₹ 57.63 L₹ 1,750/sq.ft.', '₹ 1.68 Cr₹ 7,000/sq.ft.', '₹ 2.6 Cr₹ 11,063/sq.ft.', '₹ 59 L₹ 4,469/sq.ft.', '₹ 1.75 Cr₹ 8,750/sq.ft.', '₹ 1.09 Cr₹ 10,900/sq.ft.', '₹ 1.3 Cr₹ 6,500/sq.ft.', '₹ 87 L₹ 6,516/sq.ft.', '₹ 64 L₹ 5,914/sq.ft.', '₹ 2.5 Cr₹ 20,000/sq.ft.', '₹ 1.5 Cr₹ 12,500/sq.ft.', '₹ 73 L₹ 4,661/sq.ft.', '₹ 43 L₹ 3,823/sq.ft.', '₹ 38 L₹ 5,093/sq.ft.', '₹ 54 L₹ 3,661/sq.ft.', '₹ 3 Cr₹ 14,423/sq.ft.', '₹ 30 L₹ 2,890/sq.ft.', '₹ 37.5 L₹ 2,500/sq.ft.', '₹ 1.55 Cr₹ 7,579/sq.ft.', '₹ 1 Cr₹ 6,803/sq.ft.', '₹ 1.55 Cr₹ 6,888/sq.ft.', '₹ 55 L₹ 3,618/sq.ft.', '₹ 48 L₹ 4,465/sq.ft.', '₹ 2.75 Cr₹ 17,187/sq.ft.', '₹ 1.7 Cr₹ 7,798/sq.ft.', '₹ 55 L₹ 6,256/sq.ft.', '₹ 1.08 Cr₹ 4,500/sq.ft.', '₹ 48 L₹ 6,530/sq.ft.', '₹ 90 L₹ 7,500/sq.ft.', '₹ 1.65 Cr₹ 6,875/sq.ft.', '₹ 52 L₹ 3,409/sq.ft.', '₹ 1.2 Cr₹ 6,386/sq.ft.', '₹ 90 L₹ 4,554/sq.ft.', '₹ 65 L₹ 5,726/sq.ft.', '₹ 65 L₹ 5,829/sq.ft.', '₹ 65 L₹ 4,850/sq.ft.', '₹ 68 L₹ 5,461/sq.ft.', '₹ 2.05 Cr₹ 20,833/sq.ft.', '₹ 3 Cr₹ 23,809/sq.ft.', '₹ 2.2 Cr₹ 20,754/sq.ft.', '₹ 95 L₹ 5,867/sq.ft.', '₹ 2.3 Cr₹ 5,111/sq.ft.', '₹ 3.33 Cr₹ 25,000/sq.ft.', '₹ 83 L₹ 6,916/sq.ft.', '₹ 85 L₹ 7,107/sq.ft.', '₹ 48 L₹ 6,153/sq.ft.', '₹ 85 L₹ 4,550/sq.ft.', '₹ 87 L₹ 9,255/sq.ft.', '₹ 85 L₹ 6,028/sq.ft.', '₹ 3.3 Cr₹ 27,160/sq.ft.', '₹ 67 L₹ 4,950/sq.ft.', '₹ 1.3 Cr₹ 9,118/sq.ft.', '₹ 95 L₹ 9,500/sq.ft.', '₹ 36 L₹ 7,200/sq.ft.', '₹ 85 L₹ 6,352/sq.ft.', '₹ 75 L₹ 6,250/sq.ft.', '₹ 3.3 Cr₹ 12,406/sq.ft.', '₹ 1.09 Cr₹ 4,688/sq.ft.', '₹ 95 L₹ 7,364/sq.ft.', '₹ 65 L₹ 4,333/sq.ft.', '₹ 1.05 Cr₹ 7,272/sq.ft.', '₹ 2.35 Cr₹ 19,583/sq.ft.', '₹ 85 L₹ 6,720/sq.ft.', '₹ 70 L₹ 5,279/sq.ft.', '₹ 38 L₹ 3,201/sq.ft.', '₹ 95 L₹ 4,750/sq.ft.', '₹ 3.3 Cr₹ 13,750/sq.ft.', '₹ 2.38 Cr₹ 9,806/sq.ft.', '₹ 1.35 Cr₹ 8,059/sq.ft.', '₹ 3.1 Cr₹ 7,045/sq.ft.', '₹ 2.1 Cr₹ 10,000/sq.ft.', '₹ 78 L₹ 6,500/sq.ft.', '₹ 88 L₹ 8,292/sq.ft.', '₹ 72 L₹ 4,812/sq.ft.', '₹ 60.4 L₹ 1,098/sq.ft.', '₹ 1.53 Cr₹ 9,562/sq.ft.', '₹ 40 L₹ 4,366/sq.ft.', '₹ 75 L₹ 2,500/sq.ft.', '₹ 79 L₹ 6,583/sq.ft.', '₹ 75 L₹ 5,868/sq.ft.', '₹ 2 Cr₹ 500/sq.ft.', '₹ 1.98 Cr₹ 14,327/sq.ft.', '₹ 3 Cr₹ 11,300/sq.ft.', '₹ 3.5 Cr₹ 7,000/sq.ft.', '₹ 1.3 Cr₹ 8,074/sq.ft.', '₹ 1.4 Cr₹ 13,181/sq.ft.', '₹ 62 L₹ 5,794/sq.ft.', '₹ 9.5 Cr₹ 39,583/sq.ft.', '₹ 70 L₹ 5,897/sq.ft.', '₹ 45 L₹ 3,839/sq.ft.', '₹ 85 L₹ 5,592/sq.ft.', '₹ 1.55 Cr₹ 15,500/sq.ft.', '₹ 58 L₹ 4,360/sq.ft.', '₹ 3.4 Cr₹ 7,166/sq.ft.', '₹ 82 L₹ 6,029/sq.ft.', '₹ 87 L₹ 5,209/sq.ft.', '₹ 75 L₹ 5,576/sq.ft.', '₹ 22.5 L₹ 1,875/sq.ft.', '₹ 83 L₹ 5,962/sq.ft.', '₹ 91 L₹ 3,121/sq.ft.', '₹ 65 L₹ 5,416/sq.ft.', '₹ 1.8 Cr₹ 9,917/sq.ft.', '₹ 1.28 Cr₹ 5,818/sq.ft.', '₹ 65 L₹ 5,293/sq.ft.', '₹ 50 L₹ 4,405/sq.ft.', '₹ 73 L₹ 6,260/sq.ft.', '₹ 2.5 Cr₹ 5,434/sq.ft.', '₹ 48 L₹ 5,172/sq.ft.', '₹ 62 L₹ 5,439/sq.ft.', '₹ 2.4 Cr₹ 24,000/sq.ft.', '₹ 1.1 Cr₹ 9,166/sq.ft.', '₹ 42 L₹ 3,500/sq.ft.', '₹ 50 L₹ 5,000/sq.ft.', '₹ 75 L₹ 5,845/sq.ft.', '₹ 4.5 Cr₹ 4,200/sq.ft.', '₹ 55 L₹ 3,956/sq.ft.', '₹ 75 L₹ 6,250/sq.ft.', '₹ 50 L₹ 4,177/sq.ft.', '₹ 45 L₹ 5,528/sq.ft.', '₹ 57 L₹ 6,039/sq.ft.', '₹ 2 Cr₹ 8,400/sq.ft.', '₹ 90 L₹ 5,151/sq.ft.', '₹ 1 Cr₹ 8,000/sq.ft.', '₹ 33 L₹ 3,666/sq.ft.', '₹ 70 L₹ 6,715/sq.ft.', '₹ 1.05 Cr₹ 6,740/sq.ft.', '₹ 45 L₹ 4,500/sq.ft.', '₹ 75 L₹ 5,033/sq.ft.', '₹ 90 L₹ 7,718/sq.ft.', '₹ 34 L₹ 3,216/sq.ft.', '₹ 70 L₹ 4,546/sq.ft.', '₹ 75 L₹ 5,040/sq.ft.', '₹ 76 L₹ 7,238/sq.ft.', '₹ 90 L₹ 7,086/sq.ft.', '₹ 68 L₹ 6,445/sq.ft.', '₹ 85 L₹ 4,676/sq.ft.', '₹ 65 L₹ 5,652/sq.ft.', '₹ 1.55 Cr₹ 10,333/sq.ft.', '₹ 36 L₹ 3,000/sq.ft.', '₹ 5.95 Cr₹ 12,915/sq.ft.', '₹ 5 Cr₹ 9,803/sq.ft.', '₹ 1.4 Cr₹ 6,879/sq.ft.', '₹ 85 L₹ 5,077/sq.ft.', '₹ 45 L₹ 3,750/sq.ft.', '₹ 48 L₹ 5,504/sq.ft.', '₹ 90 L₹ 5,639/sq.ft.', '₹ 95 L₹ 8,683/sq.ft.', '₹ 1.25 Cr₹ 8,333/sq.ft.', '₹ 95 L₹ 5,757/sq.ft.', '₹ 52.5 L₹ 6,034/sq.ft.', '₹ 85 L₹ 5,151/sq.ft.', '₹ 90 L₹ 8,120/sq.ft.', '₹ 1.5 Cr₹ 11,111/sq.ft.', '₹ 3.5 Cr₹ 28,157/sq.ft.', '₹ 99 L₹ 6,591/sq.ft.', '₹ 72 L₹ 4,114/sq.ft.', '₹ 1.75 Cr₹ 14,583/sq.ft.', '₹ 381.15 Cr₹ 500/sq.ft.', '₹ 78 L₹ 7,761/sq.ft.', '₹ 8.64 Cr₹ 6,000/sq.ft.', '₹ 1 Cr₹ 7,380/sq.ft.', '₹ 3.25 Cr₹ 8,125/sq.ft.', '₹ 90 L₹ 7,053/sq.ft.', '₹ 3 Cr₹ 25,000/sq.ft.', '₹ 1.1 Cr₹ 6,179/sq.ft.', '₹ 67 L₹ 7,938/sq.ft.', '₹ 55 L₹ 4,602/sq.ft.', '₹ 1.5 Cr₹ 8,571/sq.ft.', '₹ 6 Cr₹ 11,787/sq.ft.', '₹ 42.9 L₹ 4,756/sq.ft.', '₹ 1.76 Cr₹ 9,730/sq.ft.', '₹ 2.4 Cr₹ 20,000/sq.ft.', '₹ 1.7 Cr₹ 3,541/sq.ft.', '₹ 60 L₹ 4,898/sq.ft.', '₹ 19 Cr₹ 45,238/sq.ft.', '₹ 1.12 Cr₹ 11,650/sq.ft.', '₹ 58 L₹ 4,428/sq.ft.']

In [33]:
for price in total_price:
    match = re.search(r'₹ (.*)', price)
    print(match.group(1))

13.2 L - 1.32 Cr₹ 1,100/sq.ft.
45.11  - 50.25 L₹ 10,925/sq.ft.
50 L₹ 10,845/sq.ft.
45.11  - 50.25 L₹ 10,925/sq.ft.
45.11  - 50.25 L₹ 10,925/sq.ft.
83 L₹ 13,238/sq.ft.
54.54  - 61.03 L₹ 13,237/sq.ft.
2.25 Cr₹ 9,868/sq.ft.
69.95 L₹ 6,568/sq.ft.
65 L₹ 5,579/sq.ft.
3.5 Cr₹ 8,750/sq.ft.
3.5 Cr₹ 11,666/sq.ft.
1.4 Cr₹ 4,516/sq.ft.
1.4 Cr₹ 3,429/sq.ft.
65 L₹ 7,049/sq.ft.
79 L₹ 5,873/sq.ft.
52.85 L₹ 3,600/sq.ft.
62 L₹ 5,391/sq.ft.
7 Cr₹ 29,166/sq.ft.
1.1 Cr₹ 11,167/sq.ft.
72 L₹ 6,000/sq.ft.
2.51 Cr₹ 20,916/sq.ft.
1.4 Cr₹ 9,440/sq.ft.
2.58 Cr₹ 7,020/sq.ft.
1.6 Cr₹ 7,804/sq.ft.
75 L₹ 6,732/sq.ft.
4.2 Cr₹ 6,562/sq.ft.
2.2 Cr₹ 5,500/sq.ft.
3.9 Cr₹ 14,634/sq.ft.
95 L₹ 7,774/sq.ft.
1.75 Cr₹ 6,481/sq.ft.
4.5 Cr₹ 18,919/sq.ft.
1.72 Cr₹ 15,551/sq.ft.
2.75 Cr₹ 6,470/sq.ft.
3.24 Cr₹ 4,500/sq.ft.
78 L₹ 6,500/sq.ft.
80 L₹ 6,639/sq.ft.
76 L₹ 5,846/sq.ft.
1.4 Cr₹ 7,778/sq.ft.
1.01 Cr₹ 7,067/sq.ft.
1.4 Cr₹ 7,200/sq.ft.
1.1 Cr₹ 8,371/sq.ft.
1 Cr₹ 4,361/sq.ft.
72 L₹ 6,000/sq.ft.
82 L₹ 6,856/sq.ft.
70 L₹ 6,008/sq.ft.
68 L₹ 4,718/sq.ft.
72 L₹ 3,000/sq.ft.
57 L₹ 4,913/sq.ft.
70 L₹ 6,363/sq.ft.
1.3 Cr₹ 16,250/sq.ft.
1.85 Cr₹ 15,416/sq.ft.
90 L₹ 3,000/sq.ft.
1.6 Cr₹ 8,333/sq.ft.
90 L₹ 5,142/sq.ft.
70 L₹ 5,223/sq.ft.
90 L₹ 7,299/sq.ft.
70 L₹ 5,990/sq.ft.
1.96 Cr₹ 5,500/sq.ft.
76 L₹ 7,562/sq.ft.
42 L₹ 2,850/sq.ft.
90 L₹ 5,278/sq.ft.
1.44 Cr₹ 6,000/sq.ft.
3.37 Cr₹ 11,462/sq.ft.
2.5 Cr₹ 16,666/sq.ft.
1.05 Cr₹ 7,101/sq.ft.
2.2 Cr₹ 8,500/sq.ft.
56.5 L₹ 4,887/sq.ft.
68 L₹ 1,700/sq.ft.
8.5 Cr₹ 22,222/sq.ft.
1.42 Cr₹ 9,281/sq.ft.
80 L₹ 6,225/sq.ft.
1.1 Cr₹ 18,333/sq.ft.
90 L₹ 5,220/sq.ft.
65 L₹ 6,519/sq.ft.
2.25 Cr₹ 4,326/sq.ft.
1.8 Cr₹ 15,000/sq.ft.
99 L₹ 6,005/sq.ft.
86 L₹ 5,375/sq.ft.
87 L₹ 5,544/sq.ft.
62 L₹ 6,526/sq.ft.
43 L₹ 4,574/sq.ft.
5.94 Cr₹ 24,750/sq.ft.
88 L₹ 5,866/sq.ft.
90 L₹ 8,814/sq.ft.
2.25 Cr₹ 17,786/sq.ft.
1.14 Cr₹ 9,500/sq.ft.
1.02 Cr₹ 8,500/sq.ft.
88 L₹ 6,308/sq.ft.
2.48 Cr₹ 11,703/sq.ft.
75.6 L₹ 4,200/sq.ft.
2.1 Cr₹ 2,989/sq.ft.
75 L₹ 5,482/sq.ft.
1.2 Cr₹ 7,500/sq.ft.
2 Cr₹ 13,333/sq.ft.
95 L₹ 5,420/sq.ft.
76 L₹ 7,076/sq.ft.
1.9 Cr₹ 15,833/sq.ft.
2.4 Cr₹ 9,135/sq.ft.
82 L₹ 6,833/sq.ft.
22.5 L₹ 1,500/sq.ft.
1.2 Cr₹ 10,000/sq.ft.
45 L₹ 4,891/sq.ft.
87 L₹ 7,250/sq.ft.
69 L₹ 5,018/sq.ft.
37 L₹ 3,441/sq.ft.
3.2 Cr₹ 6,400/sq.ft.
79 L₹ 6,044/sq.ft.
1.4 Cr₹ 11,673/sq.ft.
78 L₹ 6,000/sq.ft.
1.44 Cr₹ 12,000/sq.ft.
68 L₹ 4,690/sq.ft.
2.5 Cr₹ 18,518/sq.ft.
1.76 Cr₹ 8,000/sq.ft.
1 Cr₹ 9,433/sq.ft.
66 L₹ 5,344/sq.ft.
1.66 Cr₹ 8,000/sq.ft.
28 L₹ 2,334/sq.ft.
19 Cr₹ 35,185/sq.ft.
1.3 Cr₹ 8,484/sq.ft.
12 Cr₹ 1,837/sq.ft.
4.5 Cr₹ 8,720/sq.ft.
2.49 Cr₹ 10,346/sq.ft.
1.45 Cr₹ 6,304/sq.ft.
70 L₹ 5,640/sq.ft.
1.7 Cr₹ 9,444/sq.ft.
79 L₹ 4,648/sq.ft.
40 L₹ 4,914/sq.ft.
1 Cr₹ 7,462/sq.ft.
3.25 Cr₹ 10,000/sq.ft.
74.6 L₹ 6,781/sq.ft.
59 L₹ 5,272/sq.ft.
3 Cr₹ 10,000/sq.ft.
83 L₹ 5,500/sq.ft.
80 L₹ 8,820/sq.ft.
1.44 Cr₹ 12,000/sq.ft.
80 L₹ 4,000/sq.ft.
88 L₹ 6,000/sq.ft.
83 L₹ 6,582/sq.ft.
74 L₹ 5,972/sq.ft.
90 L₹ 7,826/sq.ft.
4.15 Cr₹ 27,666/sq.ft.
1.3 Cr₹ 8,176/sq.ft.
2.25 Cr₹ 11,182/sq.ft.
62 L₹ 5,344/sq.ft.
48 L₹ 4,824/sq.ft.
50 L₹ 4,612/sq.ft.
70 L₹ 5,511/sq.ft.
3.99 Cr₹ 8,555/sq.ft.
1.4 Cr₹ 11,666/sq.ft.
1.25 Cr₹ 7,575/sq.ft.
39 L₹ 2,500/sq.ft.
57.63 L₹ 1,750/sq.ft.
1.68 Cr₹ 7,000/sq.ft.
2.6 Cr₹ 11,063/sq.ft.
59 L₹ 4,469/sq.ft.
1.75 Cr₹ 8,750/sq.ft.
1.09 Cr₹ 10,900/sq.ft.
1.3 Cr₹ 6,500/sq.ft.
87 L₹ 6,516/sq.ft.
64 L₹ 5,914/sq.ft.
2.5 Cr₹ 20,000/sq.ft.
1.5 Cr₹ 12,500/sq.ft.
73 L₹ 4,661/sq.ft.
43 L₹ 3,823/sq.ft.
38 L₹ 5,093/sq.ft.
54 L₹ 3,661/sq.ft.
3 Cr₹ 14,423/sq.ft.
30 L₹ 2,890/sq.ft.
37.5 L₹ 2,500/sq.ft.
1.55 Cr₹ 7,579/sq.ft.
1 Cr₹ 6,803/sq.ft.
1.55 Cr₹ 6,888/sq.ft.
55 L₹ 3,618/sq.ft.
48 L₹ 4,465/sq.ft.
2.75 Cr₹ 17,187/sq.ft.
1.7 Cr₹ 7,798/sq.ft.
55 L₹ 6,256/sq.ft.
1.08 Cr₹ 4,500/sq.ft.
48 L₹ 6,530/sq.ft.
90 L₹ 7,500/sq.ft.
1.65 Cr₹ 6,875/sq.ft.
52 L₹ 3,409/sq.ft.
1.2 Cr₹ 6,386/sq.ft.
90 L₹ 4,554/sq.ft.
65 L₹ 5,726/sq.ft.
65 L₹ 5,829/sq.ft.
65 L₹ 4,850/sq.ft.
68 L₹ 5,461/sq.ft.
2.05 Cr₹ 20,833/sq.ft.
3 Cr₹ 23,809/sq.ft.
2.2 Cr₹ 20,754/sq.ft.
95 L₹ 5,867/sq.ft.
2.3 Cr₹ 5,111/sq.ft.
3.33 Cr₹ 25,000/sq.ft.
83 L₹ 6,916/sq.ft.
85 L₹ 7,107/sq.ft.
48 L₹ 6,153/sq.ft.
85 L₹ 4,550/sq.ft.
87 L₹ 9,255/sq.ft.
85 L₹ 6,028/sq.ft.
3.3 Cr₹ 27,160/sq.ft.
67 L₹ 4,950/sq.ft.
1.3 Cr₹ 9,118/sq.ft.
95 L₹ 9,500/sq.ft.
36 L₹ 7,200/sq.ft.
85 L₹ 6,352/sq.ft.
75 L₹ 6,250/sq.ft.
3.3 Cr₹ 12,406/sq.ft.
1.09 Cr₹ 4,688/sq.ft.
95 L₹ 7,364/sq.ft.
65 L₹ 4,333/sq.ft.
1.05 Cr₹ 7,272/sq.ft.
2.35 Cr₹ 19,583/sq.ft.
85 L₹ 6,720/sq.ft.
70 L₹ 5,279/sq.ft.
38 L₹ 3,201/sq.ft.
95 L₹ 4,750/sq.ft.
3.3 Cr₹ 13,750/sq.ft.
2.38 Cr₹ 9,806/sq.ft.
1.35 Cr₹ 8,059/sq.ft.
3.1 Cr₹ 7,045/sq.ft.
2.1 Cr₹ 10,000/sq.ft.
78 L₹ 6,500/sq.ft.
88 L₹ 8,292/sq.ft.
72 L₹ 4,812/sq.ft.
60.4 L₹ 1,098/sq.ft.
1.53 Cr₹ 9,562/sq.ft.
40 L₹ 4,366/sq.ft.
75 L₹ 2,500/sq.ft.
79 L₹ 6,583/sq.ft.
75 L₹ 5,868/sq.ft.
2 Cr₹ 500/sq.ft.
1.98 Cr₹ 14,327/sq.ft.
3 Cr₹ 11,300/sq.ft.
3.5 Cr₹ 7,000/sq.ft.
1.3 Cr₹ 8,074/sq.ft.
1.4 Cr₹ 13,181/sq.ft.
62 L₹ 5,794/sq.ft.
9.5 Cr₹ 39,583/sq.ft.
70 L₹ 5,897/sq.ft.
45 L₹ 3,839/sq.ft.
85 L₹ 5,592/sq.ft.
1.55 Cr₹ 15,500/sq.ft.
58 L₹ 4,360/sq.ft.
3.4 Cr₹ 7,166/sq.ft.
82 L₹ 6,029/sq.ft.
87 L₹ 5,209/sq.ft.
75 L₹ 5,576/sq.ft.
22.5 L₹ 1,875/sq.ft.
83 L₹ 5,962/sq.ft.
91 L₹ 3,121/sq.ft.
65 L₹ 5,416/sq.ft.
1.8 Cr₹ 9,917/sq.ft.
1.28 Cr₹ 5,818/sq.ft.
65 L₹ 5,293/sq.ft.
50 L₹ 4,405/sq.ft.
73 L₹ 6,260/sq.ft.
2.5 Cr₹ 5,434/sq.ft.
48 L₹ 5,172/sq.ft.
62 L₹ 5,439/sq.ft.
2.4 Cr₹ 24,000/sq.ft.
1.1 Cr₹ 9,166/sq.ft.
42 L₹ 3,500/sq.ft.
50 L₹ 5,000/sq.ft.
75 L₹ 5,845/sq.ft.
4.5 Cr₹ 4,200/sq.ft.
55 L₹ 3,956/sq.ft.
75 L₹ 6,250/sq.ft.
50 L₹ 4,177/sq.ft.
45 L₹ 5,528/sq.ft.
57 L₹ 6,039/sq.ft.
2 Cr₹ 8,400/sq.ft.
90 L₹ 5,151/sq.ft.
1 Cr₹ 8,000/sq.ft.
33 L₹ 3,666/sq.ft.
70 L₹ 6,715/sq.ft.
1.05 Cr₹ 6,740/sq.ft.
45 L₹ 4,500/sq.ft.
75 L₹ 5,033/sq.ft.
90 L₹ 7,718/sq.ft.
34 L₹ 3,216/sq.ft.
70 L₹ 4,546/sq.ft.
75 L₹ 5,040/sq.ft.
76 L₹ 7,238/sq.ft.
90 L₹ 7,086/sq.ft.
68 L₹ 6,445/sq.ft.
85 L₹ 4,676/sq.ft.
65 L₹ 5,652/sq.ft.
1.55 Cr₹ 10,333/sq.ft.
36 L₹ 3,000/sq.ft.
5.95 Cr₹ 12,915/sq.ft.
5 Cr₹ 9,803/sq.ft.
1.4 Cr₹ 6,879/sq.ft.
85 L₹ 5,077/sq.ft.
45 L₹ 3,750/sq.ft.
48 L₹ 5,504/sq.ft.
90 L₹ 5,639/sq.ft.
95 L₹ 8,683/sq.ft.
1.25 Cr₹ 8,333/sq.ft.
95 L₹ 5,757/sq.ft.
52.5 L₹ 6,034/sq.ft.
85 L₹ 5,151/sq.ft.
90 L₹ 8,120/sq.ft.
1.5 Cr₹ 11,111/sq.ft.
3.5 Cr₹ 28,157/sq.ft.
99 L₹ 6,591/sq.ft.
72 L₹ 4,114/sq.ft.
1.75 Cr₹ 14,583/sq.ft.
381.15 Cr₹ 500/sq.ft.
78 L₹ 7,761/sq.ft.
8.64 Cr₹ 6,000/sq.ft.
1 Cr₹ 7,380/sq.ft.
3.25 Cr₹ 8,125/sq.ft.
90 L₹ 7,053/sq.ft.
3 Cr₹ 25,000/sq.ft.
1.1 Cr₹ 6,179/sq.ft.
67 L₹ 7,938/sq.ft.
55 L₹ 4,602/sq.ft.
1.5 Cr₹ 8,571/sq.ft.
6 Cr₹ 11,787/sq.ft.
42.9 L₹ 4,756/sq.ft.
1.76 Cr₹ 9,730/sq.ft.
2.4 Cr₹ 20,000/sq.ft.
1.7 Cr₹ 3,541/sq.ft.
60 L₹ 4,898/sq.ft.
19 Cr₹ 45,238/sq.ft.
1.12 Cr₹ 11,650/sq.ft.
58 L₹ 4,428/sq.ft.

In [34]:
for price in total_price:
    matches = re.findall(r'₹\s*\d+[.,]?\d*', price)
    print(matches)

['₹ 13.2', '₹ 1,100']
['₹ 45.11', '₹ 10,925']
['₹ 50', '₹ 10,845']
['₹ 45.11', '₹ 10,925']
['₹ 45.11', '₹ 10,925']
['₹ 83', '₹ 13,238']
['₹ 54.54', '₹ 13,237']
['₹ 2.25', '₹ 9,868']
['₹ 69.95', '₹ 6,568']
['₹ 65', '₹ 5,579']
['₹ 3.5', '₹ 8,750']
['₹ 3.5', '₹ 11,666']
['₹ 1.4', '₹ 4,516']
['₹ 1.4', '₹ 3,429']
['₹ 65', '₹ 7,049']
['₹ 79', '₹ 5,873']
['₹ 52.85', '₹ 3,600']
['₹ 62', '₹ 5,391']
['₹ 7', '₹ 29,166']
['₹ 1.1', '₹ 11,167']
['₹ 72', '₹ 6,000']
['₹ 2.51', '₹ 20,916']
['₹ 1.4', '₹ 9,440']
['₹ 2.58', '₹ 7,020']
['₹ 1.6', '₹ 7,804']
['₹ 75', '₹ 6,732']
['₹ 4.2', '₹ 6,562']
['₹ 2.2', '₹ 5,500']
['₹ 3.9', '₹ 14,634']
['₹ 95', '₹ 7,774']
['₹ 1.75', '₹ 6,481']
['₹ 4.5', '₹ 18,919']
['₹ 1.72', '₹ 15,551']
['₹ 2.75', '₹ 6,470']
['₹ 3.24', '₹ 4,500']
['₹ 78', '₹ 6,500']
['₹ 80', '₹ 6,639']
['₹ 76', '₹ 5,846']
['₹ 1.4', '₹ 7,778']
['₹ 1.01', '₹ 7,067']
['₹ 1.4', '₹ 7,200']
['₹ 1.1', '₹ 8,371']
['₹ 1', '₹ 4,361']
['₹ 72', '₹ 6,000']
['₹ 82', '₹ 6,856']
['₹ 70', '₹ 6,008']
['₹ 68', '₹ 4,718']
['₹ 72', '₹ 3,000']
['₹ 57', '₹ 4,913']
['₹ 70', '₹ 6,363']
['₹ 1.3', '₹ 16,250']
['₹ 1.85', '₹ 15,416']
['₹ 90', '₹ 3,000']
['₹ 1.6', '₹ 8,333']
['₹ 90', '₹ 5,142']
['₹ 70', '₹ 5,223']
['₹ 90', '₹ 7,299']
['₹ 70', '₹ 5,990']
['₹ 1.96', '₹ 5,500']
['₹ 76', '₹ 7,562']
['₹ 42', '₹ 2,850']
['₹ 90', '₹ 5,278']
['₹ 1.44', '₹ 6,000']
['₹ 3.37', '₹ 11,462']
['₹ 2.5', '₹ 16,666']
['₹ 1.05', '₹ 7,101']
['₹ 2.2', '₹ 8,500']
['₹ 56.5', '₹ 4,887']
['₹ 68', '₹ 1,700']
['₹ 8.5', '₹ 22,222']
['₹ 1.42', '₹ 9,281']
['₹ 80', '₹ 6,225']
['₹ 1.1', '₹ 18,333']
['₹ 90', '₹ 5,220']
['₹ 65', '₹ 6,519']
['₹ 2.25', '₹ 4,326']
['₹ 1.8', '₹ 15,000']
['₹ 99', '₹ 6,005']
['₹ 86', '₹ 5,375']
['₹ 87', '₹ 5,544']
['₹ 62', '₹ 6,526']
['₹ 43', '₹ 4,574']
['₹ 5.94', '₹ 24,750']
['₹ 88', '₹ 5,866']
['₹ 90', '₹ 8,814']
['₹ 2.25', '₹ 17,786']
['₹ 1.14', '₹ 9,500']
['₹ 1.02', '₹ 8,500']
['₹ 88', '₹ 6,308']
['₹ 2.48', '₹ 11,703']
['₹ 75.6', '₹ 4,200']
['₹ 2.1', '₹ 2,989']
['₹ 75', '₹ 5,482']
['₹ 1.2', '₹ 7,500']
['₹ 2', '₹ 13,333']
['₹ 95', '₹ 5,420']
['₹ 76', '₹ 7,076']
['₹ 1.9', '₹ 15,833']
['₹ 2.4', '₹ 9,135']
['₹ 82', '₹ 6,833']
['₹ 22.5', '₹ 1,500']
['₹ 1.2', '₹ 10,000']
['₹ 45', '₹ 4,891']
['₹ 87', '₹ 7,250']
['₹ 69', '₹ 5,018']
['₹ 37', '₹ 3,441']
['₹ 3.2', '₹ 6,400']
['₹ 79', '₹ 6,044']
['₹ 1.4', '₹ 11,673']
['₹ 78', '₹ 6,000']
['₹ 1.44', '₹ 12,000']
['₹ 68', '₹ 4,690']
['₹ 2.5', '₹ 18,518']
['₹ 1.76', '₹ 8,000']
['₹ 1', '₹ 9,433']
['₹ 66', '₹ 5,344']
['₹ 1.66', '₹ 8,000']
['₹ 28', '₹ 2,334']
['₹ 19', '₹ 35,185']
['₹ 1.3', '₹ 8,484']
['₹ 12', '₹ 1,837']
['₹ 4.5', '₹ 8,720']
['₹ 2.49', '₹ 10,346']
['₹ 1.45', '₹ 6,304']
['₹ 70', '₹ 5,640']
['₹ 1.7', '₹ 9,444']
['₹ 79', '₹ 4,648']
['₹ 40', '₹ 4,914']
['₹ 1', '₹ 7,462']
['₹ 3.25', '₹ 10,000']
['₹ 74.6', '₹ 6,781']
['₹ 59', '₹ 5,272']
['₹ 3', '₹ 10,000']
['₹ 83', '₹ 5,500']
['₹ 80', '₹ 8,820']
['₹ 1.44', '₹ 12,000']
['₹ 80', '₹ 4,000']
['₹ 88', '₹ 6,000']
['₹ 83', '₹ 6,582']
['₹ 74', '₹ 5,972']
['₹ 90', '₹ 7,826']
['₹ 4.15', '₹ 27,666']
['₹ 1.3', '₹ 8,176']
['₹ 2.25', '₹ 11,182']
['₹ 62', '₹ 5,344']
['₹ 48', '₹ 4,824']
['₹ 50', '₹ 4,612']
['₹ 70', '₹ 5,511']
['₹ 3.99', '₹ 8,555']
['₹ 1.4', '₹ 11,666']
['₹ 1.25', '₹ 7,575']
['₹ 39', '₹ 2,500']
['₹ 57.63', '₹ 1,750']
['₹ 1.68', '₹ 7,000']
['₹ 2.6', '₹ 11,063']
['₹ 59', '₹ 4,469']
['₹ 1.75', '₹ 8,750']
['₹ 1.09', '₹ 10,900']
['₹ 1.3', '₹ 6,500']
['₹ 87', '₹ 6,516']
['₹ 64', '₹ 5,914']
['₹ 2.5', '₹ 20,000']
['₹ 1.5', '₹ 12,500']
['₹ 73', '₹ 4,661']
['₹ 43', '₹ 3,823']
['₹ 38', '₹ 5,093']
['₹ 54', '₹ 3,661']
['₹ 3', '₹ 14,423']
['₹ 30', '₹ 2,890']
['₹ 37.5', '₹ 2,500']
['₹ 1.55', '₹ 7,579']
['₹ 1', '₹ 6,803']
['₹ 1.55', '₹ 6,888']
['₹ 55', '₹ 3,618']
['₹ 48', '₹ 4,465']
['₹ 2.75', '₹ 17,187']
['₹ 1.7', '₹ 7,798']
['₹ 55', '₹ 6,256']
['₹ 1.08', '₹ 4,500']
['₹ 48', '₹ 6,530']
['₹ 90', '₹ 7,500']
['₹ 1.65', '₹ 6,875']
['₹ 52', '₹ 3,409']
['₹ 1.2', '₹ 6,386']
['₹ 90', '₹ 4,554']
['₹ 65', '₹ 5,726']
['₹ 65', '₹ 5,829']
['₹ 65', '₹ 4,850']
['₹ 68', '₹ 5,461']
['₹ 2.05', '₹ 20,833']
['₹ 3', '₹ 23,809']
['₹ 2.2', '₹ 20,754']
['₹ 95', '₹ 5,867']
['₹ 2.3', '₹ 5,111']
['₹ 3.33', '₹ 25,000']
['₹ 83', '₹ 6,916']
['₹ 85', '₹ 7,107']
['₹ 48', '₹ 6,153']
['₹ 85', '₹ 4,550']
['₹ 87', '₹ 9,255']
['₹ 85', '₹ 6,028']
['₹ 3.3', '₹ 27,160']
['₹ 67', '₹ 4,950']
['₹ 1.3', '₹ 9,118']
['₹ 95', '₹ 9,500']
['₹ 36', '₹ 7,200']
['₹ 85', '₹ 6,352']
['₹ 75', '₹ 6,250']
['₹ 3.3', '₹ 12,406']
['₹ 1.09', '₹ 4,688']
['₹ 95', '₹ 7,364']
['₹ 65', '₹ 4,333']
['₹ 1.05', '₹ 7,272']
['₹ 2.35', '₹ 19,583']
['₹ 85', '₹ 6,720']
['₹ 70', '₹ 5,279']
['₹ 38', '₹ 3,201']
['₹ 95', '₹ 4,750']
['₹ 3.3', '₹ 13,750']
['₹ 2.38', '₹ 9,806']
['₹ 1.35', '₹ 8,059']
['₹ 3.1', '₹ 7,045']
['₹ 2.1', '₹ 10,000']
['₹ 78', '₹ 6,500']
['₹ 88', '₹ 8,292']
['₹ 72', '₹ 4,812']
['₹ 60.4', '₹ 1,098']
['₹ 1.53', '₹ 9,562']
['₹ 40', '₹ 4,366']
['₹ 75', '₹ 2,500']
['₹ 79', '₹ 6,583']
['₹ 75', '₹ 5,868']
['₹ 2', '₹ 500']
['₹ 1.98', '₹ 14,327']
['₹ 3', '₹ 11,300']
['₹ 3.5', '₹ 7,000']
['₹ 1.3', '₹ 8,074']
['₹ 1.4', '₹ 13,181']
['₹ 62', '₹ 5,794']
['₹ 9.5', '₹ 39,583']
['₹ 70', '₹ 5,897']
['₹ 45', '₹ 3,839']
['₹ 85', '₹ 5,592']
['₹ 1.55', '₹ 15,500']
['₹ 58', '₹ 4,360']
['₹ 3.4', '₹ 7,166']
['₹ 82', '₹ 6,029']
['₹ 87', '₹ 5,209']
['₹ 75', '₹ 5,576']
['₹ 22.5', '₹ 1,875']
['₹ 83', '₹ 5,962']
['₹ 91', '₹ 3,121']
['₹ 65', '₹ 5,416']
['₹ 1.8', '₹ 9,917']
['₹ 1.28', '₹ 5,818']
['₹ 65', '₹ 5,293']
['₹ 50', '₹ 4,405']
['₹ 73', '₹ 6,260']
['₹ 2.5', '₹ 5,434']
['₹ 48', '₹ 5,172']
['₹ 62', '₹ 5,439']
['₹ 2.4', '₹ 24,000']
['₹ 1.1', '₹ 9,166']
['₹ 42', '₹ 3,500']
['₹ 50', '₹ 5,000']
['₹ 75', '₹ 5,845']
['₹ 4.5', '₹ 4,200']
['₹ 55', '₹ 3,956']
['₹ 75', '₹ 6,250']
['₹ 50', '₹ 4,177']
['₹ 45', '₹ 5,528']
['₹ 57', '₹ 6,039']
['₹ 2', '₹ 8,400']
['₹ 90', '₹ 5,151']
['₹ 1', '₹ 8,000']
['₹ 33', '₹ 3,666']
['₹ 70', '₹ 6,715']
['₹ 1.05', '₹ 6,740']
['₹ 45', '₹ 4,500']
['₹ 75', '₹ 5,033']
['₹ 90', '₹ 7,718']
['₹ 34', '₹ 3,216']
['₹ 70', '₹ 4,546']
['₹ 75', '₹ 5,040']
['₹ 76', '₹ 7,238']
['₹ 90', '₹ 7,086']
['₹ 68', '₹ 6,445']
['₹ 85', '₹ 4,676']
['₹ 65', '₹ 5,652']
['₹ 1.55', '₹ 10,333']
['₹ 36', '₹ 3,000']
['₹ 5.95', '₹ 12,915']
['₹ 5', '₹ 9,803']
['₹ 1.4', '₹ 6,879']
['₹ 85', '₹ 5,077']
['₹ 45', '₹ 3,750']
['₹ 48', '₹ 5,504']
['₹ 90', '₹ 5,639']
['₹ 95', '₹ 8,683']
['₹ 1.25', '₹ 8,333']
['₹ 95', '₹ 5,757']
['₹ 52.5', '₹ 6,034']
['₹ 85', '₹ 5,151']
['₹ 90', '₹ 8,120']
['₹ 1.5', '₹ 11,111']
['₹ 3.5', '₹ 28,157']
['₹ 99', '₹ 6,591']
['₹ 72', '₹ 4,114']
['₹ 1.75', '₹ 14,583']
['₹ 381.15', '₹ 500']
['₹ 78', '₹ 7,761']
['₹ 8.64', '₹ 6,000']
['₹ 1', '₹ 7,380']
['₹ 3.25', '₹ 8,125']
['₹ 90', '₹ 7,053']
['₹ 3', '₹ 25,000']
['₹ 1.1', '₹ 6,179']
['₹ 67', '₹ 7,938']
['₹ 55', '₹ 4,602']
['₹ 1.5', '₹ 8,571']
['₹ 6', '₹ 11,787']
['₹ 42.9', '₹ 4,756']
['₹ 1.76', '₹ 9,730']
['₹ 2.4', '₹ 20,000']
['₹ 1.7', '₹ 3,541']
['₹ 60', '₹ 4,898']
['₹ 19', '₹ 45,238']
['₹ 1.12', '₹ 11,650']
['₹ 58', '₹ 4,428']

In [35]:
matches = []

for price in total_price:
    matches.extend(re.findall(r'₹\s*\d+(?:[,.]\d+)*', price))

print(matches)

['₹ 13.2', '₹ 1,100', '₹ 45.11', '₹ 10,925', '₹ 50', '₹ 10,845', '₹ 45.11', '₹ 10,925', '₹ 45.11', '₹ 10,925', '₹ 83', '₹ 13,238', '₹ 54.54', '₹ 13,237', '₹ 2.25', '₹ 9,868', '₹ 69.95', '₹ 6,568', '₹ 65', '₹ 5,579', '₹ 3.5', '₹ 8,750', '₹ 3.5', '₹ 11,666', '₹ 1.4', '₹ 4,516', '₹ 1.4', '₹ 3,429', '₹ 65', '₹ 7,049', '₹ 79', '₹ 5,873', '₹ 52.85', '₹ 3,600', '₹ 62', '₹ 5,391', '₹ 7', '₹ 29,166', '₹ 1.1', '₹ 11,167', '₹ 72', '₹ 6,000', '₹ 2.51', '₹ 20,916', '₹ 1.4', '₹ 9,440', '₹ 2.58', '₹ 7,020', '₹ 1.6', '₹ 7,804', '₹ 75', '₹ 6,732', '₹ 4.2', '₹ 6,562', '₹ 2.2', '₹ 5,500', '₹ 3.9', '₹ 14,634', '₹ 95', '₹ 7,774', '₹ 1.75', '₹ 6,481', '₹ 4.5', '₹ 18,919', '₹ 1.72', '₹ 15,551', '₹ 2.75', '₹ 6,470', '₹ 3.24', '₹ 4,500', '₹ 78', '₹ 6,500', '₹ 80', '₹ 6,639', '₹ 76', '₹ 5,846', '₹ 1.4', '₹ 7,778', '₹ 1.01', '₹ 7,067', '₹ 1.4', '₹ 7,200', '₹ 1.1', '₹ 8,371', '₹ 1', '₹ 4,361', '₹ 72', '₹ 6,000', '₹ 82', '₹ 6,856', '₹ 70', '₹ 6,008', '₹ 68', '₹ 4,718', '₹ 72', '₹ 3,000', '₹ 57', '₹ 4,913', '₹ 70', '₹ 6,363', '₹ 1.3', '₹ 16,250', '₹ 1.85', '₹ 15,416', '₹ 90', '₹ 3,000', '₹ 1.6', '₹ 8,333', '₹ 90', '₹ 5,142', '₹ 70', '₹ 5,223', '₹ 90', '₹ 7,299', '₹ 70', '₹ 5,990', '₹ 1.96', '₹ 5,500', '₹ 76', '₹ 7,562', '₹ 42', '₹ 2,850', '₹ 90', '₹ 5,278', '₹ 1.44', '₹ 6,000', '₹ 3.37', '₹ 11,462', '₹ 2.5', '₹ 16,666', '₹ 1.05', '₹ 7,101', '₹ 2.2', '₹ 8,500', '₹ 56.5', '₹ 4,887', '₹ 68', '₹ 1,700', '₹ 8.5', '₹ 22,222', '₹ 1.42', '₹ 9,281', '₹ 80', '₹ 6,225', '₹ 1.1', '₹ 18,333', '₹ 90', '₹ 5,220', '₹ 65', '₹ 6,519', '₹ 2.25', '₹ 4,326', '₹ 1.8', '₹ 15,000', '₹ 99', '₹ 6,005', '₹ 86', '₹ 5,375', '₹ 87', '₹ 5,544', '₹ 62', '₹ 6,526', '₹ 43', '₹ 4,574', '₹ 5.94', '₹ 24,750', '₹ 88', '₹ 5,866', '₹ 90', '₹ 8,814', '₹ 2.25', '₹ 17,786', '₹ 1.14', '₹ 9,500', '₹ 1.02', '₹ 8,500', '₹ 88', '₹ 6,308', '₹ 2.48', '₹ 11,703', '₹ 75.6', '₹ 4,200', '₹ 2.1', '₹ 2,989', '₹ 75', '₹ 5,482', '₹ 1.2', '₹ 7,500', '₹ 2', '₹ 13,333', '₹ 95', '₹ 5,420', '₹ 76', '₹ 7,076', '₹ 1.9', '₹ 15,833', '₹ 2.4', '₹ 9,135', '₹ 82', '₹ 6,833', '₹ 22.5', '₹ 1,500', '₹ 1.2', '₹ 10,000', '₹ 45', '₹ 4,891', '₹ 87', '₹ 7,250', '₹ 69', '₹ 5,018', '₹ 37', '₹ 3,441', '₹ 3.2', '₹ 6,400', '₹ 79', '₹ 6,044', '₹ 1.4', '₹ 11,673', '₹ 78', '₹ 6,000', '₹ 1.44', '₹ 12,000', '₹ 68', '₹ 4,690', '₹ 2.5', '₹ 18,518', '₹ 1.76', '₹ 8,000', '₹ 1', '₹ 9,433', '₹ 66', '₹ 5,344', '₹ 1.66', '₹ 8,000', '₹ 28', '₹ 2,334', '₹ 19', '₹ 35,185', '₹ 1.3', '₹ 8,484', '₹ 12', '₹ 1,837', '₹ 4.5', '₹ 8,720', '₹ 2.49', '₹ 10,346', '₹ 1.45', '₹ 6,304', '₹ 70', '₹ 5,640', '₹ 1.7', '₹ 9,444', '₹ 79', '₹ 4,648', '₹ 40', '₹ 4,914', '₹ 1', '₹ 7,462', '₹ 3.25', '₹ 10,000', '₹ 74.6', '₹ 6,781', '₹ 59', '₹ 5,272', '₹ 3', '₹ 10,000', '₹ 83', '₹ 5,500', '₹ 80', '₹ 8,820', '₹ 1.44', '₹ 12,000', '₹ 80', '₹ 4,000', '₹ 88', '₹ 6,000', '₹ 83', '₹ 6,582', '₹ 74', '₹ 5,972', '₹ 90', '₹ 7,826', '₹ 4.15', '₹ 27,666', '₹ 1.3', '₹ 8,176', '₹ 2.25', '₹ 11,182', '₹ 62', '₹ 5,344', '₹ 48', '₹ 4,824', '₹ 50', '₹ 4,612', '₹ 70', '₹ 5,511', '₹ 3.99', '₹ 8,555', '₹ 1.4', '₹ 11,666', '₹ 1.25', '₹ 7,575', '₹ 39', '₹ 2,500', '₹ 57.63', '₹ 1,750', '₹ 1.68', '₹ 7,000', '₹ 2.6', '₹ 11,063', '₹ 59', '₹ 4,469', '₹ 1.75', '₹ 8,750', '₹ 1.09', '₹ 10,900', '₹ 1.3', '₹ 6,500', '₹ 87', '₹ 6,516', '₹ 64', '₹ 5,914', '₹ 2.5', '₹ 20,000', '₹ 1.5', '₹ 12,500', '₹ 73', '₹ 4,661', '₹ 43', '₹ 3,823', '₹ 38', '₹ 5,093', '₹ 54', '₹ 3,661', '₹ 3', '₹ 14,423', '₹ 30', '₹ 2,890', '₹ 37.5', '₹ 2,500', '₹ 1.55', '₹ 7,579', '₹ 1', '₹ 6,803', '₹ 1.55', '₹ 6,888', '₹ 55', '₹ 3,618', '₹ 48', '₹ 4,465', '₹ 2.75', '₹ 17,187', '₹ 1.7', '₹ 7,798', '₹ 55', '₹ 6,256', '₹ 1.08', '₹ 4,500', '₹ 48', '₹ 6,530', '₹ 90', '₹ 7,500', '₹ 1.65', '₹ 6,875', '₹ 52', '₹ 3,409', '₹ 1.2', '₹ 6,386', '₹ 90', '₹ 4,554', '₹ 65', '₹ 5,726', '₹ 65', '₹ 5,829', '₹ 65', '₹ 4,850', '₹ 68', '₹ 5,461', '₹ 2.05', '₹ 20,833', '₹ 3', '₹ 23,809', '₹ 2.2', '₹ 20,754', '₹ 95', '₹ 5,867', '₹ 2.3', '₹ 5,111', '₹ 3.33', '₹ 25,000', '₹ 83', '₹ 6,916', '₹ 85', '₹ 7,107', '₹ 48', '₹ 6,153', '₹ 85', '₹ 4,550', '₹ 87', '₹ 9,255', '₹ 85', '₹ 6,028', '₹ 3.3', '₹ 27,160', '₹ 67', '₹ 4,950', '₹ 1.3', '₹ 9,118', '₹ 95', '₹ 9,500', '₹ 36', '₹ 7,200', '₹ 85', '₹ 6,352', '₹ 75', '₹ 6,250', '₹ 3.3', '₹ 12,406', '₹ 1.09', '₹ 4,688', '₹ 95', '₹ 7,364', '₹ 65', '₹ 4,333', '₹ 1.05', '₹ 7,272', '₹ 2.35', '₹ 19,583', '₹ 85', '₹ 6,720', '₹ 70', '₹ 5,279', '₹ 38', '₹ 3,201', '₹ 95', '₹ 4,750', '₹ 3.3', '₹ 13,750', '₹ 2.38', '₹ 9,806', '₹ 1.35', '₹ 8,059', '₹ 3.1', '₹ 7,045', '₹ 2.1', '₹ 10,000', '₹ 78', '₹ 6,500', '₹ 88', '₹ 8,292', '₹ 72', '₹ 4,812', '₹ 60.4', '₹ 1,098', '₹ 1.53', '₹ 9,562', '₹ 40', '₹ 4,366', '₹ 75', '₹ 2,500', '₹ 79', '₹ 6,583', '₹ 75', '₹ 5,868', '₹ 2', '₹ 500', '₹ 1.98', '₹ 14,327', '₹ 3', '₹ 11,300', '₹ 3.5', '₹ 7,000', '₹ 1.3', '₹ 8,074', '₹ 1.4', '₹ 13,181', '₹ 62', '₹ 5,794', '₹ 9.5', '₹ 39,583', '₹ 70', '₹ 5,897', '₹ 45', '₹ 3,839', '₹ 85', '₹ 5,592', '₹ 1.55', '₹ 15,500', '₹ 58', '₹ 4,360', '₹ 3.4', '₹ 7,166', '₹ 82', '₹ 6,029', '₹ 87', '₹ 5,209', '₹ 75', '₹ 5,576', '₹ 22.5', '₹ 1,875', '₹ 83', '₹ 5,962', '₹ 91', '₹ 3,121', '₹ 65', '₹ 5,416', '₹ 1.8', '₹ 9,917', '₹ 1.28', '₹ 5,818', '₹ 65', '₹ 5,293', '₹ 50', '₹ 4,405', '₹ 73', '₹ 6,260', '₹ 2.5', '₹ 5,434', '₹ 48', '₹ 5,172', '₹ 62', '₹ 5,439', '₹ 2.4', '₹ 24,000', '₹ 1.1', '₹ 9,166', '₹ 42', '₹ 3,500', '₹ 50', '₹ 5,000', '₹ 75', '₹ 5,845', '₹ 4.5', '₹ 4,200', '₹ 55', '₹ 3,956', '₹ 75', '₹ 6,250', '₹ 50', '₹ 4,177', '₹ 45', '₹ 5,528', '₹ 57', '₹ 6,039', '₹ 2', '₹ 8,400', '₹ 90', '₹ 5,151', '₹ 1', '₹ 8,000', '₹ 33', '₹ 3,666', '₹ 70', '₹ 6,715', '₹ 1.05', '₹ 6,740', '₹ 45', '₹ 4,500', '₹ 75', '₹ 5,033', '₹ 90', '₹ 7,718', '₹ 34', '₹ 3,216', '₹ 70', '₹ 4,546', '₹ 75', '₹ 5,040', '₹ 76', '₹ 7,238', '₹ 90', '₹ 7,086', '₹ 68', '₹ 6,445', '₹ 85', '₹ 4,676', '₹ 65', '₹ 5,652', '₹ 1.55', '₹ 10,333', '₹ 36', '₹ 3,000', '₹ 5.95', '₹ 12,915', '₹ 5', '₹ 9,803', '₹ 1.4', '₹ 6,879', '₹ 85', '₹ 5,077', '₹ 45', '₹ 3,750', '₹ 48', '₹ 5,504', '₹ 90', '₹ 5,639', '₹ 95', '₹ 8,683', '₹ 1.25', '₹ 8,333', '₹ 95', '₹ 5,757', '₹ 52.5', '₹ 6,034', '₹ 85', '₹ 5,151', '₹ 90', '₹ 8,120', '₹ 1.5', '₹ 11,111', '₹ 3.5', '₹ 28,157', '₹ 99', '₹ 6,591', '₹ 72', '₹ 4,114', '₹ 1.75', '₹ 14,583', '₹ 381.15', '₹ 500', '₹ 78', '₹ 7,761', '₹ 8.64', '₹ 6,000', '₹ 1', '₹ 7,380', '₹ 3.25', '₹ 8,125', '₹ 90', '₹ 7,053', '₹ 3', '₹ 25,000', '₹ 1.1', '₹ 6,179', '₹ 67', '₹ 7,938', '₹ 55', '₹ 4,602', '₹ 1.5', '₹ 8,571', '₹ 6', '₹ 11,787', '₹ 42.9', '₹ 4,756', '₹ 1.76', '₹ 9,730', '₹ 2.4', '₹ 20,000', '₹ 1.7', '₹ 3,541', '₹ 60', '₹ 4,898', '₹ 19', '₹ 45,238', '₹ 1.12', '₹ 11,650', '₹ 58', '₹ 4,428']

In [36]:
new_matches = matches[0::2]
print(new_matches)

['₹ 13.2', '₹ 45.11', '₹ 50', '₹ 45.11', '₹ 45.11', '₹ 83', '₹ 54.54', '₹ 2.25', '₹ 69.95', '₹ 65', '₹ 3.5', '₹ 3.5', '₹ 1.4', '₹ 1.4', '₹ 65', '₹ 79', '₹ 52.85', '₹ 62', '₹ 7', '₹ 1.1', '₹ 72', '₹ 2.51', '₹ 1.4', '₹ 2.58', '₹ 1.6', '₹ 75', '₹ 4.2', '₹ 2.2', '₹ 3.9', '₹ 95', '₹ 1.75', '₹ 4.5', '₹ 1.72', '₹ 2.75', '₹ 3.24', '₹ 78', '₹ 80', '₹ 76', '₹ 1.4', '₹ 1.01', '₹ 1.4', '₹ 1.1', '₹ 1', '₹ 72', '₹ 82', '₹ 70', '₹ 68', '₹ 72', '₹ 57', '₹ 70', '₹ 1.3', '₹ 1.85', '₹ 90', '₹ 1.6', '₹ 90', '₹ 70', '₹ 90', '₹ 70', '₹ 1.96', '₹ 76', '₹ 42', '₹ 90', '₹ 1.44', '₹ 3.37', '₹ 2.5', '₹ 1.05', '₹ 2.2', '₹ 56.5', '₹ 68', '₹ 8.5', '₹ 1.42', '₹ 80', '₹ 1.1', '₹ 90', '₹ 65', '₹ 2.25', '₹ 1.8', '₹ 99', '₹ 86', '₹ 87', '₹ 62', '₹ 43', '₹ 5.94', '₹ 88', '₹ 90', '₹ 2.25', '₹ 1.14', '₹ 1.02', '₹ 88', '₹ 2.48', '₹ 75.6', '₹ 2.1', '₹ 75', '₹ 1.2', '₹ 2', '₹ 95', '₹ 76', '₹ 1.9', '₹ 2.4', '₹ 82', '₹ 22.5', '₹ 1.2', '₹ 45', '₹ 87', '₹ 69', '₹ 37', '₹ 3.2', '₹ 79', '₹ 1.4', '₹ 78', '₹ 1.44', '₹ 68', '₹ 2.5', '₹ 1.76', '₹ 1', '₹ 66', '₹ 1.66', '₹ 28', '₹ 19', '₹ 1.3', '₹ 12', '₹ 4.5', '₹ 2.49', '₹ 1.45', '₹ 70', '₹ 1.7', '₹ 79', '₹ 40', '₹ 1', '₹ 3.25', '₹ 74.6', '₹ 59', '₹ 3', '₹ 83', '₹ 80', '₹ 1.44', '₹ 80', '₹ 88', '₹ 83', '₹ 74', '₹ 90', '₹ 4.15', '₹ 1.3', '₹ 2.25', '₹ 62', '₹ 48', '₹ 50', '₹ 70', '₹ 3.99', '₹ 1.4', '₹ 1.25', '₹ 39', '₹ 57.63', '₹ 1.68', '₹ 2.6', '₹ 59', '₹ 1.75', '₹ 1.09', '₹ 1.3', '₹ 87', '₹ 64', '₹ 2.5', '₹ 1.5', '₹ 73', '₹ 43', '₹ 38', '₹ 54', '₹ 3', '₹ 30', '₹ 37.5', '₹ 1.55', '₹ 1', '₹ 1.55', '₹ 55', '₹ 48', '₹ 2.75', '₹ 1.7', '₹ 55', '₹ 1.08', '₹ 48', '₹ 90', '₹ 1.65', '₹ 52', '₹ 1.2', '₹ 90', '₹ 65', '₹ 65', '₹ 65', '₹ 68', '₹ 2.05', '₹ 3', '₹ 2.2', '₹ 95', '₹ 2.3', '₹ 3.33', '₹ 83', '₹ 85', '₹ 48', '₹ 85', '₹ 87', '₹ 85', '₹ 3.3', '₹ 67', '₹ 1.3', '₹ 95', '₹ 36', '₹ 85', '₹ 75', '₹ 3.3', '₹ 1.09', '₹ 95', '₹ 65', '₹ 1.05', '₹ 2.35', '₹ 85', '₹ 70', '₹ 38', '₹ 95', '₹ 3.3', '₹ 2.38', '₹ 1.35', '₹ 3.1', '₹ 2.1', '₹ 78', '₹ 88', '₹ 72', '₹ 60.4', '₹ 1.53', '₹ 40', '₹ 75', '₹ 79', '₹ 75', '₹ 2', '₹ 1.98', '₹ 3', '₹ 3.5', '₹ 1.3', '₹ 1.4', '₹ 62', '₹ 9.5', '₹ 70', '₹ 45', '₹ 85', '₹ 1.55', '₹ 58', '₹ 3.4', '₹ 82', '₹ 87', '₹ 75', '₹ 22.5', '₹ 83', '₹ 91', '₹ 65', '₹ 1.8', '₹ 1.28', '₹ 65', '₹ 50', '₹ 73', '₹ 2.5', '₹ 48', '₹ 62', '₹ 2.4', '₹ 1.1', '₹ 42', '₹ 50', '₹ 75', '₹ 4.5', '₹ 55', '₹ 75', '₹ 50', '₹ 45', '₹ 57', '₹ 2', '₹ 90', '₹ 1', '₹ 33', '₹ 70', '₹ 1.05', '₹ 45', '₹ 75', '₹ 90', '₹ 34', '₹ 70', '₹ 75', '₹ 76', '₹ 90', '₹ 68', '₹ 85', '₹ 65', '₹ 1.55', '₹ 36', '₹ 5.95', '₹ 5', '₹ 1.4', '₹ 85', '₹ 45', '₹ 48', '₹ 90', '₹ 95', '₹ 1.25', '₹ 95', '₹ 52.5', '₹ 85', '₹ 90', '₹ 1.5', '₹ 3.5', '₹ 99', '₹ 72', '₹ 1.75', '₹ 381.15', '₹ 78', '₹ 8.64', '₹ 1', '₹ 3.25', '₹ 90', '₹ 3', '₹ 1.1', '₹ 67', '₹ 55', '₹ 1.5', '₹ 6', '₹ 42.9', '₹ 1.76', '₹ 2.4', '₹ 1.7', '₹ 60', '₹ 19', '₹ 1.12', '₹ 58']

In [37]:
new_matches = [str(x.replace("₹ ","")) if type(x) == str else x for x in new_matches]
print(new_matches)

['13.2', '45.11', '50', '45.11', '45.11', '83', '54.54', '2.25', '69.95', '65', '3.5', '3.5', '1.4', '1.4', '65', '79', '52.85', '62', '7', '1.1', '72', '2.51', '1.4', '2.58', '1.6', '75', '4.2', '2.2', '3.9', '95', '1.75', '4.5', '1.72', '2.75', '3.24', '78', '80', '76', '1.4', '1.01', '1.4', '1.1', '1', '72', '82', '70', '68', '72', '57', '70', '1.3', '1.85', '90', '1.6', '90', '70', '90', '70', '1.96', '76', '42', '90', '1.44', '3.37', '2.5', '1.05', '2.2', '56.5', '68', '8.5', '1.42', '80', '1.1', '90', '65', '2.25', '1.8', '99', '86', '87', '62', '43', '5.94', '88', '90', '2.25', '1.14', '1.02', '88', '2.48', '75.6', '2.1', '75', '1.2', '2', '95', '76', '1.9', '2.4', '82', '22.5', '1.2', '45', '87', '69', '37', '3.2', '79', '1.4', '78', '1.44', '68', '2.5', '1.76', '1', '66', '1.66', '28', '19', '1.3', '12', '4.5', '2.49', '1.45', '70', '1.7', '79', '40', '1', '3.25', '74.6', '59', '3', '83', '80', '1.44', '80', '88', '83', '74', '90', '4.15', '1.3', '2.25', '62', '48', '50', '70', '3.99', '1.4', '1.25', '39', '57.63', '1.68', '2.6', '59', '1.75', '1.09', '1.3', '87', '64', '2.5', '1.5', '73', '43', '38', '54', '3', '30', '37.5', '1.55', '1', '1.55', '55', '48', '2.75', '1.7', '55', '1.08', '48', '90', '1.65', '52', '1.2', '90', '65', '65', '65', '68', '2.05', '3', '2.2', '95', '2.3', '3.33', '83', '85', '48', '85', '87', '85', '3.3', '67', '1.3', '95', '36', '85', '75', '3.3', '1.09', '95', '65', '1.05', '2.35', '85', '70', '38', '95', '3.3', '2.38', '1.35', '3.1', '2.1', '78', '88', '72', '60.4', '1.53', '40', '75', '79', '75', '2', '1.98', '3', '3.5', '1.3', '1.4', '62', '9.5', '70', '45', '85', '1.55', '58', '3.4', '82', '87', '75', '22.5', '83', '91', '65', '1.8', '1.28', '65', '50', '73', '2.5', '48', '62', '2.4', '1.1', '42', '50', '75', '4.5', '55', '75', '50', '45', '57', '2', '90', '1', '33', '70', '1.05', '45', '75', '90', '34', '70', '75', '76', '90', '68', '85', '65', '1.55', '36', '5.95', '5', '1.4', '85', '45', '48', '90', '95', '1.25', '95', '52.5', '85', '90', '1.5', '3.5', '99', '72', '1.75', '381.15', '78', '8.64', '1', '3.25', '90', '3', '1.1', '67', '55', '1.5', '6', '42.9', '1.76', '2.4', '1.7', '60', '19', '1.12', '58']

In [38]:
for i, val in enumerate(new_matches):
    if ',' in val:
        # keep as it is
        continue
    elif '.' in val:
        if val.index('.') == 1:
            new_matches[i] = float(val) * 10000000
        else:
            new_matches[i] = float(val) * 100000
    elif len(val) == 2:
        new_matches[i] = int(val) * 100000
    else:
        new_matches[i] = int(val) * 10000000

In [39]:
new_matches

[1320000.0,
 4511000.0,
 5000000,
 4511000.0,
 4511000.0,
 8300000,
 5454000.0,
 22500000.0,
 6995000.0,
 6500000,
 35000000.0,
 35000000.0,
 14000000.0,
 14000000.0,
 6500000,
 7900000,
 5285000.0,
 6200000,
 70000000,
 11000000.0,
 7200000,
 25099999.999999996,
 14000000.0,
 25800000.0,
 16000000.0,
 7500000,
 42000000.0,
 22000000.0,
 39000000.0,
 9500000,
 17500000.0,
 45000000.0,
 17200000.0,
 27500000.0,
 32400000.000000004,
 7800000,
 8000000,
 7600000,
 14000000.0,
 10100000.0,
 14000000.0,
 11000000.0,
 10000000,
 7200000,
 8200000,
 7000000,
 6800000,
 7200000,
 5700000,
 7000000,
 13000000.0,
 18500000.0,
 9000000,
 16000000.0,
 9000000,
 7000000,
 9000000,
 7000000,
 19600000.0,
 7600000,
 4200000,
 9000000,
 14400000.0,
 33700000.0,
 25000000.0,
 10500000.0,
 22000000.0,
 5650000.0,
 6800000,
 85000000.0,
 14200000.0,
 8000000,
 11000000.0,
 9000000,
 6500000,
 22500000.0,
 18000000.0,
 9900000,
 8600000,
 8700000,
 6200000,
 4300000,
 59400000.00000001,
 8800000,
 9000000,
 22500000.0,
 11399999.999999998,
 10200000.0,
 8800000,
 24800000.0,
 7559999.999999999,
 21000000.0,
 7500000,
 12000000.0,
 20000000,
 9500000,
 7600000,
 19000000.0,
 24000000.0,
 8200000,
 2250000.0,
 12000000.0,
 4500000,
 8700000,
 6900000,
 3700000,
 32000000.0,
 7900000,
 14000000.0,
 7800000,
 14400000.0,
 6800000,
 25000000.0,
 17600000.0,
 10000000,
 6600000,
 16600000.0,
 2800000,
 1900000,
 13000000.0,
 1200000,
 45000000.0,
 24900000.000000004,
 14500000.0,
 7000000,
 17000000.0,
 7900000,
 4000000,
 10000000,
 32500000.0,
 7459999.999999999,
 5900000,
 30000000,
 8300000,
 8000000,
 14400000.0,
 8000000,
 8800000,
 8300000,
 7400000,
 9000000,
 41500000.0,
 13000000.0,
 22500000.0,
 6200000,
 4800000,
 5000000,
 7000000,
 39900000.0,
 14000000.0,
 12500000.0,
 3900000,
 5763000.0,
 16800000.0,
 26000000.0,
 5900000,
 17500000.0,
 10900000.0,
 13000000.0,
 8700000,
 6400000,
 25000000.0,
 15000000.0,
 7300000,
 4300000,
 3800000,
 5400000,
 30000000,
 3000000,
 3750000.0,
 15500000.0,
 10000000,
 15500000.0,
 5500000,
 4800000,
 27500000.0,
 17000000.0,
 5500000,
 10800000.0,
 4800000,
 9000000,
 16500000.0,
 5200000,
 12000000.0,
 9000000,
 6500000,
 6500000,
 6500000,
 6800000,
 20500000.0,
 30000000,
 22000000.0,
 9500000,
 23000000.0,
 33300000.0,
 8300000,
 8500000,
 4800000,
 8500000,
 8700000,
 8500000,
 33000000.0,
 6700000,
 13000000.0,
 9500000,
 3600000,
 8500000,
 7500000,
 33000000.0,
 10900000.0,
 9500000,
 6500000,
 10500000.0,
 23500000.0,
 8500000,
 7000000,
 3800000,
 9500000,
 33000000.0,
 23800000.0,
 13500000.0,
 31000000.0,
 21000000.0,
 7800000,
 8800000,
 7200000,
 6040000.0,
 15300000.0,
 4000000,
 7500000,
 7900000,
 7500000,
 20000000,
 19800000.0,
 30000000,
 35000000.0,
 13000000.0,
 14000000.0,
 6200000,
 95000000.0,
 7000000,
 4500000,
 8500000,
 15500000.0,
 5800000,
 34000000.0,
 8200000,
 8700000,
 7500000,
 2250000.0,
 8300000,
 9100000,
 6500000,
 18000000.0,
 12800000.0,
 6500000,
 5000000,
 7300000,
 25000000.0,
 4800000,
 6200000,
 24000000.0,
 11000000.0,
 4200000,
 5000000,
 7500000,
 45000000.0,
 5500000,
 7500000,
 5000000,
 4500000,
 5700000,
 20000000,
 9000000,
 10000000,
 3300000,
 7000000,
 10500000.0,
 4500000,
 7500000,
 9000000,
 3400000,
 7000000,
 7500000,
 7600000,
 9000000,
 6800000,
 8500000,
 6500000,
 15500000.0,
 3600000,
 59500000.0,
 50000000,
 14000000.0,
 8500000,
 4500000,
 4800000,
 9000000,
 9500000,
 12500000.0,
 9500000,
 5250000.0,
 8500000,
 9000000,
 15000000.0,
 35000000.0,
 9900000,
 7200000,
 17500000.0,
 38115000.0,
 7800000,
 86400000.0,
 10000000,
 32500000.0,
 9000000,
 30000000,
 11000000.0,
 6700000,
 5500000,
 15000000.0,
 60000000,
 4290000.0,
 17600000.0,
 24000000.0,
 17000000.0,
 6000000,
 1900000,
 11200000.000000002,
 5800000]

In [40]:
len(new_matches)

329

In [41]:
for i, val in enumerate(new_matches):
    if isinstance(val, str):
        val = val.replace(',','') # remove the comma from the string
    new_matches[i] = int(val) # convert to integer

In [42]:
new_matches

[1320000,
 4511000,
 5000000,
 4511000,
 4511000,
 8300000,
 5454000,
 22500000,
 6995000,
 6500000,
 35000000,
 35000000,
 14000000,
 14000000,
 6500000,
 7900000,
 5285000,
 6200000,
 70000000,
 11000000,
 7200000,
 25099999,
 14000000,
 25800000,
 16000000,
 7500000,
 42000000,
 22000000,
 39000000,
 9500000,
 17500000,
 45000000,
 17200000,
 27500000,
 32400000,
 7800000,
 8000000,
 7600000,
 14000000,
 10100000,
 14000000,
 11000000,
 10000000,
 7200000,
 8200000,
 7000000,
 6800000,
 7200000,
 5700000,
 7000000,
 13000000,
 18500000,
 9000000,
 16000000,
 9000000,
 7000000,
 9000000,
 7000000,
 19600000,
 7600000,
 4200000,
 9000000,
 14400000,
 33700000,
 25000000,
 10500000,
 22000000,
 5650000,
 6800000,
 85000000,
 14200000,
 8000000,
 11000000,
 9000000,
 6500000,
 22500000,
 18000000,
 9900000,
 8600000,
 8700000,
 6200000,
 4300000,
 59400000,
 8800000,
 9000000,
 22500000,
 11399999,
 10200000,
 8800000,
 24800000,
 7559999,
 21000000,
 7500000,
 12000000,
 20000000,
 9500000,
 7600000,
 19000000,
 24000000,
 8200000,
 2250000,
 12000000,
 4500000,
 8700000,
 6900000,
 3700000,
 32000000,
 7900000,
 14000000,
 7800000,
 14400000,
 6800000,
 25000000,
 17600000,
 10000000,
 6600000,
 16600000,
 2800000,
 1900000,
 13000000,
 1200000,
 45000000,
 24900000,
 14500000,
 7000000,
 17000000,
 7900000,
 4000000,
 10000000,
 32500000,
 7459999,
 5900000,
 30000000,
 8300000,
 8000000,
 14400000,
 8000000,
 8800000,
 8300000,
 7400000,
 9000000,
 41500000,
 13000000,
 22500000,
 6200000,
 4800000,
 5000000,
 7000000,
 39900000,
 14000000,
 12500000,
 3900000,
 5763000,
 16800000,
 26000000,
 5900000,
 17500000,
 10900000,
 13000000,
 8700000,
 6400000,
 25000000,
 15000000,
 7300000,
 4300000,
 3800000,
 5400000,
 30000000,
 3000000,
 3750000,
 15500000,
 10000000,
 15500000,
 5500000,
 4800000,
 27500000,
 17000000,
 5500000,
 10800000,
 4800000,
 9000000,
 16500000,
 5200000,
 12000000,
 9000000,
 6500000,
 6500000,
 6500000,
 6800000,
 20500000,
 30000000,
 22000000,
 9500000,
 23000000,
 33300000,
 8300000,
 8500000,
 4800000,
 8500000,
 8700000,
 8500000,
 33000000,
 6700000,
 13000000,
 9500000,
 3600000,
 8500000,
 7500000,
 33000000,
 10900000,
 9500000,
 6500000,
 10500000,
 23500000,
 8500000,
 7000000,
 3800000,
 9500000,
 33000000,
 23800000,
 13500000,
 31000000,
 21000000,
 7800000,
 8800000,
 7200000,
 6040000,
 15300000,
 4000000,
 7500000,
 7900000,
 7500000,
 20000000,
 19800000,
 30000000,
 35000000,
 13000000,
 14000000,
 6200000,
 95000000,
 7000000,
 4500000,
 8500000,
 15500000,
 5800000,
 34000000,
 8200000,
 8700000,
 7500000,
 2250000,
 8300000,
 9100000,
 6500000,
 18000000,
 12800000,
 6500000,
 5000000,
 7300000,
 25000000,
 4800000,
 6200000,
 24000000,
 11000000,
 4200000,
 5000000,
 7500000,
 45000000,
 5500000,
 7500000,
 5000000,
 4500000,
 5700000,
 20000000,
 9000000,
 10000000,
 3300000,
 7000000,
 10500000,
 4500000,
 7500000,
 9000000,
 3400000,
 7000000,
 7500000,
 7600000,
 9000000,
 6800000,
 8500000,
 6500000,
 15500000,
 3600000,
 59500000,
 50000000,
 14000000,
 8500000,
 4500000,
 4800000,
 9000000,
 9500000,
 12500000,
 9500000,
 5250000,
 8500000,
 9000000,
 15000000,
 35000000,
 9900000,
 7200000,
 17500000,
 38115000,
 7800000,
 86400000,
 10000000,
 32500000,
 9000000,
 30000000,
 11000000,
 6700000,
 5500000,
 15000000,
 60000000,
 4290000,
 17600000,
 24000000,
 17000000,
 6000000,
 1900000,
 11200000,
 5800000]

# builtup area

In [43]:
builtup_area = df['builtup_area'].tolist()

print(builtup_area)

['(111-1115 sq.m.) Plot Area', '(38-43 sq.m.) Carpet Area', '(43 sq.m.) Carpet Area', '(38-43 sq.m.) Carpet Area', '(38-43 sq.m.) Carpet Area', '(58 sq.m.) Carpet Area', '(38-43 sq.m.) Carpet Area', '(212 sq.m.) Built-up Area', '(99 sq.m.) Built-up Area', '(108 sq.m.) Carpet Area', '(183 sq.m.) Plot Area', '(279 sq.m.) Plot Area', '(288 sq.m.) Plot Area', '(325 sq.m.) Built-up Area', '(86 sq.m.) Super built-up Area', '(125 sq.m.) Built-up Area', '(136 sq.m.) Built-up Area', '(107 sq.m.) Carpet Area', '(223 sq.m.) Plot Area', '(128 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(138 sq.m.) Plot Area', '(341 sq.m.) Plot Area', '(190 sq.m.) Super built-up Area', '(105 sq.m.) Super built-up Area', '(223 sq.m.) Plot Area', '(372 sq.m.) Built-up Area', '(248 sq.m.) Plot Area', '(114 sq.m.) Built-up Area', '(251 sq.m.) Plot Area', '(221 sq.m.) Built-up Area', '(164 sq.m.) Super built-up Area', '(116 sq.m.) Plot Area', '(669 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(112 sq.m.) Super built-up Area', '(121 sq.m.) Super built-up Area', '(167 sq.m.) Plot Area', '(133 sq.m.) Super built-up Area', '(158 sq.m.) Carpet Area', '(122 sq.m.) Super built-up Area', '(213 sq.m.) Plot Area', '(111 sq.m.) Built-up Area', '(150 sq.m.) Built-up Area', '(108 sq.m.) Built-up Area', '(134 sq.m.) Super built-up Area', '(223 sq.m.) Plot Area', '(108 sq.m.) Super built-up Area', '(102 sq.m.) Super built-up Area', '(74 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(279 sq.m.) Plot Area', '(167 sq.m.) Plot Area', '(163 sq.m.) Super built-up Area', '(124 sq.m.) Super built-up Area', '(115 sq.m.) Built-up Area', '(116 sq.m.) Built-up Area', '(332 sq.m.) Plot Area', '(93 sq.m.) Carpet Area', '(138 sq.m.) Plot Area', '(158 sq.m.) Built-up Area', '(223 sq.m.) Plot Area', '(233 sq.m.) Plot Area', '(139 sq.m.) Plot Area', '(128 sq.m.) Super built-up Area', '(241 sq.m.) Carpet Area', '(107 sq.m.) Carpet Area', '(372 sq.m.) Plot Area', '(334 sq.m.) Super built-up Area', '(142 sq.m.) Plot Area', '(119 sq.m.) Super built-up Area', '(56 sq.m.) Plot Area', '(160 sq.m.) Built-up Area', '(93 sq.m.) Super built-up Area', '(483 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(153 sq.m.) Super built-up Area', '(149 sq.m.) Super built-up Area', '(146 sq.m.) Super built-up Area', '(88 sq.m.) Super built-up Area', '(87 sq.m.) Built-up Area', '(223 sq.m.) Plot Area', '(139 sq.m.) Super built-up Area', '(95 sq.m.) Carpet Area', '(118 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(130 sq.m.) Super built-up Area', '(197 sq.m.) Super built-up Area', '(167 sq.m.) Plot Area', '(653 sq.m.) Plot Area', '(127 sq.m.) Carpet Area', '(149 sq.m.) Carpet Area', '(139 sq.m.) Plot Area', '(160 sq.m.) Built-up Area', '(100 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(244 sq.m.) Built-up Area', '(111 sq.m.) Plot Area', '(139 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(85 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(128 sq.m.) Carpet Area', '(100 sq.m.) Built-up Area', '(465 sq.m.) Super built-up Area', '(121 sq.m.) Built-up Area', '(119 sq.m.) Super built-up Area', '(121 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(135 sq.m.) Super built-up Area', '(125 sq.m.) Plot Area', '(204 sq.m.) Plot Area', '(98 sq.m.) Carpet Area', '(115 sq.m.) Super built-up Area', '(193 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(502 sq.m.) Plot Area', '(153 sq.m.) Carpet Area', '(6070 sq.m.) Plot Area', '(126 sq.m.) Plot Area', '(242 sq.m.) Built-up Area', '(214 sq.m.) Plot Area', '(115 sq.m.) Super built-up Area', '(167 sq.m.) Plot Area', '(158 sq.m.) Super built-up Area', '(76 sq.m.) Super built-up Area', '(124 sq.m.) Built-up Area', '(242 sq.m.) Built-up Area', '(102 sq.m.) Built-up Area', '(104 sq.m.) Super built-up Area', '(279 sq.m.) Plot Area', '(142 sq.m.) Super built-up Area', '(84 sq.m.) Built-up Area', '(111 sq.m.) Plot Area', '(186 sq.m.) Plot Area', '(146 sq.m.) Built-up Area', '(117 sq.m.) Carpet Area', '(115 sq.m.) Super built-up Area', '(107 sq.m.) Built-up Area', '(139 sq.m.) Plot Area', '(148 sq.m.) Super built-up Area', '(187 sq.m.) Carpet Area', '(108 sq.m.) Super built-up Area', '(92 sq.m.) Carpet Area', '(101 sq.m.) Super built-up Area', '(118 sq.m.) Super built-up Area', '(418 sq.m.) Carpet Area', '(138 sq.m.) Super built-up Area', '(153 sq.m.) Built-up Area', '(139 sq.m.) Plot Area', '(306 sq.m.) Plot Area', '(223 sq.m.) Plot Area', '(218 sq.m.) Super built-up Area', '(123 sq.m.) Built-up Area', '(186 sq.m.) Built-up Area', '(93 sq.m.) Carpet Area', '(186 sq.m.) Super built-up Area', '(124 sq.m.) Built-up Area', '(101 sq.m.) Carpet Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(145 sq.m.) Super built-up Area', '(105 sq.m.) Super built-up Area', '(69 sq.m.) Built-up Area', '(137 sq.m.) Built-up Area', '(193 sq.m.) Plot Area', '(96 sq.m.) Super built-up Area', '(139 sq.m.) Plot Area', '(190 sq.m.) Super built-up Area', '(137 sq.m.) Super built-up Area', '(209 sq.m.) Built-up Area', '(141 sq.m.) Super built-up Area', '(100 sq.m.) Carpet Area', '(149 sq.m.) Carpet Area', '(203 sq.m.) Plot Area', '(89 sq.m.) Super built-up Area', '(223 sq.m.) Plot Area', '(68 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(223 sq.m.) Plot Area', '(142 sq.m.) Super built-up Area', '(175 sq.m.) Built-up Area', '(184 sq.m.) Plot Area', '(105 sq.m.) Built-up Area', '(104 sq.m.) Super built-up Area', '(124 sq.m.) Carpet Area', '(116 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(117 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(150 sq.m.) Carpet Area', '(418 sq.m.) Built-up Area', '(149 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Super built-up Area', '(72 sq.m.) Carpet Area', '(174 sq.m.) Plot Area', '(87 sq.m.) Super built-up Area', '(131 sq.m.) Carpet Area', '(113 sq.m.) Plot Area', '(141 sq.m.) Super built-up Area', '(153 sq.m.) Super built-up Area', '(94 sq.m.) Super built-up Area', '(46 sq.m.) Carpet Area', '(124 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(247 sq.m.) Plot Area', '(216 sq.m.) Plot Area', '(120 sq.m.) Super built-up Area', '(139 sq.m.) Carpet Area', '(151 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(118 sq.m.) Super built-up Area', '(123 sq.m.) Plot Area', '(110 sq.m.) Carpet Area', '(186 sq.m.) Plot Area', '(223 sq.m.) Plot Area', '(225 sq.m.) Super built-up Area', '(156 sq.m.) Super built-up Area', '(409 sq.m.) Built-up Area', '(195 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(95 sq.m.) Built-up Area', '(139 sq.m.) Super built-up Area', '(511 sq.m.) Plot Area', '(149 sq.m.) Plot Area', '(85 sq.m.) Plot Area', '(279 sq.m.) Plot Area', '(111 sq.m.) Built-up Area', '(119 sq.m.) Super built-up Area', '(3716 sq.m.) Plot Area', '(128 sq.m.) Plot Area', '(195 sq.m.) Plot Area', '(465 sq.m.) Built-up Area', '(150 sq.m.) Super built-up Area', '(98 sq.m.) Plot Area', '(99 sq.m.) Super built-up Area', '(223 sq.m.) Plot Area', '(110 sq.m.) Super built-up Area', '(109 sq.m.) Carpet Area', '(141 sq.m.) Carpet Area', '(133 sq.m.) Super built-up Area', '(124 sq.m.) Super built-up Area', '(446 sq.m.) Plot Area', '(126 sq.m.) Super built-up Area', '(155 sq.m.) Super built-up Area', '(125 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(117 sq.m.) Super built-up Area', '(271 sq.m.) Plot Area', '(111 sq.m.) Carpet Area', '(169 sq.m.) Carpet Area', '(204 sq.m.) Plot Area', '(114 sq.m.) Super built-up Area', '(105 sq.m.) Carpet Area', '(107 sq.m.) Carpet Area', '(427 sq.m.) Super built-up Area', '(86 sq.m.) Carpet Area', '(106 sq.m.) Built-up Area', '(93 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(93 sq.m.) Carpet Area', '(119 sq.m.) Super built-up Area', '(1003 sq.m.) Plot Area', '(129 sq.m.) Super built-up Area', '(111 sq.m.) Super built-up Area', '(111 sq.m.) Carpet Area', '(76 sq.m.) Carpet Area', '(94 sq.m.) Built-up Area', '(223 sq.m.) Plot Area', '(162 sq.m.) Plot Area', '(130 sq.m.) Super built-up Area', '(84 sq.m.) Super built-up Area', '(117 sq.m.) Super built-up Area', '(145 sq.m.) Super built-up Area', '(93 sq.m.) Built-up Area', '(146 sq.m.) Super built-up Area', '(108 sq.m.) Built-up Area', '(98 sq.m.) Super built-up Area', '(143 sq.m.) Built-up Area', '(138 sq.m.) Super built-up Area', '(93 sq.m.) Plot Area', '(118 sq.m.) Plot Area', '(98 sq.m.) Super built-up Area', '(139 sq.m.) Plot Area', '(149 sq.m.) Super built-up Area', '(139 sq.m.) Carpet Area', '(111 sq.m.) Plot Area', '(428 sq.m.) Plot Area', '(474 sq.m.) Built-up Area', '(189 sq.m.) Built-up Area', '(156 sq.m.) Built-up Area', '(111 sq.m.) Built-up Area', '(81 sq.m.) Super built-up Area', '(148 sq.m.) Super built-up Area', '(102 sq.m.) Carpet Area', '(139 sq.m.) Plot Area', '(153 sq.m.) Plot Area', '(81 sq.m.) Carpet Area', '(153 sq.m.) Carpet Area', '(109 sq.m.) Built-up Area', '(125 sq.m.) Plot Area', '(115 sq.m.) Plot Area', '(140 sq.m.) Built-up Area', '(163 sq.m.) Carpet Area', '(111 sq.m.) Plot Area', '(708200 sq.m.) Plot Area', '(93 sq.m.) Super built-up Area', '(1338 sq.m.) Plot Area', '(126 sq.m.) Carpet Area', '(372 sq.m.) Super built-up Area', '(119 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(165 sq.m.) Super built-up Area', '(78 sq.m.) Super built-up Area', '(111 sq.m.) Carpet Area', '(163 sq.m.) Plot Area', '(473 sq.m.) Super built-up Area', '(84 sq.m.) Super built-up Area', '(172 sq.m.) Super built-up Area', '(111 sq.m.) Plot Area', '(111 sq.m.) Plot Area', '(123 sq.m.) Super built-up Area', '(390 sq.m.) Plot Area', '(89 sq.m.) Plot Area', '(124 sq.m.) Super built-up Area']

In [44]:
characters_to_remove = ["("," sq.m.) ","Built-up Area","Super built-up Area","Carpet Area","Plot Area","-"]

#regular expression pattern to match and remove special characters and characters
pattern = "[{}]".format("".join(characters_to_remove))

#list to store modified strings
area_sqm = []

for string in builtup_area:
    modified_string = re.sub(pattern, "", string)
    area_sqm.append(modified_string)

print(area_sqm)

['1111115', '3843', '43', '3843', '3843', '58', '3843', '212', '99', '108', '183', '279', '288', '325', '86', '125', '136', '107', '223', '128', '111', '111', '138', '341', '190', '105', '223', '372', '248', '114', '251', '221', '164', '116', '669', '111', '112', '121', '167', '133', '158', '122', '213', '111', '150', '108', '134', '223', '108', '102', '74', '111', '279', '167', '163', '124', '115', '116', '332', '93', '138', '158', '223', '233', '139', '128', '241', '107', '372', '334', '142', '119', '56', '160', '93', '483', '111', '153', '149', '146', '88', '87', '223', '139', '95', '118', '111', '111', '130', '197', '167', '653', '127', '149', '139', '160', '100', '111', '244', '111', '139', '111', '85', '111', '128', '100', '465', '121', '119', '121', '111', '135', '125', '204', '98', '115', '193', '111', '502', '153', '6070', '126', '242', '214', '115', '167', '158', '76', '124', '242', '102', '104', '279', '142', '84', '111', '186', '146', '117', '115', '107', '139', '148', '187', '108', '92', '101', '118', '418', '138', '153', '139', '306', '223', '218', '123', '186', '93', '186', '124', '101', '111', '111', '145', '105', '69', '137', '193', '96', '139', '190', '137', '209', '141', '100', '149', '203', '89', '223', '68', '111', '223', '142', '175', '184', '105', '104', '124', '116', '111', '117', '111', '150', '418', '149', '111', '111', '72', '174', '87', '131', '113', '141', '153', '94', '46', '124', '111', '247', '216', '120', '139', '151', '111', '118', '123', '110', '186', '223', '225', '156', '409', '195', '111', '95', '139', '511', '149', '85', '279', '111', '119', '3716', '128', '195', '465', '150', '98', '99', '223', '110', '109', '141', '133', '124', '446', '126', '155', '125', '111', '117', '271', '111', '169', '204', '114', '105', '107', '427', '86', '106', '93', '111', '111', '93', '119', '1003', '129', '111', '111', '76', '94', '223', '162', '130', '84', '117', '145', '93', '146', '108', '98', '143', '138', '93', '118', '98', '139', '149', '139', '111', '428', '474', '189', '156', '111', '81', '148', '102', '139', '153', '81', '153', '109', '125', '115', '140', '163', '111', '708200', '93', '1338', '126', '372', '119', '111', '165', '78', '111', '163', '473', '84', '172', '111', '111', '123', '390', '89', '124']

In [45]:
BuiltUp_Area_Sqm = [int(x) for x in area_sqm]

print(BuiltUp_Area_Sqm)

[1111115, 3843, 43, 3843, 3843, 58, 3843, 212, 99, 108, 183, 279, 288, 325, 86, 125, 136, 107, 223, 128, 111, 111, 138, 341, 190, 105, 223, 372, 248, 114, 251, 221, 164, 116, 669, 111, 112, 121, 167, 133, 158, 122, 213, 111, 150, 108, 134, 223, 108, 102, 74, 111, 279, 167, 163, 124, 115, 116, 332, 93, 138, 158, 223, 233, 139, 128, 241, 107, 372, 334, 142, 119, 56, 160, 93, 483, 111, 153, 149, 146, 88, 87, 223, 139, 95, 118, 111, 111, 130, 197, 167, 653, 127, 149, 139, 160, 100, 111, 244, 111, 139, 111, 85, 111, 128, 100, 465, 121, 119, 121, 111, 135, 125, 204, 98, 115, 193, 111, 502, 153, 6070, 126, 242, 214, 115, 167, 158, 76, 124, 242, 102, 104, 279, 142, 84, 111, 186, 146, 117, 115, 107, 139, 148, 187, 108, 92, 101, 118, 418, 138, 153, 139, 306, 223, 218, 123, 186, 93, 186, 124, 101, 111, 111, 145, 105, 69, 137, 193, 96, 139, 190, 137, 209, 141, 100, 149, 203, 89, 223, 68, 111, 223, 142, 175, 184, 105, 104, 124, 116, 111, 117, 111, 150, 418, 149, 111, 111, 72, 174, 87, 131, 113, 141, 153, 94, 46, 124, 111, 247, 216, 120, 139, 151, 111, 118, 123, 110, 186, 223, 225, 156, 409, 195, 111, 95, 139, 511, 149, 85, 279, 111, 119, 3716, 128, 195, 465, 150, 98, 99, 223, 110, 109, 141, 133, 124, 446, 126, 155, 125, 111, 117, 271, 111, 169, 204, 114, 105, 107, 427, 86, 106, 93, 111, 111, 93, 119, 1003, 129, 111, 111, 76, 94, 223, 162, 130, 84, 117, 145, 93, 146, 108, 98, 143, 138, 93, 118, 98, 139, 149, 139, 111, 428, 474, 189, 156, 111, 81, 148, 102, 139, 153, 81, 153, 109, 125, 115, 140, 163, 111, 708200, 93, 1338, 126, 372, 119, 111, 165, 78, 111, 163, 473, 84, 172, 111, 111, 123, 390, 89, 124]

In [46]:
total_price=[i*j for i in Price_per_SqFt for j in BuiltUp_Area_Sqm]
total_price

[1222226500,
 4227300,
 47300,
 4227300,
 4227300,
 63800,
 4227300,
 233200,
 108900,
 118800,
 201300,
 306900,
 316800,
 357500,
 94600,
 137500,
 149600,
 117700,
 245300,
 140800,
 122100,
 122100,
 151800,
 375100,
 209000,
 115500,
 245300,
 409200,
 272800,
 125400,
 276100,
 243100,
 180400,
 127600,
 735900,
 122100,
 123200,
 133100,
 183700,
 146300,
 173800,
 134200,
 234300,
 122100,
 165000,
 118800,
 147400,
 245300,
 118800,
 112200,
 81400,
 122100,
 306900,
 183700,
 179300,
 136400,
 126500,
 127600,
 365200,
 102300,
 151800,
 173800,
 245300,
 256300,
 152900,
 140800,
 265100,
 117700,
 409200,
 367400,
 156200,
 130900,
 61600,
 176000,
 102300,
 531300,
 122100,
 168300,
 163900,
 160600,
 96800,
 95700,
 245300,
 152900,
 104500,
 129800,
 122100,
 122100,
 143000,
 216700,
 183700,
 718300,
 139700,
 163900,
 152900,
 176000,
 110000,
 122100,
 268400,
 122100,
 152900,
 122100,
 93500,
 122100,
 140800,
 110000,
 511500,
 133100,
 130900,
 133100,
 122100,
 148500,
 137500,
 224400,
 107800,
 126500,
 212300,
 122100,
 552200,
 168300,
 6677000,
 138600,
 266200,
 235400,
 126500,
 183700,
 173800,
 83600,
 136400,
 266200,
 112200,
 114400,
 306900,
 156200,
 92400,
 122100,
 204600,
 160600,
 128700,
 126500,
 117700,
 152900,
 162800,
 205700,
 118800,
 101200,
 111100,
 129800,
 459800,
 151800,
 168300,
 152900,
 336600,
 245300,
 239800,
 135300,
 204600,
 102300,
 204600,
 136400,
 111100,
 122100,
 122100,
 159500,
 115500,
 75900,
 150700,
 212300,
 105600,
 152900,
 209000,
 150700,
 229900,
 155100,
 110000,
 163900,
 223300,
 97900,
 245300,
 74800,
 122100,
 245300,
 156200,
 192500,
 202400,
 115500,
 114400,
 136400,
 127600,
 122100,
 128700,
 122100,
 165000,
 459800,
 163900,
 122100,
 122100,
 79200,
 191400,
 95700,
 144100,
 124300,
 155100,
 168300,
 103400,
 50600,
 136400,
 122100,
 271700,
 237600,
 132000,
 152900,
 166100,
 122100,
 129800,
 135300,
 121000,
 204600,
 245300,
 247500,
 171600,
 449900,
 214500,
 122100,
 104500,
 152900,
 562100,
 163900,
 93500,
 306900,
 122100,
 130900,
 4087600,
 140800,
 214500,
 511500,
 165000,
 107800,
 108900,
 245300,
 121000,
 119900,
 155100,
 146300,
 136400,
 490600,
 138600,
 170500,
 137500,
 122100,
 128700,
 298100,
 122100,
 185900,
 224400,
 125400,
 115500,
 117700,
 469700,
 94600,
 116600,
 102300,
 122100,
 122100,
 102300,
 130900,
 1103300,
 141900,
 122100,
 122100,
 83600,
 103400,
 245300,
 178200,
 143000,
 92400,
 128700,
 159500,
 102300,
 160600,
 118800,
 107800,
 157300,
 151800,
 102300,
 129800,
 107800,
 152900,
 163900,
 152900,
 122100,
 470800,
 521400,
 207900,
 171600,
 122100,
 89100,
 162800,
 112200,
 152900,
 168300,
 89100,
 168300,
 119900,
 137500,
 126500,
 154000,
 179300,
 122100,
 779020000,
 102300,
 1471800,
 138600,
 409200,
 130900,
 122100,
 181500,
 85800,
 122100,
 179300,
 520300,
 92400,
 189200,
 122100,
 122100,
 135300,
 429000,
 97900,
 136400,
 12138931375,
 41984775,
 469775,
 41984775,
 41984775,
 633650,
 41984775,
 2316100,
 1081575,
 1179900,
 1999275,
 3048075,
 3146400,
 3550625,
 939550,
 1365625,
 1485800,
 1168975,
 2436275,
 1398400,
 1212675,
 1212675,
 1507650,
 3725425,
 2075750,
 1147125,
 2436275,
 4064100,
 2709400,
 1245450,
 2742175,
 2414425,
 1791700,
 1267300,
 7308825,
 1212675,
 1223600,
 1321925,
 1824475,
 1453025,
 1726150,
 1332850,
 2327025,
 1212675,
 1638750,
 1179900,
 1463950,
 2436275,
 1179900,
 1114350,
 808450,
 1212675,
 3048075,
 1824475,
 1780775,
 1354700,
 1256375,
 1267300,
 3627100,
 1016025,
 1507650,
 1726150,
 2436275,
 2545525,
 1518575,
 1398400,
 2632925,
 1168975,
 4064100,
 3648950,
 1551350,
 1300075,
 611800,
 1748000,
 1016025,
 5276775,
 1212675,
 1671525,
 1627825,
 1595050,
 961400,
 950475,
 2436275,
 1518575,
 1037875,
 1289150,
 1212675,
 1212675,
 1420250,
 2152225,
 1824475,
 7134025,
 1387475,
 1627825,
 1518575,
 1748000,
 1092500,
 1212675,
 2665700,
 1212675,
 1518575,
 1212675,
 928625,
 1212675,
 1398400,
 1092500,
 5080125,
 1321925,
 1300075,
 1321925,
 1212675,
 1474875,
 1365625,
 2228700,
 1070650,
 1256375,
 2108525,
 1212675,
 5484350,
 1671525,
 66314750,
 1376550,
 2643850,
 2337950,
 1256375,
 1824475,
 1726150,
 830300,
 1354700,
 2643850,
 1114350,
 1136200,
 3048075,
 1551350,
 917700,
 1212675,
 2032050,
 1595050,
 1278225,
 1256375,
 1168975,
 1518575,
 1616900,
 2042975,
 1179900,
 1005100,
 1103425,
 1289150,
 4566650,
 1507650,
 1671525,
 1518575,
 3343050,
 2436275,
 2381650,
 1343775,
 2032050,
 1016025,
 2032050,
 1354700,
 1103425,
 1212675,
 1212675,
 1584125,
 1147125,
 753825,
 1496725,
 2108525,
 1048800,
 1518575,
 2075750,
 1496725,
 2283325,
 1540425,
 1092500,
 1627825,
 2217775,
 972325,
 2436275,
 742900,
 1212675,
 2436275,
 1551350,
 1911875,
 2010200,
 1147125,
 1136200,
 1354700,
 1267300,
 1212675,
 1278225,
 1212675,
 1638750,
 4566650,
 1627825,
 1212675,
 1212675,
 786600,
 1900950,
 950475,
 1431175,
 1234525,
 1540425,
 1671525,
 1026950,
 502550,
 1354700,
 1212675,
 2698475,
 2359800,
 1311000,
 1518575,
 1649675,
 1212675,
 1289150,
 1343775,
 1201750,
 2032050,
 2436275,
 2458125,
 1704300,
 4468325,
 2130375,
 1212675,
 1037875,
 1518575,
 5582675,
 1627825,
 928625,
 3048075,
 1212675,
 1300075,
 40597300,
 1398400,
 2130375,
 5080125,
 1638750,
 1070650,
 1081575,
 2436275,
 1201750,
 1190825,
 1540425,
 1453025,
 1354700,
 4872550,
 1376550,
 1693375,
 1365625,
 1212675,
 1278225,
 2960675,
 1212675,
 1846325,
 2228700,
 1245450,
 1147125,
 1168975,
 4664975,
 939550,
 1158050,
 1016025,
 1212675,
 1212675,
 1016025,
 1300075,
 10957775,
 1409325,
 1212675,
 1212675,
 830300,
 1026950,
 2436275,
 1769850,
 1420250,
 917700,
 1278225,
 1584125,
 1016025,
 1595050,
 1179900,
 1070650,
 1562275,
 1507650,
 1016025,
 1289150,
 1070650,
 1518575,
 1627825,
 1518575,
 1212675,
 4675900,
 5178450,
 2064825,
 1704300,
 1212675,
 884925,
 1616900,
 1114350,
 1518575,
 1671525,
 884925,
 1671525,
 1190825,
 1365625,
 1256375,
 1529500,
 1780775,
 1212675,
 7737085000,
 1016025,
 14617650,
 1376550,
 4064100,
 1300075,
 1212675,
 1802625,
 852150,
 1212675,
 1780775,
 5167525,
 917700,
 1879100,
 1212675,
 1212675,
 1343775,
 4260750,
 972325,
 1354700,
 12050042175,
 41677335,
 466335,
 41677335,
 41677335,
 629010,
 41677335,
 2299140,
 1073655,
 1171260,
 1984635,
 3025755,
 3123360,
 3524625,
 932670,
 1355625,
 1474920,
 1160415,
 2418435,
 1388160,
 1203795,
 1203795,
 1496610,
 3698145,
 2060550,
 1138725,
 2418435,
 4034340,
 2689560,
 1236330,
 2722095,
 2396745,
 1778580,
 1258020,
 7255305,
 1203795,
 1214640,
 1312245,
 1811115,
 1442385,
 1713510,
 1323090,
 2309985,
 1203795,
 1626750,
 1171260,
 1453230,
 2418435,
 1171260,
 1106190,
 802530,
 1203795,
 3025755,
 1811115,
 1767735,
 1344780,
 1247175,
 1258020,
 3600540,
 1008585,
 1496610,
 1713510,
 2418435,
 2526885,
 1507455,
 1388160,
 2613645,
 1160415,
 4034340,
 3622230,
 1539990,
 1290555,
 607320,
 1735200,
 1008585,
 5238135,
 1203795,
 1659285,
 1615905,
 1583370,
 954360,
 943515,
 2418435,
 1507455,
 1030275,
 1279710,
 1203795,
 1203795,
 1409850,
 2136465,
 1811115,
 7081785,
 1377315,
 1615905,
 1507455,
 1735200,
 1084500,
 1203795,
 2646180,
 1203795,
 1507455,
 1203795,
 921825,
 1203795,
 1388160,
 1084500,
 5042925,
 1312245,
 1290555,
 1312245,
 1203795,
 1464075,
 1355625,
 2212380,
 1062810,
 1247175,
 2093085,
 1203795,
 5444190,
 1659285,
 65829150,
 1366470,
 2624490,
 2320830,
 1247175,
 1811115,
 1713510,
 824220,
 1344780,
 2624490,
 1106190,
 1127880,
 3025755,
 1539990,
 910980,
 1203795,
 2017170,
 1583370,
 1268865,
 1247175,
 1160415,
 1507455,
 1605060,
 2028015,
 1171260,
 997740,
 1095345,
 1279710,
 4533210,
 1496610,
 1659285,
 1507455,
 3318570,
 2418435,
 2364210,
 1333935,
 2017170,
 1008585,
 2017170,
 1344780,
 1095345,
 1203795,
 1203795,
 1572525,
 1138725,
 748305,
 1485765,
 2093085,
 1041120,
 1507455,
 2060550,
 1485765,
 2266605,
 1529145,
 1084500,
 1615905,
 2201535,
 965205,
 2418435,
 737460,
 1203795,
 2418435,
 1539990,
 1897875,
 1995480,
 1138725,
 1127880,
 1344780,
 1258020,
 1203795,
 1268865,
 1203795,
 1626750,
 4533210,
 1615905,
 1203795,
 1203795,
 780840,
 1887030,
 943515,
 1420695,
 1225485,
 1529145,
 1659285,
 1019430,
 498870,
 1344780,
 1203795,
 2678715,
 2342520,
 1301400,
 1507455,
 1637595,
 1203795,
 1279710,
 1333935,
 1192950,
 2017170,
 2418435,
 2440125,
 1691820,
 4435605,
 2114775,
 1203795,
 1030275,
 1507455,
 5541795,
 1615905,
 921825,
 3025755,
 1203795,
 1290555,
 40300020,
 1388160,
 2114775,
 5042925,
 1626750,
 1062810,
 1073655,
 2418435,
 1192950,
 1182105,
 1529145,
 1442385,
 1344780,
 4836870,
 1366470,
 1680975,
 1355625,
 1203795,
 1268865,
 2938995,
 1203795,
 1832805,
 2212380,
 1236330,
 1138725,
 1160415,
 4630815,
 932670,
 1149570,
 1008585,
 1203795,
 1203795,
 1008585,
 1290555,
 10877535,
 1399005,
 1203795,
 1203795,
 824220,
 1019430,
 2418435,
 1756890,
 1409850,
 910980,
 1268865,
 1572525,
 1008585,
 1583370,
 1171260,
 1062810,
 1550835,
 1496610,
 1008585,
 1279710,
 1062810,
 1507455,
 1615905,
 1507455,
 1203795,
 4641660,
 5140530,
 2049705,
 1691820,
 1203795,
 878445,
 1605060,
 1106190,
 1507455,
 1659285,
 878445,
 1659285,
 1182105,
 1355625,
 1247175,
 1518300,
 1767735,
 1203795,
 7680429000,
 1008585,
 14510610,
 1366470,
 4034340,
 1290555,
 1203795,
 1789425,
 845910,
 1203795,
 1767735,
 5129685,
 910980,
 1865340,
 1203795,
 1203795,
 1333935,
 4229550,
 965205,
 1344780,
 12138931375,
 41984775,
 469775,
 41984775,
 41984775,
 633650,
 41984775,
 2316100,
 1081575,
 1179900,
 1999275,
 3048075,
 3146400,
 ...]

# bath

In [47]:
baths = df['bhk'].tolist()

print(baths)

[nan, '1 BHK1 Bath', '1 BHK1 Bath', '1 BHK1 Bath', '1 BHK1 Bath', '2 BHK', '1 BHK1 Bath', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '11 BHK11 Baths', '6 BHK5 Baths', '5 BHK5 Baths', '5 BHK4 Baths', '3 BHK2 Baths', '3 BHK2 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '5 BHK4 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '12 BHK12 Baths', '2 BHK2 Baths', nan, '3 BHK3 Baths', '2 BHK2 Baths', '6 BHK7 Baths', '9 BHK8 Baths', '3 BHK4 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK4 Baths', '3 BHK3 Baths', '7 BHK7 Baths', nan, nan, '2 BHK2 Baths', '2 BHK2 Baths', nan, '3 BHK2 Baths', '3 BHK3 Baths', '3 BHK3 Baths', nan, '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '3 BHK3 Baths', nan, '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '6 BHK5 Baths', nan, '1 BHK1 Bath', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', nan, '2 BHK2 Baths', nan, '3 BHK3 Baths', nan, '3 BHK4 Baths', '5 BHK5 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', nan, '4 BHK4 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '4 BHK2 Baths', '4 BHK4 Baths', '2 BHK2 Baths', '9 BHK9 Baths', '11 BHK11 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '5 BHK8 Baths', '3 BHK2 Baths', '2 BHK1 Bath', '14 BHK13 Baths', nan, nan, '2 BHK2 Baths', '3 BHK4 Baths', nan, nan, '2 BHK2 Baths', '3 BHK3 Baths', nan, '3 BHK3 Baths', '2 BHK2 Baths', '6 BHK6 Baths', '3 BHK3 Baths', nan, nan, '3 BHK3 Baths', '2 BHK2 Baths', nan, '2 BHK2 Baths', '3 BHK2 Baths', '6 BHK7 Baths', '2 BHK2 Baths', '2 BHK2 Baths', nan, '4 BHK4 Baths', '3 BHK2 Baths', '11 BHK11 Baths', nan, '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', nan, '7 BHK9 Baths', '3 BHK3 Baths', '3 BHK4 Baths', '12 BHK8 Baths', '3 BHK4 Baths', '3 BHK4 Baths', '3 BHK2 Baths', '8 BHK7 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '4 BHK4 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '12 BHK8 Baths', '3 BHK3 Baths', '2 BHK2 Baths', nan, nan, '3 BHK3 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '4 BHK4 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '4 BHK4 Baths', '2 BHK2 Baths', '3 BHK3 Baths', nan, nan, nan, '3 BHK4 Baths', '3 BHK2 Baths', '4 BHK3 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '13 BHK12 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK1 Bath', '3 BHK2 Baths', '12 BHK11 Baths', '2 BHK2 Baths', nan, '3 BHK3 Baths', '3 BHK2 Baths', '9 BHK9 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '4 BHK4 Baths', '2 BHK2 Baths', nan, nan, '3 BHK3 Baths', nan, '3 BHK2 Baths', '3 BHK3 Baths', nan, '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '4 BHK4 Baths', '4 BHK4 Baths', '7 BHK8 Baths', '3 BHK2 Baths', '4 BHK4 Baths', '3 BHK3 Baths', nan, '2 BHK2 Baths', '1 BHK1 Bath', '1 BHK1 Bath', '2 BHK2 Baths', '3 BHK2 Baths', '6 BHK3 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '1 BHK1 Bath', '3 BHK2 Baths', nan, '14 BHK14 Baths', '3 BHK5 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '3 BHK2 Baths', nan, '2 BHK2 Baths', nan, '3 BHK2 Baths', nan, '4 BHK4 Baths', '4 BHK4 Baths', '3 BHK3 Baths', '4 BHK4 Baths', nan, '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', nan, nan, '2 BHK3 Baths', nan, '2 BHK2 Baths', '3 BHK3 Baths', nan, '7 BHK7 Baths', '4 BHK4 Baths', '10 BHK9 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK4 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '3 BHK2 Baths', '2 BHK2 Baths', nan, '3 BHK2 Baths', '3 BHK3 Baths', '3 BHK2 Baths', nan, '2 BHK2 Baths', nan, '2 BHK3 Baths', '3 BHK3 Baths', '4 BHK4 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '9 BHK9 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '5 BHK4 Baths', '2 BHK2 Baths', nan, '2 BHK2 Baths', '2 BHK2 Baths', nan, '3 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', nan, nan, '3 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '3 BHK2 Baths', '2 BHK2 Baths', nan, '4 BHK4 Baths', '12 BHK12 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '2 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '2 BHK2 Baths', nan, nan, '2 BHK2 Baths', '3 BHK3 Baths', '2 BHK2 Baths', nan, '5 BHK4 Baths', '3 BHK3 Baths', '3 BHK2 Baths', '14 BHK14 Baths', nan, '2 BHK2 Baths', nan, '3 BHK2 Baths', '4 BHK4 Baths', '3 BHK3 Baths', '11 BHK10 Baths', '3 BHK3 Baths', '3 BHK2 Baths', '2 BHK2 Baths', '3 BHK2 Baths', '4 BHK4 Baths', '2 BHK2 Baths', '3 BHK3 Baths', '3 BHK3 Baths', '9 BHK6 Baths', '3 BHK3 Baths', nan, nan, '3 BHK3 Baths']

In [48]:
Baths = [re.search(r'\d+', x).group() if x is not np.nan else x for x in baths]

print(Baths)

[nan, '1', '1', '1', '1', '2', '1', '3', '2', '2', '11', '6', '5', '5', '3', '3', '3', '2', '5', '3', '2', '12', '2', nan, '3', '2', '6', '9', '3', '2', '2', '3', '3', '7', nan, nan, '2', '2', nan, '3', '3', '3', nan, '2', '3', '2', '3', nan, '2', '2', '3', '6', nan, '1', '3', '2', '2', '3', nan, '2', nan, '3', nan, '3', '5', '2', '3', '2', nan, '4', '3', '2', '4', '4', '2', '9', '11', '3', '3', '3', '2', '2', '5', '3', '2', '14', nan, nan, '2', '3', nan, nan, '2', '3', nan, '3', '2', '6', '3', nan, nan, '3', '2', nan, '2', '3', '6', '2', '2', nan, '4', '3', '11', nan, '2', '2', '3', nan, '7', '3', '3', '12', '3', '3', '3', '8', '3', '2', '2', '4', '2', '2', '12', '3', '2', nan, nan, '3', '2', '3', '2', '4', '3', '3', '2', '2', '2', '2', '4', '2', '3', nan, nan, nan, '3', '3', '4', '2', '3', '3', '2', '13', '2', '2', '2', '2', '3', '12', '2', nan, '3', '3', '9', '3', '2', '3', '4', '2', nan, nan, '3', nan, '3', '3', nan, '2', '2', '3', '2', '4', '4', '7', '3', '4', '3', nan, '2', '1', '1', '2', '3', '6', '3', '3', '2', '1', '3', nan, '14', '3', '2', '3', '3', nan, '2', nan, '3', nan, '4', '4', '3', '4', nan, '2', '2', '3', nan, nan, '2', nan, '2', '3', nan, '7', '4', '10', '3', '2', '2', '3', '2', '2', '3', '3', '2', nan, '3', '3', '3', nan, '2', nan, '2', '3', '4', '2', '2', '2', '9', '2', '3', '5', '2', nan, '2', '2', nan, '3', '2', '3', '2', '2', nan, nan, '3', '2', '2', '3', '2', '3', '2', '2', '3', '3', '2', '2', '2', '3', '3', '2', nan, '4', '12', '3', '3', '2', '2', '3', '2', nan, nan, '2', '3', '2', nan, '5', '3', '3', '14', nan, '2', nan, '3', '4', '3', '11', '3', '3', '2', '3', '4', '2', '3', '3', '9', '3', nan, nan, '3']

In [49]:
for i in range(len(Baths)):
    try:
        if np.isnan(float(Baths[i])):
            Baths[i] = 0
    except:
        pass

print(Baths)

[0, '1', '1', '1', '1', '2', '1', '3', '2', '2', '11', '6', '5', '5', '3', '3', '3', '2', '5', '3', '2', '12', '2', 0, '3', '2', '6', '9', '3', '2', '2', '3', '3', '7', 0, 0, '2', '2', 0, '3', '3', '3', 0, '2', '3', '2', '3', 0, '2', '2', '3', '6', 0, '1', '3', '2', '2', '3', 0, '2', 0, '3', 0, '3', '5', '2', '3', '2', 0, '4', '3', '2', '4', '4', '2', '9', '11', '3', '3', '3', '2', '2', '5', '3', '2', '14', 0, 0, '2', '3', 0, 0, '2', '3', 0, '3', '2', '6', '3', 0, 0, '3', '2', 0, '2', '3', '6', '2', '2', 0, '4', '3', '11', 0, '2', '2', '3', 0, '7', '3', '3', '12', '3', '3', '3', '8', '3', '2', '2', '4', '2', '2', '12', '3', '2', 0, 0, '3', '2', '3', '2', '4', '3', '3', '2', '2', '2', '2', '4', '2', '3', 0, 0, 0, '3', '3', '4', '2', '3', '3', '2', '13', '2', '2', '2', '2', '3', '12', '2', 0, '3', '3', '9', '3', '2', '3', '4', '2', 0, 0, '3', 0, '3', '3', 0, '2', '2', '3', '2', '4', '4', '7', '3', '4', '3', 0, '2', '1', '1', '2', '3', '6', '3', '3', '2', '1', '3', 0, '14', '3', '2', '3', '3', 0, '2', 0, '3', 0, '4', '4', '3', '4', 0, '2', '2', '3', 0, 0, '2', 0, '2', '3', 0, '7', '4', '10', '3', '2', '2', '3', '2', '2', '3', '3', '2', 0, '3', '3', '3', 0, '2', 0, '2', '3', '4', '2', '2', '2', '9', '2', '3', '5', '2', 0, '2', '2', 0, '3', '2', '3', '2', '2', 0, 0, '3', '2', '2', '3', '2', '3', '2', '2', '3', '3', '2', '2', '2', '3', '3', '2', 0, '4', '12', '3', '3', '2', '2', '3', '2', 0, 0, '2', '3', '2', 0, '5', '3', '3', '14', 0, '2', 0, '3', '4', '3', '11', '3', '3', '2', '3', '4', '2', '3', '3', '9', '3', 0, 0, '3']

In [50]:
for i in range(len(Baths)):
    try:
        Baths[i] = int(Baths[i])
    except:
        pass
print(Baths)

[0, 1, 1, 1, 1, 2, 1, 3, 2, 2, 11, 6, 5, 5, 3, 3, 3, 2, 5, 3, 2, 12, 2, 0, 3, 2, 6, 9, 3, 2, 2, 3, 3, 7, 0, 0, 2, 2, 0, 3, 3, 3, 0, 2, 3, 2, 3, 0, 2, 2, 3, 6, 0, 1, 3, 2, 2, 3, 0, 2, 0, 3, 0, 3, 5, 2, 3, 2, 0, 4, 3, 2, 4, 4, 2, 9, 11, 3, 3, 3, 2, 2, 5, 3, 2, 14, 0, 0, 2, 3, 0, 0, 2, 3, 0, 3, 2, 6, 3, 0, 0, 3, 2, 0, 2, 3, 6, 2, 2, 0, 4, 3, 11, 0, 2, 2, 3, 0, 7, 3, 3, 12, 3, 3, 3, 8, 3, 2, 2, 4, 2, 2, 12, 3, 2, 0, 0, 3, 2, 3, 2, 4, 3, 3, 2, 2, 2, 2, 4, 2, 3, 0, 0, 0, 3, 3, 4, 2, 3, 3, 2, 13, 2, 2, 2, 2, 3, 12, 2, 0, 3, 3, 9, 3, 2, 3, 4, 2, 0, 0, 3, 0, 3, 3, 0, 2, 2, 3, 2, 4, 4, 7, 3, 4, 3, 0, 2, 1, 1, 2, 3, 6, 3, 3, 2, 1, 3, 0, 14, 3, 2, 3, 3, 0, 2, 0, 3, 0, 4, 4, 3, 4, 0, 2, 2, 3, 0, 0, 2, 0, 2, 3, 0, 7, 4, 10, 3, 2, 2, 3, 2, 2, 3, 3, 2, 0, 3, 3, 3, 0, 2, 0, 2, 3, 4, 2, 2, 2, 9, 2, 3, 5, 2, 0, 2, 2, 0, 3, 2, 3, 2, 2, 0, 0, 3, 2, 2, 3, 2, 3, 2, 2, 3, 3, 2, 2, 2, 3, 3, 2, 0, 4, 12, 3, 3, 2, 2, 3, 2, 0, 0, 2, 3, 2, 0, 5, 3, 3, 14, 0, 2, 0, 3, 4, 3, 11, 3, 3, 2, 3, 4, 2, 3, 3, 9, 3, 0, 0, 3]

In [51]:
len(Baths)

329

In [52]:
print(len(bhk))
print(len(Total_SqFt))
print(len(BuiltUp_Area_Sqm))
print(len(Price_per_SqFt))
print(len(type_of_land))
print(len(loc))
print(len(new_matches))

329
329
329
329
329
329
329

In [53]:
df=pd.DataFrame({'BHK':bhk,'Baths':Baths,'Total_Area_SqFt':Total_SqFt,"Price_per_SqFt":Price_per_SqFt,"Type_of_Land":type_of_land,'Area':loc,'Price':new_matches})
df['Location']='Bengaluru'
df

,BHK,Baths,Total_Area_SqFt,Price_per_SqFt,Type_of_Land,Area,Price,Location
0,0,0,12000,1100,Residential land / Plot,Devanahalli,1320000,Bengaluru
1,1,1,461,10925,Apartment,Thanisandra,4511000,Bengaluru
2,1,1,461,10845,Apartment,Thanisandra,5000000,Bengaluru
3,1,1,461,10925,Apartment,Thanisandra,4511000,Bengaluru
4,1,1,461,10925,Apartment,Thanisandra,4511000,Bengaluru
...,...,...,...,...,...,...,...,...
324,9,9,1200,3541,Bedroom House,Electronics City Phase 1,17000000,Bengaluru
325,3,3,1327,4898,Apartment,Himagiri Meadows,6000000,Bengaluru
326,0,0,4200,45238,Residential land / Plot,Raj Mahal Vilas Extension,1900000,Bengaluru
327,0,0,960,11650,Residential land / Plot,Singasandra,11200000,Bengaluru
328,3,3,1330,4428,Apartment,Kadugodi,5800000,Bengaluru

In [54]:
df.to_excel('Buy_Data.xlsx')